### ISSUE TITLE
trimLeft error

### ISSUE THREAD

**Issue by hotrush** [lodash/lodash#1059]
Described here http://jsfiddle.net/qym6r6oy/1/

**Comment by octref** [comment]
The thing is, maybe you think this
`_.trimLeft('ba_b', 'ba_')`
Would return `b`.
But it should return `''`, because all the four characters in `ba_b` are in the character set of `ba_`.
The trimming happens like "from the beginning, trim characters from `string` which appears in `chars`, only stop at the char which doesn't belong to `chars`.

**Comment by hotrush** [comment]
Hm, so it's trim all characters set and not depends from order? strange behavior

**Comment by StreetStrider** [comment]
Possible solution is to distinct `'ba_'` and `[ 'b', 'a', '_' ]`, where first woluld mean «all characters in same order» and the second «any of characters in list».  But it would be breaking change.

The issue is closed, I think @jdalton may not notice it.

**Comment by hotrush** [comment]
I think str.replace(one,two) will be easier)

**Comment by StreetStrider** [comment]
@hotrush, quite right. But you'll need not simple string, but regular expression (`/^stuff/`). If prefix is variable too, you'll also need to ugly regexp constructing via `new RegExp(^stuff`.

**Comment by hotrush** [comment]
@StreetStrider agreed. Thanks for help.

**Comment by jdalton** [comment]
The behavior is is based on several other trim implementations like:

https://github.com/epeli/underscore.string#trimstring-characters--string
http://moutjs.com/docs/latest/string.html#trim
