### ISSUE TITLE
Downloading v3.6.0-amd

### ISSUE THREAD

**Issue by nwhite89** [lodash/lodash#1106]
Not sure if I'm doing something wrong I am trying to download the AMD version of lodash, I'm expecting to get access to all of the individual lodash helpers individually except within my ``bower_components`` folder I am getting a lodash folder with ``lodash.js`` containing the entire thing? Am I doing something wrong?

In my bower.json file I have:
```
"dependencies": {
    "lodash": "~3.6.0-amd"
  }
```

bower output:
```
bower lodash#~3.6.0-amd     not-cached git://github.com/lodash/lodash.git#~3.6.0-amd
bower lodash#~3.6.0-amd        resolve git://github.com/lodash/lodash.git#~3.6.0-amd
bower lodash#~3.6.0-amd       download https://github.com/lodash/lodash/archive/3.6.0.tar.gz
bower lodash#~3.6.0-amd        extract archive.tar.gz
bower lodash#~3.6.0-amd       resolved git://github.com/lodash/lodash.git#3.6.0
bower lodash#~3.6.0-amd        install lodash#3.6.0
```

Thanks in advanced

**Comment by jdalton** [comment]
From the output it's resolving the master branch. Double check your bower request for tags/branches and try it without the ~ too.

**Comment by nwhite89** [comment]
removing the ``~`` fixed it, slightly annoying as it means it won't automatically update on versions but nvm thanks @jdalton

**Comment by d10** [comment]
This is because when using versions with a dash after numbers, eg. `3.6.0-amd`, Bower and other package management systems treat it as a "beta" release, eg. `3.6.0-rc`. So when using `~`, Bower tries to get what it thinks is the latest version of that release, which is `3.6.0`. So it's kinda sad that there's no auto-update. :(

**Comment by jdalton** [comment]
> So it's kinda sad that there's no auto-update. :(

Got a solution? All in all I really like our branch/tagging approach.

**Comment by StreetStrider** [comment]
@d10 is right. According to semver, any postfix after triad major-minor-path means pre-release: [pre-release tags](https://github.com/npm/node-semver#prerelease-tags). bower is using this very package.

**Comment by jdalton** [comment]
Yap, I'm aware of the semver rules but I don't want separate repos because that would quickly get out of hand for (modern, modern-amd, modern-es, modern-npm, modern-npm-packages, compat, compat-amd, compat-npm). The tags/branches allows for separation, organization, & it sorts well in github. Version range support would be nice but I'm not bumming to hard over it as long as there's a way to get the package for bower/component/volo/yada.
