### ISSUE TITLE
Is this the expected behavior?

### ISSUE THREAD

**Issue by bbohling** [lodash/lodash#1134]
This works:

```
var collections = { foo: 'bar' };
_.each(collections, function (def, identity) {
    console.log('def: ', def);
    console.log('id: ', identity);
})
```

This does not (get lodash wrapper):

```
var collections = { foo: 'bar' };
_(collections).each(function (def, identity) {
    console.log('def: ', def);
    console.log('id: ', identity);
})
```

But this does:

```
var collections = { foo: 'bar' };
_(collections).each(function (def, identity) {
    console.log('def: ', def);
    console.log('id: ', identity);
}).commit()
```

And if `commit()` is required did that change at some point and I just missed it? Thanks!

**Comment by jdalton** [comment]
Yes this expected behavior. In v3 chaining is deferred until an implicit or explicit `.value()` is requested. In this case `.each` returns `collection` which means that when chaining it returns another wrapper to potentially continue the chain. Because this has become a bit of a tricky spot in v4 we may change to making `.each` non-chainable. I'll add it to the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap).
