### ISSUE TITLE
deep path support for zipObject

### ISSUE THREAD

**Issue by jasonkarns** [lodash/lodash#1151]
The deep path support in 3.7.0 is exciting! After updating, my first use case was for zipping an array into an object, where some of the property names use bracket/subscript notation. (More specifically, my use case is a quick one-liner to parse a query string into an object.)

```js
_([
  [ "a[b]", 1 ],
  [ "a.c", 2 ]
]).object().value() //=>  { a: { b:1, c:2 } }
```
There are a couple of questions as to how this would be handled for `zipObject`.

Clearly when zipping objects, the deep path parsing would need to be optional. But we also have a number of different sub-features:

1. handling subscript notation with string key: `"a[b]"`
2. handling dot notation: `"a.b"`
3. handling empty subscript (to result in an array property): `"b[]"`
4. handling explicit numerical subscript: (result in array? or object? object with string keys or numbers?): `"b[0]"`

And there's the interplay with `_.pairs` to think about, as well.

**Comment by jdalton** [comment]
Sub-features 2 & 4 are handled by `_.set`. Sub feature 1 is kind of handled if you do `a['b']` but not `a[b]` because that's like a prop name by variable (I don't want to handle it). Sub feature 3 isn't handled at all, it's treated as a normal property name because it's an invalid path.

With all the features combined it starts to feel a little too magic. If you can point to an existing implementation that would help but this seems a bit heavier than the other deep path sugar we have.

**Comment by jasonkarns** [comment]
Actually, I believe num. 1,2, and 4 are already handled by _.set:

`_([ ["a[b]", 1] ]).object().transform(_.rearg(_.set, 0, 2, 1)).value()` => ` { a: { b: 1 ] }`

(Code above is taken from a snippet I'm actually using.)

**Comment by jdalton** [comment]
> Actually, I believe num. 1

Ah ya, num 1 is currently a side effect, I guess I should add tests for it or nix it : P

**Comment by jdalton** [comment]
After thinking it over I don't think sub-feature 3 would apply as you would either assign an empty array as a value or reference an index to assign to. So with that a deep form of `zipObject` would basically be using `set` internally instead of basic property assignment. I'm open to  pull request.
