### ISSUE TITLE
_.flattenObject

### ISSUE THREAD

**Issue by bcherny** [lodash/lodash#1180]
```coffee
recurse = (v, k) -> if _.isObject(v) then collapse(v) else [[k, v]]
collapse = (json) -> _.flatten(_.map(json, recurse))
flattenObject = _.zipObject collapse

// or,
flattenObject = (object, accumulator = {}) ->

    _.mapValues object, (value, key) ->

      if _.isPlainObject value
      then _.flattenObject value, accumulator
      else accumulator[key] = value

    accumulator

flattenObject { a: { b: 1 }, c: 2 }
# => { b: 1, c: 2 }
```

**Comment by jdalton** [comment]
Hi @bcherny! There's a couple of ways to handle this. Another way is to flatten it down to a property named `a.b` similar to [flat](https://www.npmjs.com/package/flat#flatten-original-options). Because it's a bit loosely defined I'm going to punt this to packages like [flat](https://www.npmjs.com/package/flat#flatten-original-options) for now.

**Comment by DylanPiercey** [comment]
+1

**Comment by eligiblekeng** [comment]
+1, it'd be the `_.flatten` for objects, which may look like the product of `_.zipObject`
