### ISSUE TITLE
_.debounce/_.throttle return values

### ISSUE THREAD

**Issue by davis** [lodash/lodash#1201]
is there a way for me to get access to debounced/throttled functions' return values?

for example:

```javascript
function returnsFive () {
  return 5;
}

let debouncedReturnsFive = _.debounce(returnsFive, 500);

let shouldBeFive = debouncedReturnsFive();
console.log(shouldBeFive)
// => 5
```

**Comment by jdalton** [comment]
debounced functions will return the last value that `func` returns.

**Comment by davis** [comment]
for example, i am trying to debounce the following:
```
function theTime () {
  return Date.now(); 
}

let debounced = _.debounce(theTime, 500);

let time = debounced();
console.log(time)
// => undefined
// but the last value returned by func should be the time...

**Comment by jdalton** [comment]
By default the debounced function isn't invoked until the trailing edge of the timeout. You can configure this with an options object.
```js
_.debounce(theTime, 500, { 'leading': true })
```

**Comment by davis** [comment]
I do want the function to only be invoked at the trailing edge of the timeout, but I want access to the return value once it is eventually invoked. Is this possible?

**Comment by jridgewell** [comment]
>  I want access to the return value once it is eventually invoked. Is this possible?

Not on the first invocation. The function created by debounce has to return something, and you're value won't be available until after it's returned `undefined`.

**Comment by davis** [comment]
Ah - understood. Thanks!

**Comment by ChristianDavis** [comment]
This still seems like a bug for the case of 
this.debouncedPromiseFunction = _.debounce(PromiseFunction, delay0, { 'trailing:true', 'leading:false'})

The first call will throw:
Uncaught TypeError: Cannot read property 'then' of undefined 

Because .debounce doesn't return a promise, even though PromiseFunction is a promise. 

But subsequent calls work as expected. If the returned debounceFunction was a promise when Function is a promise returning function, this could be avoided
