### ISSUE TITLE
Lodash google-closure externs

### ISSUE THREAD

**Issue by Misiur** [lodash/lodash#1283]
Sorry if this is not a valid place for such question. Anyway, [underscore.js](https://github.com/lukeasrodgers/underscore-js-externs) has google-closure externs, however google search for externs for lodash is fruitless. Is there any side-repository for lodash externs already created, or are there any plans to create one?

**Comment by jdalton** [comment]
Those Underscore extern versions look pretty old. Lodash's build does a multi pass approach minifying with closure-compiler (cc) simple, cc advanced, ulgify, cc simple + uglify, cc advanced + uglify and picks the smallest one. The built auto escapes properties and handles some of the overly aggressive cc advanced mode removals. Because of this I would avoid cc advanced mode when not handled by the build.
