### ISSUE TITLE
Invalidate cached result of before functions

### ISSUE THREAD

**Issue by cornerman** [lodash/lodash#1328]
When I use ```_.once``` for caching expensive function calls, I would like the possibility to invalidate the cached result at some point. Would this be possible with lodash? When looking into the source code, I did not see any possibility to reset the value of ```n``` in ```function before```.

A trivial workaround would be to replace the existing function with a new ```_.once``` function.

**Comment by jdalton** [comment]
The primary purpose of the method is to restrict the function. I think invalidating the cache is a bit outside the scope of it. You can always add a mixin for this though.

**Comment by dietergeerts** [comment]
I was looking for this today and may have found a 'workaround': You can use a combination of `once` and `bindKey`, so that you can actually replace the function with a new `once` function whenever you want, without the thing that uses it needing to know. Of course, this means that you store that function and you'll have to make sure it can be garbage collected when needed, but that would not be a problem, as you would need the reference if you later want to invalidate it.
