### ISSUE TITLE
lodash-fp: issues with assign, result, zipObject

### ISSUE THREAD

**Issue by jakubholynet** [lodash/lodash#1343]
Hello, first of all let me thank you for lodash, it is a great library and I cannot imaging programming without it. 

I have started experimenting with lodash-fp and it looks pretty good but I run into some issues. I don't know how much it is due to my lack of knowledge (and sadly documentation) and how much these actually are limitations / defects in lodash-fp. 

The problems I've discovered so far:

1. `_.assign({}, {a:1}, {b:2});` returns `{a:1}` instead if `{a:1,b:2}` (the wrongly placed {} should have no effect)
2. No way to provide a default value to `result`?
3. zipObject(["key1", "value1", ...]) does not work
4. Functions on objects don't get the key parameter - find, map, mapValues, ...

Please see the [demonstration of the problems and more context here](https://github.com/jakubholynet/lodash-fp_issues/blob/master/lodash-fp_issues.ipynb).

Thank you!

**Comment by jdalton** [comment]
For future reference lodash-fp has its own [repo and issue tracker](https://github.com/lodash/lodash-fp/issues).

Having auto-curried iteratee-first data-last methods comes with some restrictions. This means functions do not accept a variable number of arguments. So methods that do are split out. For example there's `_.uniq` and `_.uniqBy`. We limit the number of arguments provided to `_.map` and such because it's easier for devs writing in that style to compose methods. Most don't want the `index`, and `object` params messing up their composition.

```js
_.map(parseInt)(['6', '08', '10']);
// → [6, 8, 10]
```

If you're wanting to provide the default value for `_.result` that would be a feature request on lodash-fp.

**Comment by jakubholynet** [comment]
Thank you for the quick response and sorry for reporting to the wrong repo!

You explanation makes sense, I will try to find time to make a PR with improved docs for lodash-fp to make this clear also to other users.

I still believe that the behavior of assign is strange but I can open a bug for that on lodash-fp.

Thank you!
