### ISSUE TITLE
Cannot pull lodash via bower

### ISSUE THREAD

**Issue by BoykoAlex** [lodash/lodash#1353]
I have the follwoing line in my bower.json:
    "lodash": "2.4.2",

for which i get the error: Fatal error: Unable to find suitable version for lodash

If I change the version to "3.0.0" or "3.10.1" or "latest" it still throws the same error.

It used to work with lodash 2.4.2 about a month ago... not sure what happened now. Can you advise how to get around this problem?

**Comment by jdalton** [comment]
Nothing changed on our end. I tried:
```bash
bower i lodash#2.4.2
```
and it works for me.

**Comment by inexuscore** [comment]
I'm currently using lodash v4.17.4. When I try to install the latest version or a specific version like #4.17.11 bower throws an error. ECONFLICT cannot find a suitable version for lodash. any ideas?

**Comment by jdalton** [comment]
Hi @inexuscore!

I'm not sure. We have the released tagged like all the others.

**Comment by inexuscore** [comment]
Hi @jdalton 
Ah, no problem. I tried changing the resolution but it didn't work.
It's probably because of another library, which is targeting an older version.
I'm thinking it's the **angular-google-maps** library that I'm using.

No worries though, it's a low-level warning, I can live with that. Thanks anyways!
