### ISSUE TITLE
Thank You!!! :)

### ISSUE THREAD

**Issue by phegade** [lodash/lodash#1414]
Hay, sorry for saying thank you as an issue ;)
You really saved me many times...A big thank you for lodash !!!

**Comment by jdalton** [comment]
Thanks @phegade!

I was going to mark the issue as `invalid` since we didn't have a label to express it but that didn't seem right. So I created the *heart* label for issues like this.

It's easy to get lost in the day to day operation of a project, getting bogged down with todos and issues. Encouragement like yours helps keep me and other core going. Thank you!

**Comment by Romanx** [comment]
:+1: I concur, i follow the repo to keep up with issues and see some crazy optimal javascript i could only wish to be able to write easily. Thank for a library that saves me re-creating the wheel every time

**Comment by crazy4groovy** [comment]
:heart: :heavy_multiplication_x: `infinity`

**Comment by oriSomething** [comment]
_.times(Infinity, () => :heart:)

:P
