### ISSUE TITLE
Trivial shortcut fusion not working?

### ISSUE THREAD

**Issue by pkt-zer0** [lodash/lodash#1434]
I think I might be doing something wrong, because even the following, basic example fails to use shortcut fusion, and calls the filter ten thousand times (instead of just seven).

	var arr = _.range(10000);
	var filter = function(item) {
		console.log('filtering');
		return true;
	};
	_(arr).filter(filter).drop(2).take(5).value();

However, I don't really see anything in the documentation for this, and intuitively it seems it should work. Is this possibly a bug?

**Comment by jdalton** [comment]
The issue is your `drop` after a `filter`. The `filter` means there's no way to know the end bounds of the `filter` until it is completed to perform the `drop`. If you remove the `drop` notice shortcut fusion kicks in.

**Comment by PhiLhoSoft** [comment]
I think you have missed the point of shortcut fusion.
From the current doc: "_Shortcut fusion is an optimization strategy which merge iteratee calls; this can help to avoid the creation of intermediate data structures and greatly reduce the number of iteratee executions._"
You were perhaps confused by the last part of the sentence.

Let see what we have without shortcut fusion: we take the array, filter it, producing an intermediate array. Then we apply drop, producing a new array as result. Then take is applied, producing yet another array. All these arrays will probably coexist in memory, until garbage collection kicks in.

The point of shortcut fusion is, by my understanding, to create a unique function processing in a pipeline each value. Thus, only one array is created, the final result.
This is the memory optimization.
And the number of iteratee calls is reduced too, because instead of doing 1000 * 3 function calls, it does only 1000 function calls, on the fused function.

While I typed this answer (based on guess game rather than on extensive study of code), I see @jdalton answered too, with a slightly different interpretation... So if I am wrong, I would be glad to be corrected. :smile: 

BTW, does this shortcut fusion uses the same techniques than tranducers, explained in http://stackoverflow.com/a/26856288/15459 answer?

**Comment by jdalton** [comment]
@PhiLhoSoft Naw @pkt-zer0  is right on.

I confused `drop` with `dropRight`. When we first introduced shortcut fusion `drop` would work in a lazy sequence when combined with `filter` because we had a more complex path to perform a `dropWhile()` under the hood. This ended up being too much code for 1 method scenario so it was cut to simplify things.

**Comment by pkt-zer0** [comment]
Hmm, okay. Maybe this limitation should be documented somewhere to avoid surprising people with sudden performance spikes in slightly differently formulated expressions. Here's an alternative formulation that does work more-or-less as expected:

	_(arr).filter(filter).take(5+2).drop(2).value();

**Comment by PhiLhoSoft** [comment]
I don't get it.
I tried in Plunkr, even if I drop `drop()` (sic), I still get n lines of log, where n is the number of items in the array. Same with drop() after take(), as @pkt-zer0 shows. I don't see an improvement.
Which is consistent with my guess: I don't see how take() can predict the items filter() will deliver to limit the number of iterations. You still have to run filter() on each item to know if it will be filtered out.

But then again, I am not a functional programming guru by a long run, so I probably miss smart optimizations... :smile: 

What I am missing?

**Comment by jdalton** [comment]
@PhiLhoSoft shortcut fusion kicks in after a length of 200. The whole point is devs continue coding as they do and as a bonus optimizations are applied when applicable.

**Comment by PhiLhoSoft** [comment]
Aaah, I see. Indeed, if I put a value of 200 or 500, I get the same number of lines in the console: 14.
Thanks for your patience, I got a better understanding of Lodash.
