### ISSUE TITLE
Support new function bind syntax

### ISSUE THREAD

**Issue by donaldpipowitch** [lodash/lodash#1435]
Hi,

it would be great if Lodash would support the new bind syntax. This allows for ad-hoc enhancements of existing objects without the need to modify the prototypes or wrapping them in some Lodash code.

Take a look at this [example](http://blog.jeremyfairbank.com/javascript/javascript-es7-function-bind-syntax/):

````
let { map, filter } = Array.prototype;
let todoItems = document.querySelectorAll('ul.my-list > li');
 
let completedItems = todoItems::filter(item => item.dataset.completed);
let titles = todoItems::map(item => item.textContent);
````

It would be nice if I could use Lodash in the same way. Use native methods where possible and add Lodashs methods if needed:

````
let { chunk } = _.prototype;
[ 1, 2, 3, 4].map(i => i * i)::chunk(2);
````

This currently throws:
````
/node_modules/lodash/index.js:1266
          length = source.length;
                         ^
TypeError: Cannot read property 'length' of undefined
````

**Comment by jdalton** [comment]
Hi @donaldpipowitch! I've looked at this a bit and I don't think the experimental bind syntax is a good fit for lodash because our data is not produced from the `this` but as the first param. It might work from our chaining wrapper already but that would be unintentional.

**Comment by donaldpipowitch** [comment]
> our data is not produced from the this but as the first param

This is true for `_.chunk`, but not `_.prototype.chunk` or am I wrong?

**Comment by jdalton** [comment]
> This is true for `_.chunk`, but not `_.prototype.chunk` or am I wrong?

You're correct. Our chaining syntax, while a closer fit, relies on chaining on certain chaining methods to exist too. Its an awkward fit. I could see getting support via a wrapper of some kind but that means more upfront work. 

Since this is all experimental syntax it could be solved by proposing a bind operator that works with our generic pattern. The `this` is the first argument.

**Comment by donaldpipowitch** [comment]
Whatever the solution will be I think it will be good for the whole web platform, if we could do something like `[ 1, 2, 3, 4].map(i => i * i)::chunk(2);`. It's a little bit like a “save“ forward-looking polyfill. Save because it doesn't change the behaviour of existing objects

**Comment by dantman** [comment]
> Since this is all experimental syntax it could be solved by proposing a bind operator that works with our generic pattern with the this as the first argument.

The proposal has settled down and judging by zenparsing/es-function-bind#19 it's unlikely that the proposal will ever include an alternative syntax that binds to the first-argument instead of `this`. Doing so would likely make it impossible to convince the TC39 committee to standardize it.

lodash supports a wide variety of custom builds and does a bunch of processing on the code, including breaking it up into modules, in multiple formats including es6 modules; shouldn't it be possible in some way to create a build mode that exports functions that use `this` in place of the first arg?

Then we'd have `lodash-bind` and `lodash-es-bind` packages to use.

The effect of doing that would be really, really advantageous.
```js
import { chunk } from 'lodash-es-bind';
[1, 2, 3, 4]
  .map(i => i * i)
  ::chunk(2)
  .forEach(([a, b]) => {
    // ...
  });
```

In this (naturally poor hypothetical but useful nonetheless) example, if you used rollup and babel, once rollup/rollup#45 is fixed, rollup would end up tree-shaking every part of lodash not used to make `chunk` work resulting in a very small bundle size.

The key points here are:
* You get a small build only including what you require
* The import is a one-liner: if you wanted more than `chunk` you would not need a separate `import`
* You get the advantages of chaining: Even though `_(...)` is not used; as a bonus you also get to chain off of native methods without ugly wrapping

Every alternative compromises that in some way.
* You can chain nicely using a one-line import using `_(...)` but tree-shaking becomes practically impossible
* You can get small bundles with `lodash/foo` imports, but even if you wrapped them so you could using es-function-bind you'd have a pile of ugly imports at the top
* You *could* tree shake a one line `lodash-es` import with rollup but you don't get to chain it

**Comment by jdalton** [comment]
That's a lot of what-ifs and not a lot of substance at the moment. If things move a bit further along then I'll take another look but as it stands it's a massive waste of my time.

**Comment by jdalton** [comment]
I mean totally complete nothing worse than waste of time.
