### ISSUE TITLE
Feature request: repeat arrays.

### ISSUE THREAD

**Issue by AlexFrazer** [lodash/lodash#1436]
Syntax in python will allow something like as follows:

```
>>> [1,2,3] * 4
[1,2,3,1,2,3,1,2,3,1,2,3]
```

Would this be something good for Lodash?

**Comment by jdalton** [comment]
Maybe. I use a non-methodized form of this in our unit tests with `_.times`. While `_.times` is not as streamlined it can accomplish what you want.

I'll keep an eye on this to see if there's enough demand to warrant addition to core.

**Comment by mk-pmb** [comment]
I was surprised to learn that lodash cannot yet repeat arrays. If `.times` can shim it, docs for `.repeat` should mention it, and should pre-emptively explain why not arrays.

I had to split out the relevant code in order to [fix it](https://github.com/mk-pmb/lodash-repeat-arrays-fix1436-pmb-js/commits/master) because I can't easily work on files that huge.

As I've gone each step (add array support, add buffer support) in an extra commit you can easily see the impact on assumed cost of operations:
* Using `.concat` to append strings or arrays costs that dot lookup + invocation in each step, and
* supporting the Buffer helper function costs an extra function call in each step. We could however save the `.concat` lookup if we made a special add function for the string case.

Hope it helps, and remember to add the docs spoiler! :-)

**Comment by jdalton** [comment]
Hi @mk-pmb!

> If .times can shim it, docs for .repeat should mention it, and should pre-emptively explain why not arrays.

The docs have [_.repeat](https://lodash.com/docs#repeat) under the "Strings" category with documentation examples with strings. I'm not willing to go further than that in explaining the method as it would contribute to doc clutter.

**Comment by mk-pmb** [comment]
> The docs have _.repeat under the "Strings" category

Oh ok, I missed that part because I followed the docs link from the lodash.repeat npm package. At least it's just a few clicks from "what, lodash can't do it?" to this feature request thread. :-)

**Comment by jdalton** [comment]
I'll look into scrolling the toc entry into view as well when navigating to specific methods.

**Comment by mk-pmb** [comment]
Wouldn't have helped in my case, but good idea anyways. (1. I hadn't granted JS execution for just reading docs, 2. I hadn't even looked at the toc because I felt entitled to expect based on the function name that of course it's not limited to just one data type.)

**Comment by jdalton** [comment]
You should really enable JS on a JS library site. You're missing out on things like, doc repls, offline support, and enhanced search.

**Comment by homerjam** [comment]
> Maybe. I use a non-methodized form of this in our unit tests with _.times.

@jdalton would you mind sharing how you're doing this in the unit tests (I can't seem to find them)?

**Comment by jdalton** [comment]
@homerjam Unit tests can be found [here](https://github.com/lodash/lodash/tree/4.17.5).

**Comment by homerjam** [comment]
Great thanks.

To anyone interested I've ended up doing this:

```js
const arrayToRepeat = [1, 2, 3];
const numberOfRepeats = 3;
const repeatedArray = _.flatten(_.times(numberOfRepeats, _.constant(arrayToRepeat)));
```

**Comment by RodrigoRoaRodriguez** [comment]
In case anyone else ends up here looking for an answer on how to do this;  I have a more concise solution:
```js
_.range(numberOfRepetitions).flatMap(() => arrayToRepeat)
```
So that:
```
_.range(2).flatMap(() => [1,2,3]) // returns [1,2,3,1,2,3]
```
