### ISSUE TITLE
Early exit in select or reduce?

### ISSUE THREAD

**Issue by mrozbarry** [lodash/lodash#1444]
I'm currently working with a large array with I want to select from, but if the array has a certain value at a single element, I want to exit early and not select on the rest of the array.  I noticed no documentation on this.

Althought I can do some tracking with an outer scope variable:

```javascript
earlyExit = false
selected = _.select(myCollection, function(collectionItem, index) {
  return false if earlyExit
  if (collectionItem == earlyExitCondition) {
    earlyExit = true;
    return false;
  }
  return (collectionItem == myCondition)
});
```

I find this not much better than:

```javascript
selected = []
for(collectionItem in myCollection) {
  if (collectionItem == earlyExitCondition) break;
  if (collectionItem == myCondition) selected.push(collectionItem);
}
```

Obviously, I can't use break, since the internal for loop is out of scope.  I don't mind using plain old JS, but I find it breaks the pattern I'm using with lodash functions.

Any ideas?

**Comment by jdalton** [comment]
You can use [_.transform](https://lodash.com/docs#transform).

**Comment by nathanmarks** [comment]
@jdalton Given this example, I can't return false using `transform` -- it always returns true because of how the accumulator + iteration function work with `transform`:

```js
return transform(conditions, (res, val, key) => {
  if (get(payload, key) !== val) {
    return false;
  }
  return res;
}, true);
```

Setting `res = false` doesn't work as I'm replacing the reference rather than mutating the accumulator.

But if I use `reduce`, it allows me to return a boolean, but also forces me to continue running through every iteration as I can't exit early:

```
return reduce(conditions, (res, val, key) => {
  if (res && get(payload, key) !== val) {
    return false;
  }
  return res;
}, true);
```

Is there a trick I'm missing to achieve the intended functionality (without using a native for loop)?

**Comment by jdalton** [comment]
@nathanmarks
> Setting `res = false` doesn't work as I'm replacing the reference rather than mutating the accumulator.

`_.transform` is intended for object/array accumulation not primitives.

> Is there a trick I'm missing to achieve the intended functionality (without using a native for loop)?

You can use `_.each` and exit early and track values with variables but that's only a matter of taste better than a for-loop.

**Comment by nathanmarks** [comment]
@jdalton 

Thanks, I'll just stick with one of those then if the iterations are a concern.
