### ISSUE TITLE
_.sum(object) doesn't seem to work

### ISSUE THREAD

**Issue by phaniram** [lodash/lodash#1506]
Simple example `_.sum({ 'a': 4, 'b': 6 })` produces `0`

[jsfiddle](http://jsfiddle.net/pLbyvs1u/)

**Comment by jdalton** [comment]
That's because it's loading lodash from the master branch and `_.sum` works only on arrays there as part of a v4.0 change.

FWIW I think jsfiddle is a horrible tool for sharing repos because it looks the source away in iframe after iframe. When I loaded the jsfiddle it said lodash v2.1.0 was loaded but after digging through the result view and inspecting its embedded iframe it shows that 
> 
```html
<script type='text/javascript' src='//cdn.jsdelivr.net/lodash/2.1.0/lodash.compat.js'></script> 
<link rel="stylesheet" type="text/css" href="/css/result-light.css">
<script type='text/javascript' src="https://cdn.rawgit.com/lodash/lodash/master/lodash.min.js"></script>
```

**Comment by phaniram** [comment]
I actually loaded it from external source
https://cdn.rawgit.com/lodash/lodash/master/lodash.min.js

and when I actually view it in browser, I see this,
/**
 * @license
 * lodash 3.10.1 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash -p -o ./lodash.min.js`
 */

Not sure why it doesn't say v4.0 if it's a v4.0

**Comment by jdalton** [comment]
> I actually loaded it from external source

Right, jsfiddle doesn't make that obvious.

> Not sure why it doesn't say v4.0 if it's a v4.0

The master branch is our edge branch, so it's a work in progress and not published. You should not use the master branch for anything really unless you're wanting to test it out.

If you visit the [site](https://lodash.com/) you'll see we link to the tagged v3.10.1 release.
