### ISSUE TITLE
Rename `_.restParam` to `_.rest`?

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#1526]
I figured I'd bring up renaming `_.restParam` to `_.rest` in v4.0.
This would mean the existing `_.rest` would be renamed `_.tail` and I'd either drop `_.first` for `_.head` or make it an alias of `_.head`.

Thoughts?

**Comment by jasonkarns** [comment]
I was initially fully in support of _rest until reading that there is already _rest. So instead, might I suggest an alternative. Rest params are called splats in ruby. Perhaps _splat

**Comment by jdalton** [comment]
That may be the answer. Curious do you have info on the history of the name "splat"?
`_.spead` and `_.splat` have a nice ring to it.

**Comment by jasonkarns** [comment]
I don't have any offhand knowledge on the origins of either the operator (`*`) nor the name `splat`. However, Ruby takes a lot of inspiration from Perl so maybe there? (I don't know if Perl has a splat-like operator)

> _.spread and _.splat have a nice ring to it

I would be remiss if I didn't point out that there would be a bit of a disconnect between ruby's naming and lodash, in this case. In Ruby, the splat operator has both the same symbol (`*`) and the same name (splat) when used in each direction. JS, of course, uses the same operator (`...`) but names it differently based on the mode/direction (`rest` vs `spread`). So while `splat` does fit, anyone with a ruby background might find pairing `splat` with the name `spread` a bit odd. But that's a minor nit.

In any case, it's a bit of a conundrum. A ruby person might expect to be able to use `splat` in place of `spread`.

But the name `rest` doesn't quickly make clear whether it's rest-as-with-spread or rest-as-in-tail.

`head`/`tail` work well (as would `car`/`cdr` for a Lisper), and using the ES6 terminology for `rest`/`spread` has a lot of merit.

I think I've just talked my way back to opposing my own suggestion. Despite the influence of other langs, maintaining consistency within JS is probably the best route.

I vote for 
`_.rest`/`_.spread`;  `_.head`/`_.tail`

And options for `tail`:  `_.remainder`, `_.remaining`, `_.left` (though I think `head`/`tail` is the best. If you keep `_.first` as an alias for `_.head`, I'd expect `_.last` to exist; but not as a `_.tail` alias, of course)

**Comment by jdalton** [comment]
Thanks!

**Comment by jdalton** [comment]
Interesting notes on `first`, `rest`, `tail` and friends https://en.wikipedia.org/wiki/CAR_and_CDR

**Comment by StreetStrider** [comment]
I personally alias as head-tail:
```js
var head = require('first')
var tail = require('rest')
```
I also like one-word, short names very much, I found them magical. The optimal name length is about 4. English has many cool 4-letter words, so `head`-`tail` and renaming `restParam` to `rest` is a 100% win in my opinion.

**Comment by megawac** [comment]
I'm fine with it as long as the renames stay within the documentation (not just the changelog)

Something along the lines of

> `**_.head**`                previously known as `_.rest`, `_.first`

**Comment by NicBright** [comment]
Hi there,

I would like to suggest some different point of views:

### Concerning _.rest() / _.tail()
I agree that `_.rest()` as it exists in v3 can just be removed. But I don't understand why `_.tail()` which (in v3) aliases `_.rest()` should stay at all in the current form. Because:

1. _.rest(array) === _.tail(array) **=== _.drop(array, 1) === _.drop(array)**
2. I personally dislike the different semantics of **tail** when comparing lodash to unix:

Consider this bash exmaple:
```bash
cat anyFile | tail -n 20
```
The bad thing is, that the same thing would work in lodash, but with totally different results. To do the same thing in lodash v3 one needs to use `_.takeRight()`. In lodash v2 it was `_.last()` which no longer accepts an ***n*** parameter in v3.

From this point of view, I think the API should change like this:
- remove `_.rest()` and `_.tail()` like they exist in v3
- add `_.tail()` to alias `_.takeRight()`


### Concerning _.first() / _.last()
When looking at lodash from a jQuery point of view, it makes a lot of sense to stick with `_.first()` and `_.last()` as they are (now in v3).

### Concerning _.head()
Again when looking from a unix point of view:
```bash
cat anyFile | head -n 10
```
Since lodash v3 this is no longer possible. Back in v2 this would have worked just fine as `_.head()` was an alias of `_.first()` which accepted an n parameter back then. The bad thing again is the different semantics (`_.head()` is no longer accepting an n parameter) which leaves a person coming from a unix domain thinking that one could write `_(collection).head(10)` which executes just fine but leaves you only with the first item.

From this point of view, I think the API should change like this:
- make `_.head()` be an alias of `_.take()` instead of an alias of `_.first()` (as it is right now)

### Conclusion
Both, `_.head()` and `_.tail()` should either be removed as a whole. Or they should (imho) be changed to make them work analoguous to the versions of the unix domain.

Regards,
Nicolas

**Comment by jdalton** [comment]
Thanks @NicBright! I've already sorted it out.
