### ISSUE TITLE
Enhancement: Rename _.trunc to something that doesn't clash with Math.trunc

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash#1568]
I know this would be a breaking change but it would particularly nice if _.trunc could be renamed to something less confusing/clashing with Math, namely Math.trunc. Possible alternatives could be _.shorten, _.curtail, _.lessen, _.abridge or  _.abbreviate

**Comment by jdalton** [comment]
I have been thinking this might come up ever since I learned of the ES6 methods. I based `_.trunc` on mout (truncate), underscore.string (truncate), Ruby (truncate), MooTools (truncate). It seems everyone is calling it `truncate`. I think for v4 we can rename it but I want to hold off adding a `_.trunc` method until after 4.0 is out the door to reduce the wtf of switching. I'll accept a pull request to rename `_.trunc` to `_.truncate`.

**Comment by Xotic750** [comment]
I think I can manage that. ;)

**Comment by jdalton** [comment]
Moved to #1569.
