### ISSUE TITLE
.get nested object with dot in key

### ISSUE THREAD

**Issue by azhang** [lodash/lodash#1637]
```
## works
> get({ 'some.field': 123 }, 'some.field') 
123

## works
> get({some: {field: 123}}, 'some.field');
123

## This is the one I'm trying to use and doesn't work
> get({some: {'nested.field': 123}}, 'some.nested.field');
undefined

## This doesn't work either
> get({'some.nested': {field: 123}}, 'some.nested.field');
undefined
```

**Comment by jdalton** [comment]
You can use an array for the path:
```js
_.get({some: {'nested.field': 123}}, ['some', 'nested.field']);
// => 123
```

**Comment by azhang** [comment]
Thanks! That works for me.

**Comment by petermikitsh** [comment]
It would be convenient if the _.get function could intelligently parse a single string into the appropriate property names.

If I say,

```js
_.get({some: {'nested.field': 123}}, ['some.nested.field']);
```

Lodash could attempt:

```
_.get({some: {'nested.field': 123}}, ['some', 'nested.field']);
```

if some.nested.field is undefined.

In my use case, I have to store the property path in a database for use at runtime as a string, not as a string array.

**Comment by IvanKarpan** [comment]
Here's what worked for me:
```
.get({some: {'nested.field': 123}}, 'some["nested.field"]')
// => 123
```

**Comment by newasmod** [comment]
@jdalton  please help me! i need to set value to property with dots in key, cant get it working

**Comment by jdalton** [comment]
@newasmod Check out our [gitter chat](https://gitter.im/lodash/lodash) for help.

**Comment by donpinkus** [comment]
It seemed nested property access doesn't work with `"lodash": "^4.17.5"`

```

**Comment by DesignByOnyx** [comment]
@donpinkus - I tested your example and it does indeed work. Something else must be going on on your end: https://codepen.io/anon/pen/MqRmpm?editors=1111

 @petermikitsh - I know it's been a while since you posted, but I implemented something like you suggested with recursively looking up keys combinations with dots, and you are talking about object lookups going from O(n) to O(N^2), which totally kills performance. I advise users to find an alternative solution as you did. Often times your code knows when a key might have dots in it, in which case you can pass an array of keys instead of a string.

**Comment by lucaslimafons** [comment]
> You can use an array for the path:
> 
> ```js
> _.get({some: {'nested.field': 123}}, ['some', 'nested.field']);
> // => 123
> ```

This solution worked for me! Thanks!!!

**Comment by spiewak** [comment]
@donpinkus I believe that your problem is not connected with `lodash`. You probably should setup `paths` property in [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

e.g.
```
new LodashModuleReplacementPlugin({
   paths: true
});

```

**Comment by usb248** [comment]
@spiewak you save my day
