### ISSUE TITLE
Update indexOf signature documentation

### ISSUE THREAD

**Issue by gajus** [lodash/lodash#1711]
First parameter does not need to be an array. It can be an instance of any itterable object.

This is causing some ambiguity, e.g. people think that `_.indexOf` cannot be used with a string (see https://github.com/wix/eslint-plugin-lodash3/issues/11#issuecomment-165751936).

**Comment by megawac** [comment]
In future versions of lodash (lodash^4), `indexOf` and all array methods will support array methods in all cases where index lookup `obj[x]` works (i.e. is array-like). However, in older environments (IE<=8) strings did not behave like this and `obj[x]` would produce undefined.

The current version of lodash addresses this issue, so yes it should be `[Array|string]`, however in future versions of lodash is should only be `[Array]` (IMO)

**Comment by gajus** [comment]
Turns out

```js
_.indexOf('abcd', 'bc')

> -1
```

https://github.com/wix/eslint-plugin-lodash3/issues/11#issuecomment-165760824

**Comment by jdalton** [comment]
@gajus I've chosen the categories of methods carefully to reduce their support burden. In v3 and less which have support for IE < 9 the "Collection" methods had code forks for strings because older browsers don't support index property access or iterate over strings correctly. However, the `_.indexOf` method is an "Array" method which means it avoids the string support case altogether. If you use a string with an "Array" method we aren't responsible for support.

**Comment by jdalton** [comment]
It looks like what you want is `_.contains('abcd', 'bc')`.

**Comment by megawac** [comment]
@jdalton 
> It looks like what you want is _.contains('abcd', 'bc').
isn't `_.includes(str, content)` preferred?

**Comment by jdalton** [comment]
Yep, yep.
