### ISSUE TITLE
Lodash/fp's merge signature is surprising

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#1754]
Ramda's `merge(a, b)` merges `b` onto `a`.
Lodash does the same.
Lodash/fp's `merge(a, b)` merges `a` onto `b`.

Is this intentional? I can see both arguments as to whether `a` or `b` should be considered the data argument -- it's just kind of surprising, since Lodash/fp's function signatures generally align with those of Ramda, but in this case it's actually Lodash that shares Ramda's signature. Might be worth documenting as a caveat for those migrating from Ramda, if intentional.

**Comment by jdalton** [comment]
Naw, I'll align.

**Comment by billyjanitsch** [comment]
Great, thanks!

Just noticed that `set` is also a bit surprising when compared with Ramda's `assoc`:
Lodash: (object, path, value)
Lodash/fp: (value, path, object)
Ramda: (path, value, object)

**Comment by jdalton** [comment]
Great! Keep them coming!

**Comment by jdalton** [comment]
\cc @jfmengels. Yay/Nay?

**Comment by jdalton** [comment]
\cc @jackfirth for opinions too.

**Comment by jackfirth** [comment]
Changing this would make for some really nasty backwards compatibility breaks. The new behavior wouldn't be different from the old behavior in a way where it immediately throws an exception upon use if you didn't update the call site, but instead produces subtly-wrong output in edge cases. There'd need to be a really strong reason to prefer a different order to justify the change.

**Comment by jdalton** [comment]
@jackfirth The `fp` additions were introduced in the v4.0 release (so this can be seen as a bug fix shortly after as adoption is slow on a major bump). At the moment I'm siding with what other FP libs do to meet developers where they're already familiar/comfortable.

**Comment by jackfirth** [comment]
@jdalton That makes more sense. Also I'm clearly not awake enough at the moment, because since this grew out of the Ramda gitter I didn't read very closely and assumed this was an issue in the Ramda repo, not lodash (doh). Backwards compatibility would be a much bigger issue with Ramda's merge since they've had it forever.

**Comment by jdalton** [comment]
\cc @davidchambers too

**Comment by davidchambers** [comment]
Properties of the second argument should trump those of the first argument, so one can `merge(defaults)` in a pipeline.

**Comment by jfmengels** [comment]
IMHO (as someone pretty new to FP), all functions should be data-last, and should incidentally be easy to use with `_.flow`/`_.compose`.

```js
_.flow(
  _.defaults({a: 2, b: 3}),
  ...
)(obj)
```

In the case of comparing it to Ramda, this is the example I see [in their docs](http://ramdajs.com/docs/#merge)
```js
R.merge({ 'name': 'fred', 'age': 10 }, { 'age': 40 });
//=> { 'name': 'fred', 'age': 40 }

var resetToDefault = R.merge(R.__, {x: 0});
resetToDefault({x: 5, y: 2}); //=> {x: 0, y: 2}
```
Ramda's merge function is curried, but even in their example, the practical application is by using partials because it is not data-last.
```js
// Ramda
var resetToDefault = R.merge(R._, {x: 0});
// A would-be more practical way to write, and data-last:
var resetToDefault = R.merge({x: 0});

// applications
resetToDefault(obj);
R.compose(
  ...,
  resetToDefault
  ...
)(obj);
```

In terms of consistency, all lodash/fp AFAIK aim to be data-last, so any function that does not do that seems out of the bunch. They all require to be wrapped by a _.partial call or a new function like `(obj) => _.merge(obj, {x: 0})` in order to be data-last.

So, yes, it does not look like Ramda, but it does not look like Lodash's other FP functions if they're not data-last, which is a bigger inconsistency IMO, especially because of the current lack in documentation about the order of the FP functions' argument order which forces you to poke and play with functions before being sure of what they do.

With regards to _.assign(), what I liked to do in v4.0.0 (it was a short-lived pleasure), was pretty much a multiple shallow _.set in one simple call, like this:
```js
const foldHandAtPoker = _.assign({cardsInHand: [], hasFolded: true})
// instead of
const foldHandAtPoker = _.flow(
  _.set('cardsInHand', []),
  _.set('hasFolded', true)
)
```

**Comment by jackfirth** [comment]
Ramda's merge *is* data-last if you consider the case of supplying defaults for absent values:

```javascript
var defaultCoords = R.merge({x: 0, y: 0});
defaultCoords({x: 10});
//=> {x: 10, y: 0}
```

This comes up a lot with functions accepting "configuration" objects affecting their behavior.

**Comment by jdalton** [comment]
If anyone wants to help with docs [our wikis](https://github.com/lodash/lodash/wiki/Build-Differences) allow editing.

**Comment by jfmengels** [comment]
@jackfirth indeed. And I guess that brings us back to what @billyjanitsch said:
> I can see both arguments as to whether a or b should be considered the data argument

In the case of Lodash, there is a `_.defaults` function, that I would probably use when setting default values. But then what bothers me is that the default values is in second place, and the actual data that will be given first.

**Comment by jdalton** [comment]
So is the consensus to revert to the initial v4.0 behavior of `(b,a)`?

**Comment by jdalton** [comment]
Or some mix of the two.

**Comment by jfmengels** [comment]
I vote on simply reverting to the initial v4.0 behavior.

**Comment by billyjanitsch** [comment]
IMO, in FP, `merge(a, b)` should merge `b` onto `a` and `defaults(a, b)` should merge `a` onto `b`. (4.0.1 behavior.)

The reasoning is that, in FP terms, the *data* of `defaults` *are* -- semantically -- the defaults (`b`) to be applied to the params (`a`). The data of `merge` are the object to be merged (`b`), with params `a`.

Thinking about them in the opposite order makes more sense when thinking in non-FP terms.

**Comment by billyjanitsch** [comment]
@jdalton 

> So is the consensus to revert to the initial v4.0 behavior

It seems like myself, @jackfirth, and @davidchambers are all in favor of the 4.0.1 behavior while only @jfmengels prefers the 4.0.0 behavior.

**Comment by jackfirth** [comment]
To me it seems strange to have both `merge` and `defaults`. With just `merge`, Ramda's behavior makes far more sense because most of the time you'll use it to set defaults on some object. I'm not sure what Lodash users use merge for most often.

**Comment by jdalton** [comment]
Lodash's `_.merge` performs a deep merging of two objects while `_.defaults` is flavor of `_.extend` that avoids overwriting non-`undefined` properties.

**Comment by jdalton** [comment]
@billyjanitsch 
> IMO, in FP, `merge(a, b)` should merge `b` onto `a` and `defaults(a, b)` should merge `a` onto `b`.

I can dig that. Thanks all for helping work this out.
