### ISSUE TITLE
How to upgrade 3.x to 4?

### ISSUE THREAD

**Issue by elado** [lodash/lodash#1773]
Looks like many functions, such as `_.where` and `_.findWhere`, are missing from 4.0.0, and there's no upgrading guide.

**Comment by DannyNemer** [comment]
The [changelog](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings) contains the following:
> Removed `_.where` in favor of `_.filter` with iteratee shorthand
> Removed `_.findWhere` in favor of `_.find` with iteratee shorthand

Also, give [`lodash-migrate`](https://www.npmjs.com/package/lodash-migrate) a spin to help migrate older Lodash code to the latest release.

**Comment by jdalton** [comment]
Yep. @elado let me know if you have further issues.

**Comment by ehartford** [comment]
is there any guide?  
It is not apparent how a lodash-migrate.js will help me to migrate my codebase.  It surely doesn't modify my source code for me?

**Comment by jdalton** [comment]
@ehartford You add it as a dev dep to your app and it will log out when it hits differences in APIs that you'll have to address.

**Comment by anterokarttunen** [comment]
Aww man.. these deprecations. For example qlik sense javascript is using underscore - I wanted to try with lodash 4 but _.findWhere was removed.

So do I have to:

1 revert back to underscore

2 use lodash v3 (is there going to be any support for that version?)

3 use lodash-migrate

**Comment by jfmengels** [comment]
@anterokarttunen `_.findWhere in favor of _.find with iteratee shorthand`. Can't you use `_.find`?

**Comment by jdalton** [comment]
@anterokarttunen 

The methods were removed because their functionality was already duplicated.
`_.findWhere` is just `_.find` + the `_.matches` iteratee shorthand `_.find(collection, { 'foo': bar })`.
The `lodash-migrate` package doesn't add compatibility it just logs the differences between v3 and v4 APIs.

**Comment by anterokarttunen** [comment]
I'll try to create alias. Can't fork qlik sense js code directly :D





On 31 Mar 2016, at 17:41, John-David Dalton <notifications@github.com<mailto:notifications@github.com>> wrote:


@anterokarttunen<https://github.com/anterokarttunen>

The methods were removed because their functionality was already duplicated.
_.findWhere is just _.find + the _.matches iteratee shorthand _.find(collection, { 'foo': bar }).
The lodash-migrate package doesn't add compatibility it just logs the differences between v3 and v4 APIs.
