### ISSUE TITLE
`window._` leaks out even when lodash is packaged with webpack/browserify

### ISSUE THREAD

**Issue by seansfkelley** [lodash/lodash#1798]
7862ae6d3625436ced505b3db507743e46c30432 unconditionally exports `window._`, which means that even when packaged up by e.g. webpack it unexpectedly clobbers any other lodashes that are on the page. I'm aware of `noConflict`, but what was the reason for this change away from regular UMD-style behavior in the first place?

**Comment by jdalton** [comment]
I can't find the specific issue but the gist is that various bundling and builds can insulate lodash from the global even if when it's not wanted. So just as with the AMD approach we export to the global because you can always cleanup with `noConflict` if needed.

**Comment by megawac** [comment]
This seems like a regression for folks trying to move to lodash 4 file by file

**Comment by seansfkelley** [comment]
FWIW, babel-plugin-lodash makes this a moot point, which is a nice side effect.

**Comment by jdalton** [comment]
> This seems like a regression for folks trying to move to lodash 4 file by file

Naw, folks had reported problems accessing lodash when bundled with other code. This solves it in a pretty painless way. If you're concerned with clobbering call `noConflict`. It worked for AMD folks for years ;)

**Comment by jdalton** [comment]
Basically if you're in the browser or a web worker lodash will export to the global to ensure access even if its trapped in a bundle and unable to be exposed via the bundler. It's a good thing.

**Comment by spazmodius** [comment]
I'm not clear how I can get all my third-party dependencies to call `_.noConflict()` whenever they import lodash.

**Comment by jdalton** [comment]
You would call `noConflict` in your initial use. Third party deps would use require lodash in whichever modular way they already do.

**Comment by aldendaniels** [comment]
FWIW, this issue caused me confusion today. I have a `lodash.js` file that adds some mixins to lodash:

```javascript
const _ = require('lodash').runInContext();
_.mixin({...});
module.exports = _;
```

I use this throughout my project. In one instance, however, I forgot to actually import my enhanced LoDash instance. Instead of blowing up, I instead got the un-enhanced lodash instance off the global scope.

**Comment by jdalton** [comment]
In the next bump, v4.14.0, Lodash will no longer auto global export.

**Comment by NekR** [comment]
@jdalton this doesn't seem to be solved since webpack has AMD support too so this line https://github.com/lodash/lodash/blob/59c7c3fca34c7f50baffc51633583081599cb2d8/dist/lodash.js#L17060 transforms into `true` and then this line happens: https://github.com/lodash/lodash/blob/59c7c3fca34c7f50baffc51633583081599cb2d8/dist/lodash.js#L17065

While there are couple of ways to solve it: 1) use `_.noConflict()`; 2) or use `imports-loader` http://stackoverflow.com/questions/29302742/is-there-a-way-to-disable-amdplugin; it would be good anyway if lodash had good webpack support and was checking for CommonJS modules signature first.

**Comment by homeslicesolutions** [comment]
I still have issues with this even in version v4.14.0 to the latest of v4.17.0.   Does anyone else have this issue? I am using it with Webpack.

**Comment by jdalton** [comment]
You're probably using an AMD loader and that's by design.

**Comment by NekR** [comment]
Not sure what you mean by AMD loader. AMD support is built-in in webpack and that happens with normal webpack configuration and lodash from npm.

I already described the problem in one of such issues (there are many in this repo about this same problem), not sure if I'll be able to find that message now though.

**Comment by jdalton** [comment]
It means that if we detect an AMD loader, like RequireJS, then we will export to the global since we're unable to know if Lodash will be required by the AMD loader or be loaded as a regular script.

**Comment by NekR** [comment]
@jdalton I think you can check for CommonJS first (as opposed to detect AMD first, then CommonJS) and if it's then don't do global export. This is what many-many other libs do and they are able to detect it.

**Comment by seansfkelley** [comment]
FWIW I'm still seeing this on 4.17.4 as well, using Webpack in non-AMD mode (not sure what you'd call it -- but it's all packaged into `monolith.js`).

I suspect this is a Webpack-specific issue; as I ran into it [on an issue in CometD to add Common JS support](https://github.com/cometd/cometd/issues/649#issuecomment-252059969):

> The only hiccup was in the ordering of the UMD header. Apparently, Webpack tries bundling mechanisms in the order they appear in the file and it rightfully complains about the AMD definition, since there's nothing called `org/cometd` anywhere in my CommonJS-based project.

**Comment by jdalton** [comment]
Our order is the way it is because of supporting other environments and was in place before Webpack was a thing. If webpack is having an issue you should report it there. I can tell you I'm not changing Lodash v4. It's last version has shipped so there is zero chance of this ever being addressed. And since there's no chance of this getting addressed the lock is coming down.

**Comment by jdalton** [comment]
Again. Srsly wtf folks.

**Comment by jdalton** [comment]
It turns out this issue is due to a Webpack transform [that's catered to end users and not libraries](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829), like Lodash, that have AMD support. For the time being, Webpack recommends [opting-out of their AMD parsing](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512) if you're running into issues.
