### ISSUE TITLE
Can't find _.pluck() in the documentation

### ISSUE THREAD

**Issue by HenryZouInterSystems** [lodash/lodash#1806]
https://lodash.com/docs#pluck doesn't exist even tho the functionality does.

**Comment by pgn-vole** [comment]
> Removed _.pluck in favor of _.map with iteratee shorthand

https://github.com/lodash/lodash/wiki/Changelog

**Comment by monokrome** [comment]
@jdalton I think that this is more of a documentation issue than an implementation issue. Would it make sense for the documentation to recognize `map` as an alias to `pluck` in the same way that *extend*, for instance, is a pointer to *assignIn*?

**Comment by jdalton** [comment]
The change was made to simplify the API. We had 17 aliases before which is a bit overboard. We should try to keep them to a minimum and name things appropriately to begin with.

**Comment by megawac** [comment]
@jdalton I mentioned this before but it may be nice to label methods changed/renamed in the documentation (ala python docs)

**Comment by jdalton** [comment]
Those interested in tackling that can dig in https://github.com/lodash/lodash.github.io/issues/8.

**Comment by thinkingmedia** [comment]
I vote to re-open this issue as I've read https://github.com/lodash/lodash.github.io/issues/8 and don't see how it applies.

The problem here is that `lodash` is generating `npm` warning to discontinue use of `3.x` and use `4.x` instead because `3.x` is discontinued, but this places pressure on developers to upgrade to suppress the warnings (sometimes generated multiple times).

After upgrading to `4.x` the builds fails with `_.pluck` is not a function.  That's kind of unfair because when you go to the documentation the keyword `pluck` can not be found.

I had to google, search issues and than link to another repo in order to discover that it had been removed (without deprecation) not in version `4.3.0` but in several versions before that `4.0.0`. You have to read release notes from that older version know what the fix for it is.

So I ask why! Why can't a quick edit of the Javascript file for map be done to add a note informing people of this work around. Instead I find this issue and it was closed and deferred to another topic about documentation improvements which isn't what the problem is about.

There has to be a large number of people experiencing this. I'm just saying that a quick fix to the docs should be fast tracked. I can do the pull request but I wanted to confirm it will get merged.
