### ISSUE TITLE
Question about matchesProperty change

### ISSUE THREAD

**Issue by PhiLhoSoft** [lodash/lodash#1901]
This is not really an issue, more a question on reasons behind a breaking change done in v4.
I don't ask for (and don't expect) a change for this...

Why did you change the matchesProperty style from two parameters to an array?

Convenience for you? (easier to code / to maintain / to test / whatever)
More performance?
Significant reduce in size of built package?
Consistency of API?

I find the new syntax heavy (more to type: `_.find(o, 'id', id)` vs. `_.find(o, [ 'id', id ])`), and disruptive (lot of places to change).
I mind less the drop of .value() call after a chained `forEach()`, for example, which is logical anyway.

Sorry if I sounds grumpy, the issue is really about understanding motivation. :smile: 
Could not find a forum, gitter or other more appropriate communication channel... :information_desk_person:

**Comment by jdalton** [comment]
The `matchesProperty` shorthand was changed to work with the removal of the `thisArg` param. There was no longer a hangling param to use as part of the shorthand. It also allowed the shorthand to be more effective. Before when it took 2 params you could not match a value of `undefined` because it would think the `thisArg` was undefined and not trigger the shorthand. Using the array avoids the issue and is comparable to a single value `matches` shorthand.

**Comment by PhiLhoSoft** [comment]
Good reasons (of course!).
Thanks for the quick answer.

**Comment by jridgewell** [comment]
Is there a reason this isn't just a special case for `_.matches` and the `{id: id}` shorthand?

**Comment by jdalton** [comment]
> Is there a reason this isn't just a special case for `_.matches` and the `{id: id}` shorthand (with a single property)?

We do that as well. Having both allows devs to specialize (custom bundles) if desired.

**Comment by PhiLhoSoft** [comment]
Good remark, @jridgewell!
I avoided this form in v3 because the two parameter form is simpler, and avoids an object creation (minor).
But here, it has the big advantage of working in both versions...
