### ISSUE TITLE
fp module path

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash#1909]
There's nice symmetry with individual module and cherry-picked paths.
```js
require('lodash.chunk');
require('lodash/chunk');

require('lodash._arraymap');
require('lodash/_arrayMap');
```

Should fp paths be changed from:
```js
require('lodash/fp/assign')
```
to
```js
require('lodash/assign/fp')
```
so that it allows
```js
require('lodash.assign/fp');
```

**Comment by d6u** [comment]
+1 for the change

**Comment by StreetStrider** [comment]
So this will allow individual packages to have fp-twin? Great if so. :thumbsup:

**Comment by jdalton** [comment]
Should I introduce both and have
```js
require('lodash/fp/assign')
// and
require('lodash/assign/fp')
```
or just
```js
require('lodash/assign/fp')
```

**Comment by jfmengels** [comment]
Both versions pretty much make sense. I'd only offer one though (so that you don't have inconsistent require uses even among the same project, or confuse beginners).

I'd stick to 'lodash/fp/assign', because I think it kind of looks like namespaces I guess. Import the assign method that is in the fp "sub-module" of Lodash. Both make sense, but if I had to choose I'd choose this one.

**Comment by demoneaux** [comment]
I think it makes more sense to use `lodash/fp/assign` to make it clearer that fp methods are being used. For individual cherry-picked methods, `lodash.assign/fp` seems okay, although I don't think most people would choose to cherry-pick individual fp methods.

**Comment by d6u** [comment]
It's difficult to say "most people" when there isn't any data. But I changed my mind, and think `lodash/fp/xxx` looks most consistent with `require('lodash/fp')`. Imagine:

```js
require('lodash/fp');
require('lodash/fp/map');

require('lodash');
require('lodash/map');

import _ from 'lodash';
import { map } from 'lodash';

import _ from 'lodash/fp';
import { map } from 'lodash/fp';
```

**Comment by StreetStrider** [comment]
Both ways make sence.

```
lodash → <whole lodash>
lodash/fp → <whole lodash FP>
lodash/assign → <assign from lodash>
lodash/fp/assign → <assign from lodash FP>
```

But another order is good for individual builds.
```
lodash.assign → <individual assign>
lodash.assign/fp → <individual assign FP>
```

I'd stick with first way for monolythic build and with second one for individual builds.

**Comment by willfrew** [comment]
I agree with @StreetStrider.

It makes sense to give dependants on individual builds access to an `/fp` version of the method, but it doesn't make sense to stop allowing people to `import _ from 'lodash/fp';`.

**Comment by rstacruz** [comment]
:-1: - a breaking change for marginal value.

:-1: for allowing both, too. having "one and only one way" to do things is much simpler and removes the burden of choice.

**Comment by jdalton** [comment]
>  a breaking change for marginal value.

On a release that hit Friday. With like zero folks using it. Let's chill on that tone right now.

**Comment by jdalton** [comment]
The value would be to keep symmetry with module paths. It can be a big help when switching between the two.

**Comment by rstacruz** [comment]
ah, sorry—thought it was a feature that's been around for a while now!

**Comment by jdalton** [comment]
Thanks everyone!

So far it look like folks aren't super excited about the `require('lodash/assign/fp')` style path beyond it being nice for folks coming from the individual packages.

I think I'll hold off on offering the `require('lodash.assign/fp')` individual package support until there's demand for it.

**Comment by jfmengels** [comment]
I think I'm changing my opinion on this. I did not play too much with individual module and cherry-picked paths (probably didn't understand the difference too actually), but as I try to use individual modules, I notice that I don't have access to individual fp packages (slow on the uptake), and it feels missing.

Since this was originally a question about the path to make this: `lodash.assign/fp` makes some sense (although it reorders the path, creating some confusion, and an extra hurdle to using fp), but what could also be done is `lodash.fp.assign`. It has the same order, but since it doesn't use `/`, it needs to be a **new** individual package, which I think is ok as a user (don't know as a maintainer).

I still maintain that consistency in the path is important, but having access to individual modules is even more so (so I'd be ok with `lodash.assign/fp` if it came down to that)

**Comment by c-dante** [comment]
I don't think it's needed. If you're doing it for symmetry to make it easier to merge over, the idea is, "Oh, I refactor my code and just append `/fp` to my cherry-picked require!" But you still need all intention of updating the code to begin with -- having the root package change from `lodash/*` to `lodash/fp/*` makes just as much sense for cherry picking as it does for the full library.

I guess I'm wondering how this is more or less symmetric than the alternative:
```
require('lodash.assign')
require('lodash.assign.fp') vs require('lodash.fp.assign')
```

On one hand, the former is "it's lodash -> assign. It comes in another flavor with -> fp", on the other, it's "There are two distinct flavors of lodash"
