### ISSUE TITLE
functional forms of _.has/_.hasIn

### ISSUE THREAD

**Issue by hhp21** [lodash/lodash#1974]
Given how `_.matches` and `_.property` are so useful, I assumed there would be an equivalent for testing if a path exists in an object, but there don't seem to be one? Right now I'm doing something like `_.partial(_.has, _, 'a.b.c')` which is fine but just feels a bit verbose - if there is something more concise I'd love to know!

**Comment by jfmengels** [comment]
If you want to use a functional programming style, you could try using lodash/fp (`require('lodash/fp')` if you use Node), which re-arranges the order of arguments into a more FP way (data-last), does not mutate passed data, auto-currying.... That way, you could use `has` as `_.has('a.b.c')`.

Docs for lodash/fp are under way, but you can find some temporary docs here: https://gist.github.com/jfmengels/6b973b69c491375117dc#_haspath-object. Do try them in a REPL before though, because some examples are buggy.

**Comment by hhp21** [comment]
Nice, thanks!
