### ISSUE TITLE
Lodash standalone using lodash-modularized

### ISSUE THREAD

**Issue by josmardias** [lodash/lodash#1990]
Is it possible to use lodash-modularized packages as dependencies on lodash standalone?

Consider a package that uses lodash modules (a.k.a lodash-modularized). Npm could do a great job on dedupe considering the standalone lodash on the user side (npm dedupe or npm v3).

On the frontend it should be a greater issue, but babel-plugin-lodash basically solves the problem there.

**Comment by jdalton** [comment]
The cherry-pick modules and individual npm packages server different purposes. Both with tradeoffs. The individual packages are for folks that may want few lodash methods at given versions but not for folks that want to bundle. Because they're standalone packages devs have expectations that they only have a few dependencies, which means a good amount of inlining of dependencies. This inlining is code duplication and avoided by cherry-picking. On the other hand cherry-picking gives you all modules at a given version. So while you get the smallest bundle you're limited to a blanket version. Most devs are either all cherry-picking or all individual packages. If you want to mix the two Webpack does offer several plugins to remap module paths.

**Comment by josmardias** [comment]
@jdalton 

Actually, my question was if https://www.npmjs.com/package/lodash can be modified to use https://www.npmjs.com/browse/keyword/lodash-modularized as dependencies. So npm v3 or dedupe on npm v2 could produce a smaller node_modules bundle.

Not sure if you answered it right, sorry if you did.

Great work btw. Thanks for this awesome package.

**Comment by jdalton** [comment]
No worries.

It would have a cost of hundreds of modules loaded for each version of lodash in the dep graph (one time each but enough). And then you'd inflated bundle sizes due to inlining to keep the individual packages dep counts low. So slower and larger bundles.

There is a package that experimented with it https://www.npmjs.com/package/lodash-modularized.
