### ISSUE TITLE
_.isError gives unexpected response

### ISSUE THREAD

**Issue by maxlapides** [lodash/lodash#1994]
I have an interesting edge case for you:

```
var localStorageTest = _.attempt(function() {
    localStorage.setItem('localStorageTest', true);
    localStorage.removeItem('localStorageTest');
});
return _.isError(localStorageTest);
```

In Safari Private Browsing, using lodash 4.1.0, this returns `true`. But in Safari Private Browsing, using lodash 4.2.0, this returns `false`. I think it should return true because `localStorageTest` will return an error in Safari Private Browsing: `Error: Error: QuotaExceededError: DOM Exception 22`

**Comment by jdalton** [comment]
The `_.isError` method didn't change but the [_.attempt method did](https://github.com/lodash/lodash/pull/1907). Basically if the caught error is an object we let it slide instead of wrapping it in an `Error` constructor. I think our behavior is correct here as wrapping it would obscure the error further.

**Comment by jdalton** [comment]
Actually, imma fix `_.isError` to work with custom errors to address both things.

**Comment by maxlapides** [comment]
Hooray! Thanks, @jdalton :)
