### ISSUE TITLE
_.groupBy change action but not record in changelog

### ISSUE THREAD

**Issue by chenbojian** [lodash/lodash#2072]
in 3.10 `_.groupBy(array, iteratee)`
iteratee have two parameters, the second is index.
But in 4.x _.groupBy the iteratee does not have a second parameter.

How can I group by index?

**Comment by jdalton** [comment]
For `index` you could always track a counter var.

**Comment by chenbojian** [comment]
in previous version I can do `_.groupBy([1,2,3,4,5,6], (item, index) => Math.floor(index/2)).toArray()` to get [[1,2],[3,4],[5,6]]. I know this is same with `_.chunk(array,2)`. Do you think this change about drop the support of index should be recorded to the changelog so that I can know what's changed in my project?

**Comment by jdalton** [comment]
> Do you think this change about drop the support of index should be recorded to the changelog so that I can know what's changed in my project?

It's in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400) as

> Made “By” methods like `_.sortBy` provide a single param to iteratees

I can add `_.groupBy` to the example.

**Comment by saikatguha** [comment]
`_.groupBy` with index parameter was useful for partitioning. e.g., `_.groupBy([1,2,3,4,5,6], (item, index) => index %3)` to get `[[1,4], [2,5],[3,6]]`

Introducing a counter into the local scope becomes unmanageable quickly since each iteratee needs to know which counter to use. This is a problem especially with chains where things may get grouped multiple times in a single expression.

Is there something similar to `_.chunk` but does striping?

**Comment by jdalton** [comment]
Striping? There is a request for [_.chunkBy](https://github.com/lodash/lodash/issues/1379).
