### ISSUE TITLE
Memoizing functions with multiple arguments

### ISSUE THREAD

**Issue by willpiers** [lodash/lodash#2115]
The docs mention that, "By default, the first argument provided to the memoized function is used as the map cache key"

It would be great if the cache were multi-dimensional so `_.memoize` worked well out of the box with longer functions. i.e. functions with more arguments.

If there is a simple way to do this already, we can close. If this sounds useful I can look into submitting a PR

**Comment by jdalton** [comment]
You can use [the `resolver` function](https://lodash.com/docs#memoize) to compose your own.

**Comment by willpiers** [comment]
So, what would the resolver look like?

`function(a, b) {
  return {a: b};
}`;

**Comment by jdalton** [comment]
The cache itself is modeled after [ES6 Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) so you're at its constraints.

**Comment by willpiers** [comment]
I know, it just seems like a weird API to me to use the first argument as the cache key.

**Comment by jdalton** [comment]
With the `resolver` you can use the middle or last arg or create some unique identifier of the combo of the three.

**Comment by jdalton** [comment]
Dup of #680.

**Comment by willpiers** [comment]
had to bring in another library to do proper memoization :( Still think _.memoize should support longer functions

**Comment by jdalton** [comment]
which other lib?

**Comment by willpiers** [comment]
Ended up using this function from `reactjs/reselect` https://github.com/reactjs/reselect/blob/master/src/index.js#L5-L20

**Comment by ashwathgovind** [comment]
You can also look at this one- https://github.com/caiogondim/fast-memoize

**Comment by VictorQueiroz** [comment]
There is any reason why `_.memoize` does not support multiple arguments caching?

**Comment by jdalton** [comment]
@VictorQueiroz serializing isn't cheap or straight-forward so we punt on that with a `resolver` function that you can customizer for your particular scenario.

**Comment by VictorQueiroz** [comment]
@jdalton It's for a good reason then. Thank's for the quick reply

**Comment by anton6** [comment]
@jdalton can you please provide an example of a simple resolver to do this? thanks

**Comment by jdalton** [comment]
@anton6 Sure thing!

```js
const example = _.memoize((...args) => args, (...args) => JSON.stringify(args))
example(1,3,2)
// => [1, 3, 2]
example(1,2,3)
// => [1, 2, 3]
```

**Comment by Lucretiel** [comment]
Is there a resolver that works out-of-the-box for sets of hashable arguments? That is, right now I can use a `Function` as my memoize key, but I can't use a `[Function, string]` pair, because that array has a different identity than the previous one, even if the identities are the same.

**Comment by vipcxj** [comment]
> @anton6 Sure thing!
> 
> ```js
> const example = _.memoize((...args) => args, (...args) => JSON.stringify(args))
> example(1,3,2)
> // => [1, 3, 2]
> example(1,2,3)
> // => [1, 2, 3]

> @anton6 Sure thing!
> 
> ```js
> const example = _.memoize((...args) => args, (...args) => JSON.stringify(args))
> example(1,3,2)
> // => [1, 3, 2]
> example(1,2,3)
> // => [1, 2, 3]
> ```

It not work with function argument. and sometimes, we just need `===` of arguments, not content equals.

**Comment by ahfarmer** [comment]
@jdalton the original suggestion in this issue was to create a multi-dimensional cache for memoize, which is very different from serializing multiple arguments into a single key, and in many cases much more performant.

To be clear: a multidimensional cache would be a Map of Map of Maps (one layer of nesting per argument).

Would you consider a PR for a change like this? The resolver argument could be left in place for those who want to serialize, and the multidimensional cache would be used when the "resolver" argument is not provided.

**Comment by giulioambrogi** [comment]
To add to the comments above.

If you try implementing memoize on your own in vanilla js you'll understand why the may have decided to provide a `resolver`.

## Root cause
`Objects` and `Array` are passed by reference in JavaScript.

## Example

Imagine you have a function that accepts three args `a`, `b,` c`, and you call it with `myFunc(1,2,3)`.

If you store `[1,2,3]` in your `cache` (which is an instance of `Map`), and then do `cache.get([1,2,3])` you will get `undefined`. Because this `[1,2,3]` is not the **same** instance as the one that was stored in the Map.

## Conclusion

For this reason I guess it's up to define how we want to has our arguments, e.g. using `JSON.stringify`. 

Hope it makes sense.

**Comment by Lucretiel** [comment]
@giulioambrogi That's precisely the problem, though; it's quite difficult to come up with your own resolver in plain vanilla JS, even though the INTENT of `memoize(function(a, b, c, d))` without a custom resolver is quite clear (we want to memoize on the unique set `(a, b, c, d)`). That's *why* I think this should be a feature; this is a problem worth solving once for everyone.

**Comment by ivanvpan** [comment]
I know this is an old PR, and I came here hoping there could be some such functionality, but really I am siding heavily with the maintainers in that this should not be implemented. Two reasons:
* Hard to find out how to consistently serialize argument by value (as opposed to reference). You would need to tell the memoizing functions which arguments you want to get memoized by value and which by reference only. So a simple `===` is the only thing that makes sense. Chances that that's what the user means when trying to memoize by multiple arguments are minimal in my opinion.
* Computing complex keys for cache is a problem due to performance reasons. Why I came here is that I am trying to memoize code that actually attempts to generate synthetic keys for many objects and is killing the server CPU, so I am trying to figure out how to optimize and simplify it, but really - if you are going to throw complex logic you might be hiding some CPU-heavy features.

So, while I wish this was a feature, unless somebody could propose an intuitive interface and efficient implementation then I do not see how this could be a usable lodash feature.

**Comment by shermam** [comment]
I think this feature request still makes a lot of sense. The multidimensional map mentioned in the description by @willpiers and in [this comment](https://github.com/lodash/lodash/issues/2115#issuecomment-577383887) by @ahfarmer would definitely work well for multi argument functions. I created here for me this crude implementation:

```js
export default function memoize(func) {
  const cache = new Map();

  const memoized = function (...args) {
    let innerCache = cache;
    for (let i = 0; i < func.length - 1; i++) {
      const key = args[i];
      if (!innerCache.has(key)) {
        innerCache.set(key, new Map());
      }
      innerCache = innerCache.get(key);
    }
    const key = args[args.length - 1];
    if (innerCache.has(key)) {
      return innerCache.get(key);
    }

    const result = func(...args);
    innerCache.set(key, result);
    return result;
  };

  return memoized;
}
```

This should work the same as `_.memoize(func, (...args) => JSON.stringify(args));`, but for my use case it was much more performant to go with the multidimensional version above.

A problem I noticed here is that when looping through the arguments to create the inner levels of maps I was unsure whether to use `args.length` or `func.length`. In JS you can declare a function that accepts a number of arguments and then call it with a different number of arguments. And in my case, I found some instances where different calls to the same function passed different number of arguments. And in those cases the map structure wouldn't be build correctly if I was using `args.length`. So using `func.length` seemed more reliable for me. But for a more comprehensive solution we would need to consider something like `const func = (...args) => {}`, where `func.length` would be 0, but callers would definitely pass more arguments to this function. I thought about doing something like `const length = Math.max(func.length, args.length)` which would help a bit, but if a function is being called with a variable number of arguments this would still be tricky.

**Comment by Place1** [comment]
I've been using the suggestion from @shermam but i've modified it to support functions that can be passed a varying number of arguments like variadic functions `(...args) => {}`

```javascript
export default function memoize(func) {
  const cache = new Map();

  const memoized = function (...args) {
    let innerCache = cache;

    // first layer of the map is the arguments length
    // if two calls have different number of arguments
    // then they cannot be the same call
    if (!innerCache.has(args.length)) {
        innerCache.set(args.length, new Map());
    }
    innerCache = innerCache.get(args.length);

    // using args.length because func.length is 0 for variadic functions
    for (let i = 0; i < args.length - 1; i++) {
      const key = args[i];
      if (!innerCache.has(key)) {
        innerCache.set(key, new Map());
      }
      innerCache = innerCache.get(key);
    }

    const key = args[args.length - 1];
    if (innerCache.has(key)) {
      return innerCache.get(key);
    }

    const result = func(...args);
    innerCache.set(key, result);
    return result;
  };

  return memoized;
}
```

Here's how I've been visualizing the data structure (cache).


```javascript
const fn = memoize((...args) => { });

fn(1, 2, 3)
fn(1, 2)
```

```
{
  3: { // first call
    1: {
      2: {
        3: [memoized-result]
      }
    }
  },
  2: { // second call
    1: {
      2: [memoized-result]
    }
  }
}
```

**Comment by DoctypeRosenthal** [comment]
> @anton6 Sure thing!
> 
> ```js
> const example = _.memoize((...args) => args, (...args) => JSON.stringify(args))
> example(1,3,2)
> // => [1, 3, 2]
> example(1,2,3)
> // => [1, 2, 3]
> ```

This should definitely be the standard case. 
We just debugged our code for 3 days with 4 senior developers in our company and removing `memoize()` from one function was the solution. 
It is totally contra-intuitive that a utility function from lodash only operates on one parameter. This could be logical for a more functional/currying-oriented library but not lodash where there are ample functions which take multiple arguments.

This (and some other strange behaviors with utility functions in lodash) discourage me to use this library any further.

**Comment by WolvenSpirit** [comment]
The memorize function should throw by default if supplied with multiple arg function and no resolver. This is trivial to implement and the utility as it is now, can only be categorized as a potential foot gun.
I would open a PR but i think it would be either sitting a lot until a major version is iminent or maybe frowned upon. It seems so simple to fix so that this behavior can be caught during CI..
