### ISSUE TITLE
Introduce typings for npm package

### ISSUE THREAD

**Issue by stasberkov** [lodash/lodash#2140]
TypeScript 1.6 has introduced new way of resolving module names that mimics the Node.js module resolution algorithm. This means the TypeScript compiler can currently load typings that are bundled with npm packages. 
Please include `lodash.d.ts` file into npm package and reference it from `package.json` file

```
{
...
    "typings": "./lodash.d.ts"
}
```

**Comment by jdalton** [comment]
I don't want to maintain the TypeScript definition file at this time. I'm not a regular user of TypeScript, nothing against it, it's just I wouldn't be able to support it to bar I'd want. You can use [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/lodash).

**Comment by dmethvin** [comment]
I really like TypeScript too but to @jdalton's point it can be difficult to maintain an accurate set of `.d.ts` files unless the library itself is written in TypeScript so that it happens automatically. Otherwise it's likely to drift out of sync and/or be inaccurate. You'll find that is the case with many DefinitelyTyped definitions where the original is not Typescript.

**Comment by StreetStrider** [comment]
@jdalton, on the other hand, folks from DT can't support the level of syncronizing with LoDash when new features arrive.

**Comment by jdalton** [comment]
I'm OK with typescript getting that level of support since the project isn't written in TypeScript.
