### ISSUE TITLE
feature request for method _.fromPath

### ISSUE THREAD

**Issue by continuata** [lodash/lodash#2169]
the inverse of `_.toPath`

fromPath should convert a path Array to a path string.

```js
_.fromPath(['a', '0', 'b', 'c']); 
// => 'a[0].b.c'
```

as paths are used by lodash both in string and array form, it makes sense to be able to convert between the two in both directions.

**Comment by jfmengels** [comment]
Can you elaborate on a usecase for it? I'm not sure I see the value right now.

**Comment by steelsojka** [comment]
@jfmengels I think a good use case would be when manipulating a path. An array is much easier to work with than a path string. I could see converting from a path string to an array, modifying that array, and converting back into a path string. I remember reaching for this method in lodash a couple weeks ago only not to find it... although I can't remember the exact use case.

**Comment by jfmengels** [comment]
@steelsojka What would you use that stringified path for? If it's meant to be used with Lodash methods, they already support both styles, so why not just keep it as an array?

```js
_.get({a: [{b: {c: 2}}]}, ['a', '0', 'b', 'c']) // => 2
_.get({a: [{b: {c: 2}}]}, 'a[0].b.c') // => 2
```

**Comment by steelsojka** [comment]
@jfmengels There's other libraries that use a similar string path that might not use the Lodash implementation. So I guess the difference would be if you were using it outside of the context of Lodash. I have a library that does recursive generators and yields a string path of the currently yielded property. I had to implement my own array to string function. I believe this was the scenario I was referring to above.

**Comment by continuata** [comment]
@jfmengels my specific use case is that I needed to store the path in the DOM to be used later for get, and to be sent to the server on submit, an array was not suitable.
My assertion is that if the lodash methods allow both array and string (e.g. `_.get()`) we should be allowed a way to move between them at our choice.

Another use case would be sending the path in a URL, which I've considered doing for another application.

**Comment by jdalton** [comment]
Thanks @continuata!

As requests go we usually [wait for there to be a bit more user demand](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) before considering a method for core. Until then while not perfect you can do `path.join('.')`.

**Comment by continuata** [comment]
@jdalton err ... well as you may have noticed ... I already implemented it and tested it and put in a PR. (i.e. no need to code up a hack like `path.join('.')` )

So to me it seems a bit of a no-brainer ... the work has been done and ready to merge.

**Comment by jdalton** [comment]
Having a PR is super helpful when a method gets the green light for inclusion in core.
However, a PR isn't the catalyst  for inclusion .

**Comment by jdalton** [comment]
Vote with :+1:

**Comment by continuata** [comment]
@jdalton sure, I understand ... I'd misunderstood what you said as implying that the inertia for inclusion was related to the fact there was a more available hack; which is moot when there's a tested solution. I saw your note on the PR after responding ;-)

I do understand you holding off if you don't think there's a need for this. I proposed it because I had a personalneed for it, and was surprised to discover there was no method for the inverse of `toPath`.

**Comment by daniel-pedersen** [comment]
A sidenote is that right now lodash is ambiguous in its use of the term 'path', referring to both the `a.b.c` and `['a', 'b', 'c']` style. This makes the names `toPath/fromPath` somewhat confusing, as both take a 'path' as input and produce a 'path' as output.

This could be resolved by making `toPath` it's own inverse, or by disambiguating the term 'path' in documentation.

Either way, I support this feature.

**Comment by jdalton** [comment]
Vote with [reactions](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/#reacting-to-ideas-in-issues-and-pull-requests). It makes it easier to [sort issues](https://help.github.com/articles/about-discussions-in-issues-and-pull-requests/#sorting-issues-and-pull-requests-by-reaction) by them.

**Comment by continuata** [comment]
@daniel-pedersen I was convinced at one point that the existing `toPath` did just that. Currently though if you put an Array as input it returns a clone of the Array.
I do agree with your point about the naming being confusing given that both are effectively paths.

I'm not sure if I agree with using the same method as its own inverse though ... it makes a functional pipeline of chained methods behave in an unpredictable manner. The concept of a one -> one mapping for every method feels a lot safer to me; so maybe we could name them `toPathArray` and `toPathString` to avoid confusion?

**Comment by continuata** [comment]
@jdalton how do you undo a reaction? I accidentally clicked the thumbs-down. :-(

**Comment by daniel-pedersen** [comment]
@continuata I agree, calling them `toPathArray` and `toPathString` seems like the best idea. You can apply the thumbs-down reaction again to undo it.

**Comment by continuata** [comment]
@daniel-pedersen phew .. that nearly ruined my whole day ;-)

**Comment by continuata** [comment]
@daniel-pedersen I'd probably just make `toPathArray` an alias for `toPath` to maintain backward-compatibility.

**Comment by gitowiec** [comment]
@continuata I would like to use Your great idea for redux-forms addressing array of fields....

**Comment by gitowiec** [comment]
@jdalton joining with a dot does not makes `path[0]name` string...

**Comment by TrevorJamesH** [comment]
I have a use case for this using react and redux. I have a parent component passing dynamically built paths to it's children to extract their data from the redux store in their mapState functions. Passing a new array each time it's built, even if it's the same, causes the children to rerender and call their mapState function. By turning the path back into a string before passing it, it would pass the equality checks and skip the unneeded work.

I know I can join it, or stringify it, but it would be much neater if the string stayed compatible with toPath.

**Comment by johnchristopherjones** [comment]
My use-case is that I want to have a save inverse of `toPath`.

In particular, I have a hierarchical menu that I want to have an easier time working with.
- I have an array of objects that have their position in a hierarchical menu listed as an array of strings.
- For constant-time access and easy construction of the menu, I'd like to construct two objects from that data:
  1. a nested object from those arrays so that I can easily look up child menu names, and
  2. an object where each key is the path and each value is an array of all final menu items under that path.

I would like to be able to easily move between the two data structures.  Lodash's `update`, `set`, and `get` all make it easy to work with these data structures at first blush, but I can only safely go in one direction due to the lack of a `fromPath`.

This isn't precisely a hard problem, but it's constraining my solution space. If I want to use `get`, `set`, and `update`, I need lodash-compatible paths. But without an official `fromPath`, I should really write my own to/from path for the second object so that I can be confident in the path serialization/deserialization to get back to a lodash-compatible path.

**Comment by kevin-lindsay-1** [comment]
Yeah +1 on this as well, I keep finding cases where it would be handy to have such a util. It strikes me as interesting that so many people agree that the `property path array` format and `property path string` format are interchangeable, but Lodash only supporting 1-way conversion on something that's seen as interchangeable seems to me to be a pretty clear-cut case of a feature that should exist but doesn't.

I agree that they're interchangeable formats, and as such I can't remember the amount of times I've thought to myself "yeah this util must exist" before forgetting that it doesn't, for really no reason. If they're interchangeable, then you should be able to switch between them on-demand.

As it stands, if I have an implementation that uses paths, there's a near guarantee that I'll end up with the array format where I don't want it, because it would be too much trouble (or inconvenient to justify business logic relying upon) to switch it to a string with a custom function.

**Comment by joshuat** [comment]
Once again voicing support for this. My specific use case is printing an error path and I'd vastly prefer having an existing utility for this, especially considering the presence of `toPath` already present in lodash.

**Comment by stukennedy** [comment]
@jdalton can we revisit this? Seems to be unanimous  agreement here that a solution like this would be of benefit. Can we re-open the PR? https://github.com/lodash/lodash/pull/2170

**Comment by HamzaM3** [comment]
Just wanted to say that I needed this feature. I used it to keep track of the position I am within an object and throw the error with the path in the message.

(There should be a platform to exchange library patches)

**Comment by weibinzhu** [comment]
I need this feature too. For some reason I need to store and compare the path, and string is much neater in this use case.
