### ISSUE TITLE
Lodash always exported to `window._` in `lodash@^4`

### ISSUE THREAD

**Issue by nowells** [lodash/lodash#2251]
It appears that `lodash@^4` added the [`(freeWindow || freeSelf || {})._ = lodash;`](https://github.com/lodash/lodash/blob/master/dist/lodash.core.js#L3963) line to address some AMD issues. However, this seems to have the side effect of always exporting lodash to `window._` in our webpack builds. Was this intended? Is there a way to better restrict this fix for the AMD issue by checking for `typeof window.define` or something?

It appears this was added in https://github.com/lodash/lodash/commit/7862ae6d3625436ced505b3db507743e46c30432

Thanks for your excellent work on lodash, it is as always a wonderful library.

**Comment by megawac** [comment]
#1798 and #1852 (I think this should be addressed as a bug btw @jdalton)

**Comment by jdalton** [comment]
Hi @nowells,

This is by design. If you'd like to pull lodash off the global you can use `_.noConflict`.

**Comment by nowells** [comment]
> This is by design.

Fair enough. Just a bit odd in a webpack/browserify world to call that on every package (likely at the entrypoint) but sounds like this is worth the tradeoffs. Thanks for the quick reply!

**Comment by jdalton** [comment]
I'll update the code comment a bit to make it more clear.

**Comment by jdalton** [comment]
It's actually for webpack/browserify.

**Comment by mjmasn** [comment]
@jdalton I've just come across the same issue. Caused problems with Meteor because it uses underscore 1.5.2 internally and I was using the following in my code:

```javascript
import lodash from 'lodash';
```

which isn't at all obvious that it would overwrite the global value of `_`.

Easily fixed with `_.noConflict()` so all's well but may be worth making this clear in the documentation...

**Comment by jdalton** [comment]
It turns out this issue is due to a Webpack transform [that's catered to end users and not libraries](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829), like Lodash, that have AMD support. For the time being, Webpack recommends [opting-out of their AMD parsing](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512) if you're running into issues.
