### ISSUE TITLE
Flow interface support for lodash/fp

### ISSUE THREAD

**Issue by crittelmeyer** [lodash/lodash#2293]
Hello, I would like to use lodash/fp with Flow and was just wondering if anyone has done any work towards creating a Flow interface for lodash/fp? I couldn't find anything on the web. Probably will be relatively trivial to convert the existing lodash interface that comes with Flow to one that works for lodash/fp, but I wanted to make sure it didn't exist already before I did it.

**Comment by dmethvin** [comment]
TypeScript got a solution via DefinitelyTyped and  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7896 so the best way to get this in Flow would be for Flow to be able to consume (or transform) DT files. However, from https://github.com/facebook/flow/issues/7 it seems like that approach is stalled. Since DT has an incredibly extensive set of type definitions it would be really good if Flow could use them. Or you could switch to TypeScript?

**Comment by crittelmeyer** [comment]
Ahhh, to switch to TS or not to switch to TS. The theme of my year

**Comment by jdalton** [comment]
Hi @crittelmeyer!

I'm not aware of an existing flow interface for lodash/fp. Feel free to add a section to our [resources](https://github.com/lodash/lodash/wiki/Resources) to cover things like this though.
