### ISSUE TITLE
forEach bug?

### ISSUE THREAD

**Issue by gzhegow2all** [lodash/lodash#2307]
`var arr = [1,2];
_.forEach(arr, function (val, key) {
  console.log(val);
  arr.splice(0, 1);
});`

logs `1` then `undefined`
why? i am waiting program to log `1`, `2`...

**Comment by gzhegow2all** [comment]
Can it may be about "for" is working with cloned object, but if we trying to change original object - the for cycle is aborting?

**Comment by devanp92** [comment]
The reason you're getting this error is because ```arr.splice(index, deleteCount)``` **removes** elements from the array at the specific index to (index + deleteCount).

Here is an easier way to see this:
```
var _ = require('lodash')
var arr = [1,2]; 
_.forEach(arr, function (val, index) { 
    console.log('i: ' + index + ', val: ' + val); 
    console.log('Array before splice', arr);
    arr.splice(0, 1); 
    console.log('Array after splice', arr);
});
```

Notice how there is an index out of bounds error on the second iteration (```i = 1```). Since there is only one element left in the array, you cannot access index 1.

**Comment by gzhegow2all** [comment]
so... i thought when i remove some value from array by splice, the indexes will be recalculated automatically...
