### ISSUE TITLE
_.every returns true for empty or undefined collections

### ISSUE THREAD

**Issue by daemonaka** [lodash/lodash#2350]
Currently, _.every performs no checking to ensure that it has values to iterate over. This results in unexpected behaviour such as:

    _.every (void 0, _.isNumber)
    // -> true

    _.every (null, _.isNumber)
    // -> true

    _.every ([], _.isNumber)
    // -> true

    _.every ({}, _.isNumber)
    // -> true

**Comment by jfmengels** [comment]
That is the expected behavior, as it follows the behavior of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every. Returning true for values is `void 0`/`null` is a side-effect of them being considered as having no elements.

Think of it this way: it returns `false` when the iteratee returns `false` for any of the elements, and `true` otherwise. With no elements, it never returns `false`, so it returns `true`.

**Comment by ariesxje** [comment]
According to MDN

> The every() method tests whether all elements in the array pass the test implemented by the provided function.

To my understanding, it should only returns true if and only if all the elements in the array pass the test.
It is not "if there is no elements fails test, it returns false".
If this is the case, we can simply use !_.some()

It still think it should return false for null or empty arrays, because it means no element passes the test.

Think about this use case:
I want to know if one item is duplicated with the other by check an array of fields (e.g. firstname and lastname)

So, this is what I will do
`_.every(uniqueKeys, function(key) {
  return item1[key] === item2[key];
})`

The code means: if every value of the uniqueKeys is the same, then two items are duplicated.
E.g. item1 = {firtname: 'Tom', lastname: 'Smith', age: 24},
 item2={firstname: 'Tom', lastname: 'Smith', age: 48}, 
uniqueKeys=['firstname', 'lastname'];
then item1 and item2 are duplicated.

But when the 'uniqueKeys' is empty, does it mean two items are duplicated, or not?

Apparently, if we don't define 'uniqueKeys' or it is empty, we would not consider two items are duplicated because there is no field to check.
But the above code will return true, which means item1 and item2 are duplicated.
So, we need to add an extra condition before the 'every'
`if (!uniqueKeys) return false;`

Or another simple example, I would like to know which class that every student in it gets higher than 80 marks in math exam.
`_.every(mathExamMarks, checkHigherThan80)`

What if the entire class didn't attend the exam, or even the exam is not even taken yet, then the mathExamMarks would be empty, but it still returns true, which means even no one has math exam mark, but the whole class is higher than 80.

it is exactly the same as `!_.some(mathExamMarks, checkHigherThan80)`
So, my opinion is, if _.every = !_.some, then one can replace the other, and there is no point of having both of them.

Hope it makes sense.

**Comment by jdalton** [comment]
Related to #2129 & #728.
