### ISSUE TITLE
_.isEqual returns false when two otherwise identical objects have different constructors

### ISSUE THREAD

**Issue by Bladedanxa** [lodash/lodash#2362]
I have been unable to work out if this is intended behavior and understand if it is but was surprised (especially given how involved it can be to detect an objects constructor sometimes) when I compared an object literal with the results of a mysql-node row (constructor: RowDataPacket) to find that despite visually appearing to be identical _.isEqual returned false.

I have been able to work around it by using _.clone to create the object literal and then setting its attributes before comparison but this seemed ugly and unintuitive to me.  If this is intended behavior can you recommend a method of comparison that only compares the enumerable attributes?
Thanx

**Comment by jdalton** [comment]
Hi @Bladedanxa!

Over the years I've started to relax some of the more strict checks in our equivalence method. For example, `-0` and `0` are now considered equal. The constructor check is so that `Foo` instances are seen as different than `Bar` instances. I think that's still a fair distinction to make. To get around this you can create an object like:

```js
var o = _.create(RowDataPacket.prototype, {
  'propA': 1,
  'propB': 2
});
```
