### ISSUE TITLE
Propagate recent changes to lodash.debounce

### ISSUE THREAD

**Issue by Offirmo** [lodash/lodash#2385]
This (great !) recent change to lodash.debounce : https://github.com/lodash/lodash/issues/2054#issuecomment-220152292

seems to not have been propagated to its individual npm package : https://www.npmjs.com/package/lodash.debounce (currently 4.0.6)

When following the "package source" link, we arrive [here](https://github.com/lodash/lodash/tree/4.0.6-npm-packages/lodash.debounce) which shows the old code.

But maybe there is an automated schedule and this update is pending ?

Thanks for the huge work !

**Comment by jdalton** [comment]
The process is manual and usually drags behind  a week or so.

**Comment by jdalton** [comment]
You should really use `require('lodash/debounce')` from the primary package. It will result in smaller bundles with [lodash-webpack-plugin](https://www.npmjs.com/package/lodash-webpack-plugin). The primary `lodash` package is the most depended on package in npm so is likely already in your users local npm cache. We're discontinuing the individual method packages in [v5](https://github.com/lodash/lodash/wiki/Roadmap) because their is no real win to using them.

**Comment by Offirmo** [comment]
With all your recent changes, everything works fine now ! Thank you so much for the good work !
