### ISSUE TITLE
Suggested _.forOwn Documentation Update

### ISSUE THREAD

**Issue by bryandowning** [lodash/lodash#2396]
I suggest the following change to the `_.forOwn` docs (and maybe the docs for other iteration methods as well):

Change: 
> Iteratee functions may exit iteration early by explicitly returning false.

To:
> Iteratee functions may exit iteration early by explicitly returning false (similar to a `break;` statement in a normal loop). Iteratee functions may also skip an iteration with a simple `return;` statement (similar to a `continue;` statement in a normal loop).

**Comment by jdalton** [comment]
I think that's a bit overkill.  Folks should get how functions work.

**Comment by bryandowning** [comment]
Sure, I guess the reason I wanted to see some clarification is that having the iteratee function return false is actually different from returning other falsey values, which is a factor of lodash — not functions.

**Comment by k0pernikus** [comment]
@jdalton I just googled "Iteratee functions may exit iteration early by explicitly returning false" from the docs in order to get a better understanding of the meaning of the statement. And I landed here.

The proposed change by @bryandowning made me understand the meaning instantly. So as a reader of the lodash documentation, I don't think it is too much.

When reading the original documentation was wondering: "What is the difference difference between `return` and `return false` here?"
