### ISSUE TITLE
flowRight/compose loses function arity

### ISSUE THREAD

**Issue by adriantoine** [lodash/lodash#2437]
Hi!

I'm trying to migrate from Ramda to lodash and I'm using `_.curry` on a function composed with `_.flowRight` but it doesn't work:
```js
const add5 = (a, b) => a + 5;
const sub = (a, b) => b - a;

const subPlus5 = _.flowRight(add5, sub);
console.log(subPlus5(50, 100)); // 100 - 50 + 5
  
const curriedSubPlus5 = _.curry(subPlus5);
const sub50Plus5 = curriedSubPlus5(50);
console.log(sub50Plus5(100)); // should log 55 but shows "sub50Plus5 is not a function"
```
Here is a jsbin: https://jsbin.com/qerasi/69/edit?js,console

It does work if I use the function arity parameter of `_.curry`:
```js
const curriedSubPlus5 = _.curry(subPlus5, 2);
const sub50Plus5 = curriedSubPlus5(50);
console.log(sub50Plus5(100)); // logs "55"
```
(https://jsbin.com/qerasi/80/edit?js,console)

It also works if I use the Ramda `R.compose` function instead of `_.flowRight`: https://jsbin.com/qerasi/81/edit?js,console

I wanted to know if lodash will support this use case of curried composed functions or do I have to use the `arity` paramter of `_.curry`?

Thanks!

**Comment by jdalton** [comment]
Arity is one of those tricky things in JS that can be obscured by `Function#bind` or ES2015 default params. Lodash opts for folks to be explicit if it can't resolve it from a function's `length`.

If you're coming from R you might dig the [lodash/fp](https://github.com/lodash/lodash/wiki/FP-Guide) modules. Because FP doesn't favor variadic functions we've had to split them out. You're looking for [_.curryN](https://github.com/lodash/lodash/wiki/FP-Guide#new-methods) which will allow you to specify an arity:
```js
fp.curryN(arity)(func);
```

**Comment by adriantoine** [comment]
Ok, that's interesting, thanks!
