### ISSUE TITLE
Suggestion: Add `files` property to package.json

### ISSUE THREAD

**Issue by xswordsx** [lodash/lodash#2441]
Adding the following lines to package.json [files](https://docs.npmjs.com/files/package.json#files)
```js
...

"files": [
  "lodash.js",
  "lodash.min.js"
],

...
``` 
to `package.json` will halve the module size:

|Modification|Size|
|----:|:-----|
|Original| 1,27 MB (1 337 525 bytes)|
|With `core.js & core.min.js`| 699 KB (716 321 bytes)|
|Without `core.js & core.min.js`| 575 KB (589 551 bytes)|

**Comment by xswordsx** [comment]
OK, it looks like it's a dupllicate of https://github.com/lodash/lodash/pull/322

**Comment by demoneaux** [comment]
Hi @xswordsx! We currently maintain [a separate branch](https://github.com/lodash/lodash/tree/npm) which has the built version of lodash for publishing to npm. The npm package already has all unnecessary files removed (tests, vendor files, etc.). The additional file size you’re seeing is due to separate files for each module (eg. `lodash/each`).
