### ISSUE TITLE
_.reverse mutates the input array

### ISSUE THREAD

**Issue by danijar** [lodash/lodash#2442]
I would argue that this is not the behavior most programmers would expect. Especially since `_.reverse(array)` returns a reference, I think the input should not be mutated. Maybe in-place reversal could be implemented as a second parameter defaulting to false: `_.reverse(array, inplace)`.

**Comment by jfmengels** [comment]
Hi @danijar!

The method does the same thing as the native `reverse` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse), which also mutates the array. Since it follows the behavior of the native method, I would argue the opposite and say it is what most programmers would expect (or at least for the ones that use the native implementation). We don't usually differ from the native behavior, so I doubt we'll go with this.

If you want to create a new reversed array, you could use the native `splice` and call `reverse` on that one.

**Comment by jdalton** [comment]
As @jfmengels mentioned this is by design. However you can use `require('lodash/fp/reverse')`, part of our [fp modules](https://github.com/lodash/lodash/wiki/FP-Guide), which will not mutate the original array.
