### ISSUE TITLE
_.isUndefined() unexpected results

### ISSUE THREAD

**Issue by jstew529** [lodash/lodash#2486]
when trying to use the lodash method of `_.isUndefined()` with a not yet defined `value` resolves with a `ReferenceError` of value not being defined.

Looking at the [source](https://github.com/lodash/lodash/blob/master/dist/lodash.core.js#L2925) for this method confirms why this error would be received. It seems this method was developed anticipating a declared AND 'defined' value (defined/undefined) before being passed into the method call.

```js
function isUndefined(value) {
    return value === undefined;
}

/** 
 * Unit Test
 *
 * _.isUndefined(void 0) => true
 * _.isUndefined(null) => false
 * _.isUndefined(foo) => 'ReferenceError: foo is not defined(...)'
 */
```

Any reason not to utilize the vanilla javascript to check a values type instead?

Example:
```js
function isUndefined(value) {
    return typeof value === 'undefined';
}

/** 
 * Unit Test
 *
 * _.isUndefined(void 0) => true
 * _.isUndefined(null) => false
 * _.isUndefined(foo) => true
 */
```

**Comment by jdalton** [comment]
Hi @jstew529!

JavaScript methods can't help you with undefined variable references.
It'll throw with either implementation.

**Comment by jstew529** [comment]
@jdalton thanks for the quick reply!

new console session reveals this:
```js
typeof foo === 'undefined'
true
foo === undefined
VM31461:1 Uncaught ReferenceError: foo is not defined(…)
```
The current version of `isUndefined` isn't (in my opinion) truly testing the state of being defined if it resolves with refernce errors if a value isn't 'defined'...  

Thoughts?

**Comment by dmethvin** [comment]
If the symbol `foo` hasn't been defined anywhere, using it as a variable is going to generate an error as you see. That is why the canonical way to test for a *variable* being defined is `typeof foo === "undefined"`. JavaScript itself is giving you that error with `_.isUndefined(foo)` before any lodash code ever runs because it has to determine the value of `foo` to pass it to lodash.  If you are checking something like a property this is not an issue, so `myobject.foo === undefined` or `_.isUndefined(myobject.foo)` works fine. 

There should be some JavaScript intros or StackOverflow questions covering this, it's something you will need to understand well to become a good JS programmer.

**Comment by donnyv** [comment]
This `_.isUndefined()` should be changed to `_.isPropUndefined()` Makes it clear that this only works on properties.

**Comment by dmethvin** [comment]
@donnyv that is not correct, sorry if my example led you to believe that but it wasn't intended to be a full tutorial. For example,
```js
// Is this argument undefined?
function myIsUndef(arg) {
   return _.isUndefined(arg);
}
// Did my function return `undefined` (implicitly or explicitly)?
   ...
   var result = myFunc(42);
   if ( _.isUndefined(result) ) {
       // yep, it returned undefined
   }
  ...
```
Again, it's important to understand how this works in JavaScript in order to use the language effectively and there's nothing lodash can do to change that.

**Comment by donnyv** [comment]
I see, the way javascript is using "undefined" is the issue.

Just as another example. This returns true also, no need to declare a variable.
`_.isUndefined(myIsUndef());`
