### ISSUE TITLE
Missing methods in typescript lodash

### ISSUE THREAD

**Issue by hhsadiq** [lodash/lodash#2493]
> TypeScript code (from https://lodash.com/docs#chain):
> 
> var users = [
>     { 'user': 'barney',  'age': 36 },
>     { 'user': 'fred',    'age': 40 },
>     { 'user': 'pebbles', 'age': 1 }
> ];
> 
> var youngest = _.chain(users)
>     .sortBy('age')
>     .map(function(chr) {
>         return chr.user + ' is ' + chr.age;
>     })
>     .first()
>     .value();
> tsc compiler complaints:
> 
> error TS2339: Property 'sortBy' does not exist on type 'LoDashExplicitArrayWrapper<{ 'user': string; 'age': number; }>'.
> the same happens with pluck
> 

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/6586

Same happens with _.split and countless other methods.

**Comment by Koslun** [comment]
@hhsadiq Using type definitions for lodash too but it's not something officially managed by this project. In that case they would also be available from this repo through npm. If you want that you should open a new issue for that.

The lodash type definitions you referenced are managed on the repository you referenced and you should open a new issue for those specific missing types rather than reference and post in that already closed issue.

**Comment by jdalton** [comment]
@hhsadiq There is also [Lodash TypeScript definitions](https://github.com/typed-typings/npm-lodash) for [Typings](https://www.npmjs.com/package/typings).
