### ISSUE TITLE
v4.14.0 broke _.noConflict()?

### ISSUE THREAD

**Issue by caseprince** [lodash/lodash#2531]
We had `^4.12.0` in an internal dependency's package.json, and we also have some legacy code that relies on underscore, so we've using `_noConflict()` to restore window._ to underscore. This was all working great until recently, when `_` became `undefined`. Seems like it happened concurrently with yesterday's `4.14.0` release? We've pegged our lodash version to `4.12.0` and that seems to have fixed it.

**Comment by jdalton** [comment]
I can't repro. Could be related to #2527.

**Comment by jdalton** [comment]
I can't repro anything wrong with `_.noConflict`. It's probably because we're no longer always exporting to the global when in the browser context.

**Comment by caseprince** [comment]
Ah - ok - so you're saying just removing `_noConflict()` all together could also fix? I'll try that and report back for science. Thanks for the quick response!

**Comment by jdalton** [comment]
> so you're saying just removing `_.noConflict()` all together could also fix? 

Possibly.

**Comment by jdalton** [comment]
It turns out this issue is due to a Webpack transform [that's catered to end users and not libraries](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829), like Lodash, that have AMD support. For the time being, Webpack recommends [opting-out of their AMD parsing](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512) if you're running into issues.
