### ISSUE TITLE
_ added as a global to window

### ISSUE THREAD

**Issue by ketan** [lodash/lodash#2550]
Hi,

I'm using requirejs to load lodash and noticed that `_` is exported as a global to `window`. According to the release notes at https://github.com/lodash/lodash/wiki/Changelog#v4140 and a comment here https://github.com/lodash/lodash/issues/1798#issuecomment-233804586, I assumed that `window._` should not be defined.

Am I doing something wrong?

**Comment by jdalton** [comment]
While we no longer unconditionally export to the global in the browser we still export to the global for AMD use because:
>
~~~js
  // Some AMD build optimizers, like r.js, check for condition patterns like:
  if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {
    // Expose Lodash on the global object to prevent errors when Lodash is
    // loaded by a script tag in the presence of an AMD loader.
    // See http://requirejs.org/docs/errors.html#mismatch for more details.
    // Use `_.noConflict` to remove Lodash from the global object.
    root._ = _;
>
    // Define as an anonymous module so, through path mapping, it can be
    // referenced as the "underscore" module.
    define(function() {
      return _;
    });
  }
````
