### ISSUE TITLE
FP Guide in main docs

### ISSUE THREAD

**Issue by Andarist** [lodash/lodash#2566]
Is there a plan to include FP guide into main docs? Maybe even via a switch somewhere. It is really inconvenient to jump between those two. 

In addition examples for fp-only functions would be super helpful (such as `spreadFrom`).

Probably I could help with examples for those if they land in main docs.

**Comment by jdalton** [comment]
Hi @Andarist!

There's an experimental translation [here](https://github.com/jfmengels/lodash-fp-docs).

**Comment by spudly** [comment]
@jdalton, jfmengels/lodash-fp-docs looks dead (no commits since June 1st). Has it been abandoned? If so, what's the plan (if any) going forward to provide better docs for lodash-fp?

**Comment by jdalton** [comment]
Hi @spudly

It's not a Lodash project. You might try pinging it. 
That said we have since then rewritten [our site](https://github.com/lodash/lodash.com).
I'm open to someone streamlining conversion but that's pretty tricky.
Until then if there's something that could make the [FP Guide](https://github.com/lodash/lodash/wiki/FP-Guide) lets have it :grinning:

**Comment by StreetStrider** [comment]
As I remember docs improvement was an @jfmengels initiative. He might just lost his interest in it.
