### ISSUE TITLE
Also escape hyphens in escapeRegExp

### ISSUE THREAD

**Issue by yaycmyk** [lodash/lodash#2573]
They're a special character in that they denote ranges, so if it is not escaped and ends up inside a character block like:

```js
new RegExp(`[${_.escapeRegExp('a-z')}]`, 'g')
```

where the user is looking for a literal hyphen, the regex will return all letters a to z when the intent was the characters a, -, and z.

**Comment by jdalton** [comment]
I've got back and forth on having a super robust escape which guards against partials (like escaping `a`, `b`, `c`, `d`, `e`, and `f` because they could be part of a unicode sequence) and have opt-ed for the simpler approach. This is one that's been used by util libraries since 2005 and I'm not looking to expand on it.
