### ISSUE TITLE
Lodash exporting globably even after v4.14.0

### ISSUE THREAD

**Issue by AndrewBailMYOB** [lodash/lodash#2671]
quick question, You said in [this](https://github.com/lodash/lodash/issues/1798) issue that as of 4.14.0 lodash would no longer be exported globally even when bundled with webpack. Im on 4.16.1 and this is still happening for me. Is there a config setting I'm missing?

**Comment by jdalton** [comment]
Here's [our export snippet](https://twitter.com/npms_io). Feel free to review it to get an idea of what's up.

**Comment by megawac** [comment]
wrong hyper link :) but I can't reproduce

**Comment by AndrewBailMYOB** [comment]
I cant exactly see whats up.

Ill try to describe my problem again.
Originally we were on 4.12.0 bundling within webpack. Importing lodash js would conflict with the global _ variable in window. 

We can solve it by using _.noConflict, but i was looking for a nicer solution.

Allegedly i should be able to upgrade to 4.14.0 (or higher) and lodash will no longer unconditionally import globally.

**Comment by NekR** [comment]
@AndrewBailMYOB see https://github.com/lodash/lodash/issues/1798#issuecomment-269140831

**Comment by progman32** [comment]
We worked around the issue by disabling the AMD loader for lodash in our webpack config:
```
loaders: [
  { test: /node_modules\/lodash/, loader: "imports?define=>undefined" }
]
```

This causes the export code to use the `freeModule` branch, which works for our purposes.

**Comment by jdalton** [comment]
It turns out this issue is due to a Webpack transform [that's catered to end users and not libraries](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829), like Lodash, that have AMD support. For the time being, Webpack recommends [opting-out of their AMD parsing](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512) if you're running into issues.
