### ISSUE TITLE
Change _.fromPairs() to specify key and value from array of objects

### ISSUE THREAD

**Issue by djKianoosh** [lodash/lodash#2677]
First, I love lodash and use it all the time, thanks!

I found a use case where we would like to modify `fromPairs` a little bit... 

Currently, if you pass in an array like this: `_.fromPairs([['a', 1], ['b', 2]]);`, you get:
`{ 'a': 1, 'b': 2 }`.

I'd like to pass in an array of objects like this:
```
let test = [
  { name: 'first', value: 'first val' },
  { name: 'second', value: 'second val' }
]
_.fromPairs(test, 'name', 'value');
```
Which would result in `{ 'first': 'first val', 'second': 'second val' }`

The code would look like this:
```
function fromPairs(pairs, key=0, val=1) {
  var index = -1,
      length = pairs ? pairs.length : 0,
      result = {};

  while (++index < length) {
    var pair = pairs[index];
    result[pair[key]] = pair[val];
  }
  return result;
};
```
Only changes to `_.fromPairs()` in 4.16.1: https://github.com/lodash/lodash/blob/4.16.1/lodash.js#L7227 would be to:
* Add the two arguments `key` and `val` and give them defaults `0` and `1` for backwards compatibility
* Use key and val to construct the result: `result[pair[key]] = pair[val];`

Another variation would be to return an array of single objects, but then that would be a different function other than `fromPairs`, which returns a single object, not an array. 

Question is does something like this already exist and I'm not seeing it? Or else would this be a valid change to `_.fromPairs()`?

**Comment by jdalton** [comment]
Hi @djKianoosh!

I'd like to keep it close to the ECMAScript flavors of [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) since consuming key-value pairs is [a part of JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Relation_with_Array_objects).

You may have luck creating a mixin that maps these objects to key-value pairs. You can ping our [gitter chat](https://gitter.im/lodash/lodash) for help.
