### ISSUE TITLE
fp/map doesn't seem to return an index

### ISSUE THREAD

**Issue by wsmd** [lodash/lodash#2686]
I'm trying to iterate over an array of object literals, update their position values to `index + 1`, and return a new array of the same items but with new positions:

```js
const oldArray = [
  { name: foo, position: 1 }, // => position: 1
  { name: bar, position: 3 }, // => position: 2
  { name: baz, position: 4 }, // => position: 3
}]
```

I'm thinking that a combination of `map`, `set` and `extend` can help me with doing so, but the key here is the `index` of each item. Isn't that supposed to be the second param of iteratee function?

```js
import { map, flow } from 'lodash/fp';

 // this doesn't work. position values are always null
const updatePosition = map((each, i) => ({ ...each, position: i + 1 }));

// I tried calling updatePosition directly as well, but I had the same issue
const getNewArray = flow(doSomeOtherStuff, updatePosition);

getNewArray(oldArray);

/*
[
  { name: foo, position: null },
  { name: bar, position: null },
  { name: baz, position: null }
}]
*/
```

**Comment by jdalton** [comment]
Hi @wsmd!

This [is by design](https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments).
You can customize the behavior with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).

**Comment by wsmd** [comment]
Thanks @jdalton!

That makes perfect sense! I really should've read the documentation carefully rather than skimming through it.

![](https://m.popkey.co/ff876e/dd1R.gif)

**Comment by seantanly** [comment]
Hi @jdalton,

Seems that this is a common problem. Is there a idiomatic way of solving it, instead of customizing `map` via convert, breaking it's support for https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments ?

One solution is to make the requirements for iteratee argument *explicit*, i.e. introducing functions such as `mapWithIndex` that expects iteratee arguments `(value, index)`.  With this, both use cases are properly covered and there won't be any ambiguity.
