### ISSUE TITLE
Don't drop node 0.10 and 0.12 support 

### ISSUE THREAD

**Issue by phated** [lodash/lodash#2695]
Figured I should open an issue about this. As @seldo said on Twitter, it's probably wise to keep supporting 0.10 and 0.12 for around a year.

**Comment by jdalton** [comment]
Thanks for bringing this up!

We'll likely drop support for [v5](https://github.com/lodash/lodash/wiki/Roadmap#v500-2017) when released in mid Jan 2017. By then usage of 0.10 and 0.12 will likely be less than 10%.

As you know adoption of a major versions takes time (around 9 months to surpass the adoption of the previous version). Since it's a slow build it will align nicely with the fall of 0.10 and 0.12.
