### ISSUE TITLE
[fp enhancement] converge

### ISSUE THREAD

**Issue by Andarist** [lodash/lodash#2759]
Im curious if there is a possibility of adding a method like - http://ramdajs.com/docs/#converge . I find it really useful for complex data transformations, especially in pair with http://ramdajs.com/docs/#call .

Also lenses are a big topic for me, is there any plan of supporting such methods in the future?

In addition I would like to ask what are the plans for the fp port. Will it stay as just a port of regular lodash methods + some aliases? Will there be more methods added which satisfies fp style beside regular lodash? In general - whats on the roadmap?

Thanks for a great lib!

**Comment by jdalton** [comment]
Hi @Andarist!

When I started the FP wrapper I thought about adding a `converge` equiv.
I ended up adding a `useWith` equiv [_.overArgs](https://lodash.com/docs/#overArgs). Later I added [_.over](https://lodash.com/docs/#over). I got it into my head that `converge` could be created through composition but I have since forgotten. Lenses are something I'm thinking about for sure.

**Comment by Andarist** [comment]
For now I've implemented `converge` on my own. I'll leave it here, maybe somebody will find it useful 

`export const converge = overArgs(compose, [spread, over])`

**Comment by jdalton** [comment]
Yeah! Thanks @Andarist, I knew it was composable!

**Comment by StreetStrider** [comment]
@Andarist 
> Conjuration increased to 68

**Comment by FranzSkuffka** [comment]
Does anyone have a test for this?

**Comment by Andarist** [comment]
@FranzSkuffka Some tests from [here](https://github.com/ramda/ramda/blob/master/test/converge.js) could be used for this.

**Comment by FranzSkuffka** [comment]
Cool. I now used this here :)
```
  test('converge', () => {
    expect(converge(concat, [head, last])([1, 2, 3])).toEqual([1, 3])
```
