### ISSUE TITLE
isFunction() fails on async function

### ISSUE THREAD

**Issue by leebenson** [lodash/lodash#2768]
Node 7, running with `--harmony-async-await`:

```js
const _ = require('lodash');
async function test() {}

console.log('is function?', _.isFunction(test));
```

**Expected:** true

**Actual:** false

**Comment by jdalton** [comment]
Thanks! Patched https://github.com/lodash/lodash/commit/95bc54a3ddc7a25f5e134f5b376a0d1d96118f49.

**Comment by mikermcneil** [comment]
@jdalton like greased ⚡️ 

Are you open to doing a hotfix for this in 3.x so we can use it in Sails?  Happy to take care of some or all of the necessary work personally.

A bit of background on this:  I love lodash... a lot!  And we use it literally all over the place.  Specifically, we use Lodash 3.x in Sails, purely out of habit and for stylistic reasons.  In Sails v1.0, we're taking steps to make it much easier for new users to choose their own lodash version in new Sails apps.  That said, within Sails, I intend to keep us on lodash 3.x for the immediate term (again, just because I have a weird personal preference for the way some of its functions are implemented. )




-------

btw: I tried to double check that there wasn't already a 3.x patch, and got a little bit confused:

![image](https://cloud.githubusercontent.com/assets/618009/19791832/6a05b76a-9c8a-11e6-82c7-86e882323f4c.png)

But `npm show` doesn't surface them, so I'm guessing those were internal, yeah?

Anyway, happy to help in any way I can, just point me in the right direction.

Thanks!

**Comment by jdalton** [comment]
Hi @mikermcneil!

We usually don't back port fixes unless it's an emergency, something like actively borking user packages.

You're looking at the `npm-packages` tags which don't necessarily align with the monolithic package release. The [npm-packages](https://github.com/lodash/lodash/tree/3.10.2-npm-packages) is a tag for the per method packages. In [this case](https://github.com/lodash/lodash/commit/1ba6d6cc9518754f9be99ed63d88ffec33a1a655) it's for the `lodash.ceil`, `lodash.floor`, and `lodash.round` packages.

**Comment by mikermcneil** [comment]
@jdalton fair enough, appreciate the quick reply. For the time being I'll go ahead and fix on a fork and use that in sails. For Sails v1, will probably just auto-install Lodash 4 for newly generated apps- that way, folks can just look at the latest Lodash docs. And meanwhile, we'll still be able to use lodash 3 in sails internally.

(I'll follow up with a link to the unofficial 3.10.2 package when we publish.)

Thanks again!

**Comment by jdalton** [comment]
@mikermcneil
Have you looked at [scoped packages](https://docs.npmjs.com/misc/scope)?
Something like `sails@lodash` would be a nice way to handle it.

**Comment by mikermcneil** [comment]
@jdalton read my mind- exactly what we're planning on doing, except w/ a different scope (b/c apparently we have a squatter).  That's for the internal one in core-- for the lodash SVR we inject in new Sails apps, I'll go ahead and bump that to the latest lodash@4.x.x.   I think there'll be a little bit of confusion due to SO questions and tutorials w/ old usage, but that'll work itself out with time.

**Comment by jdalton** [comment]
If it's a legit squatter you can ping npm support, `support@npmjs.com`, and they can help resolve it.

**Comment by mikermcneil** [comment]
thanks, will do

**Comment by mikermcneil** [comment]
@jdalton no luck with the unsquatting :/

But!  Good news is that your patch is now rebased [onto 3.10.x](https://github.com/treelinehq/lodash/commits/master), and published as v3.10.2 of [`@sailshq/lodash`](https://www.npmjs.com/package/@sailshq/lodash).

Thanks again for the help!

-- 


If anyone else is using lodash@3.10.1 and needs this, feel free to use it.  I'm sure at some point we'll switch some of our core packages over to use an updated version of Lodash, but I plan on keeping this on NPM and patching anything major that comes along for at least a couple more years.  

> Note that this uses a single-file build of lodash to make the `npm install` faster:
![image](https://cloud.githubusercontent.com/assets/618009/19992156/767dbb76-a209-11e6-9c23-4458f670b14d.png).  This was important to us because it's likely to get installed alongside other lodashes, including caolan/async's lodash v4 dep, and the 3.10.1 dep from some of our other packages.  It probably won't affect you, unless you were doing any weird requires.  
> 
> I disabled issues in the repo (b/c I would forget to check them) -- so if you run into a problem with @sailshq/lodash, or find any other sort of major bug on Lodash 3.10.x, please let me know via `http://sailsjs.com/bugs` (aka the issue tracker of the main sails repo on Github)

**Comment by wouter-vdb** [comment]
This problem still exists for `lodash.isfunction` v3.0.8. The above fix was not applied on this separate package. Is this by design?

**Comment by jdalton** [comment]
> Is this by design?

@wouter-vdb No. I'll see about bumping it.
