### ISSUE TITLE
fp.mergeAllWith ignores customizer when sources array has length > 2

### ISSUE THREAD

**Issue by implausible** [lodash/lodash#2786]
```javascript
var other = [{ 'a': 3, 'b': 4 }, {'a': 5 }];
fp.mergeAllWith(console.log.bind(console), other); // logs to the console

other = [{ 'a': 3, 'b': 4 }, {'a': 5, 'b': 2}, {'a':7, 'b': 12}];
fp.mergeAllWith(console.log.bind(console), other); // doesn't log to the console
```

It seems to be running the normal fp.mergeAll for the second case. Am I doing this wrong or is this a bug?

**Comment by Andarist** [comment]
I've debugged it for a little for fun and I think part of the bug lies here - https://github.com/lodash/lodash/blob/92359257c1f566b655a417498086e145e4e3db1c/fp/_mapping.js#L186

According to the doscs signature of regular `mergeWith` is - `_.mergeWith(object, ...sources, customizer)`, because of `sources` being spreaded *and* in the middle arguments cannot be simply reordered with highlighted order of `[1, 2, 0]`. Using that order when called as such
- `fp.mergeAllWith(fn, [a, b, c])` it has its arguments effectively under the hood rearranged to `a, b, fn, c`, then spreaded or smth else again etc and effectively `c` and `customizer` (`fn` here) becomes neglected - leading to a bug

**Comment by Andarist** [comment]
In attempt to fix this, I've discovered that this is in matter of fact much bigger bug. It affects all (possibly, didnt check *all* of them, but the pattern is the same) methods of the `AllWith` kind which has spreaded args in the middle in their lodash equivalent, such as - `assignAllWith`, etc.

@jdalton 
I could fix it, if you provide some guidance on the best way to as this is completely new problem to tackle in the converting scenario and Im not sure on which level of it you would like to have it solved.
