### ISSUE TITLE
Breaking change between 4.16.5 and 4.17.0

### ISSUE THREAD

**Issue by felixfbecker** [lodash/lodash#2810]
Updating lodash makes tests fail in Sequelize.
https://github.com/sequelize/sequelize/pull/6849
https://travis-ci.org/sequelize/sequelize/jobs/175630416#L2244

I cannot find the exact cause, but somewhere our UUID attribute is not converted to a string correctly anymore. While debugging it seemed it was related to an object losing its prototype chain (was class instance before, is plain object now). Maybe there was a behavior change, for example in `_.clone`?

**Comment by larrydahooster** [comment]
Updating to 4.17.0 broke my App as well and caused the browser to freeze. I didn't had the time to dig into it yet as I am using several lodash functions so I just rolled back to 4.16.5.

**Comment by suprMax** [comment]
Can confirm, same problem. Seems like it's caused by recent `omit` update. Can't trace deeper, browser just crashes. Seems like problem occurs only if a lot of operations are run at the same time. Probably some of the changes were too CPU expensive.

**Comment by bangbang93** [comment]
babel-preset-es2015@6.9.0 › babel-plugin-transform-es2015-block-scoping@6.18.0 › lodash@4.17.0
Same, CPU 100% and node application cannot start up.
node 4.4.3 and node 7.1.0

**Comment by jdalton** [comment]
@felixfbecker Thanks for the heads up. Relying on inheritance from a method like `_.omit` is tricky. Traditionally `_.omit` would create an object that flattened inheritance onto an object with the specified properties omitted from the result. By adding deep path support to `_.omit` it means that not only not the root result object flattened but also deep ones too. It also means things are a [bit heavier](https://github.com/lodash/lodash/issues/2812) (@larrydahooster). Instead of flattening we could do what `_.cloneDeep` does and preserve inheritance (https://github.com/lodash/lodash/commit/f823fe478d1b1be14e5dd9228bac6a54529982f1). Can you try the latest master copy of `lodash.js` in repo root to see if that resolves your issue.

**Comment by arcanis** [comment]
@jdalton A few notes (I might not have all the story, so feel free to correct me):

Shouldn't this change have been made in a major release? You've got 5 issues before the doc website even finished being updated, which show how breaking this change is. We pulled our hairs off with a coworker, wondering why our app was completely broken - until we start questioning Lodash itself.

Why should `omit` be a deep operation, especially if it both breaks things and makes them a lot slower due to the recursion? Shouldn't the deep behaviour be moved into a separate function, or maybe kept into the same one but only when required?

**Comment by jdalton** [comment]
I just updated last night @arcanis. I've resolved most of the issues. I'm trying to see if this is a nice compromise. So I'll keep removing off-topic issues until then.

**Comment by arcanis** [comment]
> You might give the master repo lodash a try to see if that resolves your issue.

It doesn't. The issue isn't that much about the inheritance, but rather that the references aren't preserved after an `omit` call, like they previously were.

**Comment by felixfbecker** [comment]
With all these issues popping up (inheritance, references, performance, unintended interpretation of dots) please consider reverting `omit()` to the simple behavior before and add this as a new method like `omitDeep()`, just like `cloneDeep()`. This allows us to opt-in into the feature if we want it, because currently there is no way to opt-out for example if you actually need to omit keys with dots inside. Just imagine a hash of file names as keys.

**Comment by jdalton** [comment]
Cool. I'll keep tweaking.

**Comment by jdalton** [comment]
I believe I've [address this issue and the perf issue](https://github.com/lodash/lodash/commit/6c427b7a260183685b16d2624351529cda25ce81) by avoiding a deep clone for the common case.

**Comment by jdalton** [comment]
I'll have a v4.17.1 out sometime today.
