### ISSUE TITLE
lodash/fp _.remove fails to remove item from array (and returns wrong result)

### ISSUE THREAD

**Issue by anodynos** [lodash/lodash#2847]
```
const _ = require('lodash');
var arr;

arr = [1,2,3];
console.log(
  _.remove(arr, (it) => it === 1)
);
// [ 1 ] // correct
console.log(arr);
// [ 2, 3 ] // correct


// lodash/fp fails
const _f = require('lodash/fp');
arr = [1,2,3];
console.log(
  _f.remove((it) => it === 1)(arr)
);
// [ 2, 3 ] // WRONG, returns the wrong array of removed items

console.log(arr);
// [ 1, 2, 3 ] // WRONG, hasn't removed any item at all
```

**Comment by jdalton** [comment]
Hi @anodynos!

The fp methods are immutable by default. You can change this with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).

**Comment by anodynos** [comment]
Hi @jdalton 

This is _not_ obvious at all from the docs https://github.com/lodash/lodash/wiki/FP-Guide.

Also, it completely changes the meaning & signature of the words we use as a vocabulary (eg `remove` in this case). 

Sure, immutability is great but it should be left to the developer to decide whether they want to use a `_.filter` or `_.remove`, and those keywords should be consistent among the two styles. 

Regards.

**Comment by jdalton** [comment]
The FP guide does cover immutability and how to customize it.
Though `remove` is immutable it still returns a new object with the chosen values removed.

**Comment by robinpokorny** [comment]
Just discovered this myself when rewriting some code to FP.

The problem is that (non-FP) `_.remove` actually has two results: the array is mutated and it returns removed elements.

`fp.remove` does only one thing: returns array without some elements. In this, it is equal to `fp.filter` (with negated predicate).

If anything, the confusing one is actually the non-FP version.
