### ISSUE TITLE
why not the 'baseslice' func use Array.slice(), loop faster than slice?

### ISSUE THREAD

**Issue by Robin-front** [lodash/lodash#2850]
https://github.com/lodash/lodash/blob/master/lodash.js#L4074

baseslice: user loop

```javascript
var result = Array(length);
  while (++index < length) {
    result[index] = array[index + start];
  }
  return result;
```

why not use slice:

```javascript
return array.slice(start, end);
```

i test the performance of both in chrome\firefox\safari,  slice always faster than loop.

and this is QA in the stackoverflow:[http://stackoverflow.com/questions/3978492/javascript-fastest-way-to-duplicate-an-array-slice-vs-for-loop](http://stackoverflow.com/questions/3978492/javascript-fastest-way-to-duplicate-an-array-slice-vs-for-loop)
Did I get it wrong?

**Comment by jdalton** [comment]
@Robin-front 

The perf wins of `Array#slice` vs `baseSlice` depends on the size of the array. That is a minor point though as the perf of that method is not likely going to be an issue. The reason we use `baseSlice` is because we treat arrays as dense while `Array#slice` will respect sparse arrays.
