### ISSUE TITLE
Entry point in v5.0.0

### ISSUE THREAD

**Issue by billyjanitsch** [lodash/lodash#2931]
Another v5 question. :)

I'm really excited for the removal of the monolith entry point and separate method packages -- it was always a pain to have some dependencies import from "lodash", others from "lodash/x", and still others from "lodash.x", unnecessarily ~tripling the amount of Lodash being loaded.

However, will there be an entry point which simply re-exports all of the modules? I'd love to be able to `import {map, reduce} from 'lodash'` _without_ using babel-plugin-lodash (recognizing that I'm bringing in the entire bundle by doing so).

**Comment by jdalton** [comment]
@billyjanitsch thanks for asking I :heart: the questions!

There will be no entry point. From a node and web standpoint loading in hundreds of modules on the fly isn't very speedy. And since Lodash is a lower level dep, slow downs in it, can impact lots of other packages. With Lodash v5 I'm also working on reducing the overall package size. My goal is to cut the size by more thank 50%.

I'll be deferring more (monolithic syntxc, chaining, iteratee shorthands) to babel-plugin-lodash since babel has become so ingrained in the modern developer workflow. This gives us the flexibility for folks to opt-in to features while keeping the package light.

**Comment by billyjanitsch** [comment]
I understand your perspective. The single entry would definitely be slower to load (though it would barely add to package size -- just one line re-exporting each method); I'm not suggesting it be recommended for packages or apps.

I'm thinking of the use case where you're tinkering with a small local project that doesn't use babel, and have to choose between (1) bringing in babel just for lodash and (2) very verbose imports:
```js
import map from 'lodash/map'
import reduce from 'lodash/reduce'
import filter from 'lodash/filter'
// ...
```

Note that babel itself loads in hundreds of its own modules in a typical set up -- it's not terribly efficient but module loading in recent node versions has gotten so performant that it's barely noticeable. When bundling and/or using most of lodash anyway, I'd gladly take the convenience over the slight slowdown.

Appreciate the consideration, whatever you decide.

**Comment by jdalton** [comment]
With a major bump I want to try to push harder for the less is more approach as things can always be added later (it's easier to add then to take away once the release is cut). If you're using `import` then you're likely using babel as Node doesn't support that out of the box. 
Babel isn't a runtime cost though. And in our case it's an optional cost for folks that want the monolithic syntax.

**Comment by refack** [comment]
Did you do a write-up about the how? It's time for me to tree-factor `lodash-contrib` and I want to mimic your strategy. Also if you have any "garbage" you can flout it downstream to me.

**Comment by jdalton** [comment]
Work on Lodash v5 is still too early for that.
