### ISSUE TITLE
Issue with __proto__ properties using defaultsDeep

### ISSUE THREAD

**Issue by mallocator** [lodash/lodash#2937]
There seems to be an issue with applying properties to the __proto__ object when using defaultsDeep:

```Javascript
const expect = require('chai').expect;

let copy = require('lodash/defaultsDeep');
let obj1 = {};
obj1.__proto__.prop = { val1: 1 };
let obj2 = {};
obj1.__proto__.val2 = 2;
expect(copy(obj1, obj2).prop.val2).to.be.undefined;
```

Is this an intended/known issue?

**Comment by jdalton** [comment]
Hi @mallocator!

In this case `defaultsDeep` isn't touching the `__proto__` stuff because it's their on the destination object and your source is an empty object. So basically nothing is being applied and your `__proto__` is as you initially defined them.

**Comment by mallocator** [comment]
maybe I'm not to clear on the __proto__ chain, but shouldn't val2 be only available on the original object ```obj1.val2```, not ```obj.prop.val2```.
Why is val2 available on the nested object?

**Comment by jdalton** [comment]
The `defaultsDeep` method mutates and returns the destination object (the first object).

**Comment by mallocator** [comment]
that still doesn't explain how val2 is available in prop

**Comment by jdalton** [comment]
`__proto__` is a [special property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto). You're essentially add a `prop` property to the `[[Prototype]]` of `obj1`, which is `Object.prototype`. You're then adding a `val2` property to it as well. Since all objects inherit from `Object.prototype` you'll see it on the lookup of
`obj1.prop.val2`. This happens without Lodash.

```js
let obj1 = {};
obj1.__proto__.prop = { val1: 1 };
let obj2 = {};
obj1.__proto__.val2 = 2;
// obj1.prop.val2 // 2;
```

**Comment by mallocator** [comment]
Cool, thanks for the explanation.
