### ISSUE TITLE
Lodash FP map doesn't take index as second argument

### ISSUE THREAD

**Issue by nojaf** [lodash/lodash#2954]
I was expecting to see the ```1,2,3``` in the following fiddle:

https://jsfiddle.net/bdjq1doq/
Is this expected behavior?

**Comment by jfmengels** [comment]
Hi @nojaf!

This is expected behaviour, as detailed [here](https://github.com/lodash/lodash/wiki/FP-Guide#capped-iteratee-arguments). This is to avoid unexpected behavior with iteratees that take multiple parameters.
You can customize the behavior with [convert](https://github.com/lodash/lodash/wiki/FP-Guide#convert).
