### ISSUE TITLE
Skip undefined object with _.mergeWith

### ISSUE THREAD

**Issue by marc-antoinepelletier** [lodash/lodash#2966]
Hi,

I have two object like this :

```javascript
     var obj1 = {
        test1: { a: 21, b: 42 },
        test2: { c: 113, d: 431 }
      };

var obj2 = {
        test1: { a: 1, b: 2 }
      };
```

And I wanted to have this result : 

`      var newObj = {
        test1: { a: 21, b: 42 }
      };`

I need to keep the original value from obj1, but only keep the one present in obj2.

I have done something like this : 

```javascript
var customizer = function(objValue, srcValue) {
        if (!_.isUndefined(objValue)) {
          return srcValue;
        } else {
          return null; // I need to not return anything and skip to the next srcValue
        }
      };
_.mergeWith(obj2, obj1, customizer);
```

Is it possible to do so using `_.mergeWith` ?
My example will return a null value for the item that should be remove from the object, but I want to get rid of it at all.

**Comment by jdalton** [comment]
Hi @marc-antoinepelletier!

The merge modules won't delete properties. You'll have to perform another process for that.

**Comment by samal84** [comment]
You can do it like this:
```
_.mergeWith(
    destination,
    source,
    (objValue, srcValue, key) => {
        if (srcValue == null) {
            _.unset(destination, key);
        }
    }
);
```

**Comment by PazzaVlad** [comment]
@samal84 it will only work for flat objects

**Comment by samal84** [comment]
Right you are. I was just assuming that the key was a deep key.

**Comment by dmitryt** [comment]
> @samal84 it will only work for flat objects

https://github.com/lodash/lodash/blob/master/.internal/baseMerge.js#L30
Probably, it's possible to do it in a little bit different way:
```
_.mergeWith(
    destination,
    source,
    (objValue, srcValue, key, object) => {
        if (srcValue == null) {
            _.unset(object, key);
        }
    }
);
```
But I'm not sure whether it's a good idea to mutate intermediate objects. Just FYI

**Comment by carlgieringer** [comment]
@dmitryt I don't see that it works: https://codepen.io/anon/pen/JeozLm?editors=0010#0

Looking at the code you referenced, that makes sense, because the call to `assignMergeValue` happens after the `customizer` runs.  So even if we unset the value in the `customizer`, the `assignMergeValue` will assign a value to that key.  (Also, your example returns no value from your `customizer`, which is equivalent to returning `undefined`.  Per the [docs](https://lodash.com/docs/4.17.10#mergeWith), this causes lodash to use the default behavior of merging the `srcValue` of `null`.)

**Comment by carlgieringer** [comment]
One option is to do the `_.mergeWith` followed by some sort of `omit`: https://stackoverflow.com/a/53164118/39396
