### ISSUE TITLE
Update modularized packages in npm

### ISSUE THREAD

**Issue by dy-dx** [lodash/lodash#2969]
Most of the modularized packages seem to be out of date. 

While debugging a memory leak, I found that one of my dependencies has a dependency on `"lodash.has": "^4.3.1"` -- but npm only has [v4.5.2](https://www.npmjs.com/package/lodash.has).

It would be really nice if the latest version of lodash.has (with the memoize cache limit) could be released to npm. Thank you!

**Comment by jdalton** [comment]
Hi @dy-dx!

Update of the modularized packages as fallen a bit behind because it's such a pain to mess with. So much in fact that after the next release there will be no more modularized package updates (they're being scrapped for v5). I'll try to update them for their last round this weekend but no promises. Ideally you'd be using `lodash/has` instead.

**Comment by naugtur** [comment]
Looks like you guys need to talk to @janl - the author of "Kill all humans..."
https://www.youtube.com/watch?v=ZXyx_1kN1L8
