### ISSUE TITLE
Calling a curried function with no parameters does not register as a call

### ISSUE THREAD

**Issue by frozegnome** [lodash/lodash#3020]
When trying to call a curried function with a fixed number of parameters I've found that when dealing with the last argument if I try to call the function without providing a parameter I am simply returned the identity of the function I am currying. However, providing `undefined` or `null` behaves as expected.

``` javascript
let foo = _.curry(x => 5, 2);

foo(4)(null); //  5
foo(4)();     //  x => 5
```

Is this the intended behavior here? Any insight would be appreciated.

**Comment by jdalton** [comment]
Hi @frozegnome!

Yes, this is the intended behavior. When and when not to return a curried function is determined by how many arguments the curried function has received. Since you're invoking it with zero arguments it doesn't count towards the target count.

**Comment by frozegnome** [comment]
Thanks for the quick reply @jdalton 

If I may ask, what is the reasoning behind this functionality? I certainly see how it would simplify the implementation, but I'm not sure how it is helpful as an API. I feel like it goes against how JavaScript libraries typically behave.

**Comment by jdalton** [comment]
This is the common behavior of curried functions. We followed the established behavior when implementing currying.

**Comment by danielo515** [comment]
I was about to open a new issue, but then I found this one, so here is my original text

First of all, thanks for lodash
Today, trying to make some testing I almost became mad because my tests were not executing properly. I blamed node, my testing tool and my testing environment. Then  I realized the problem was with `lodash.curry`. 

 I can accept that this is the intended behavior, but not a single line in the documentation mentions the behavior I have discovered.

Here is a small snippet you can test on any REPL

```js
const x = curry((a,b,c) => console.log(a,b,c))
x()('b')('c')()()()()('a')
const y = curry((a,b,c) => console.log(a,b,c),3)
y()('b')('c')()()()('x')
```
As you can see I can call  `x` and `y` as many times as I want if I don't provide an argument. My expectation is that, if the function takes three parameters, the curried function is executed after being invoked 3 times.

Functions communicate their arity with the length property, so curry can easily track function invocations and compare them with the arity. 
Maybe I can accept that behavior on curry, but the I want to have an escape hatch on `curryN` (shortand I'll use for `curry(fn,arity)`), but that is not the case.

Imagine that I have a curried function that takes an optional parameter, I can't use ES6 defaults because then curry will not work, so I try to check default inside the function.

```js
const x = curry((a,b,c) => {
a = a || 'default'
console.log(a,b,c)
})
```
This will not work either because I'll be forced to call the function like this

```js
//not working
x()('b','c')
// works
x(null)('b','c')
```
As I said, I can accept this behavior for curry, but not for `curryN`.
And even if you want to keep it the way it is, please document this particular behavior on the documentation.

Regards

**Comment by dwiyatci** [comment]
I've got to admit that this is quite a bit surprising for me, too. 😮 ⚡️ 

@jdalton So this behavior below is also intended when using lodash `curry`, right?

```
const curried1 = a => b => fun(a, b);
const curried2 = _.curry(fun);

curried1(1)(); // 4
curried2(1)(); // TypeError: curried2(...) is not a function

function fun(a, b = 3) {
  return a + b;
}
```

**Comment by danielo515** [comment]
Sadly yes. Default parameter are not reported has part of the function length, so your `fun` function is being treated as a function with an arity of 1
