### ISSUE TITLE
Local copies of setTimeout/clearTimeout break sinon.js tests

### ISSUE THREAD

**Issue by avaly** [lodash/lodash#304]
Using [sinon.js](http://sinonjs.org/) to run tests with fake timers turns out to break if you load lodash before you trigger `sinon.useFakeTimers`. Sinon swaps the global timer methods with its fake versions, but lodash keeps the original ones in its closure.

**Comment by NiGhTTraX** [comment]
@jdalton Using `runInContext` is not a viable solution when working with modules. You can't replace the lodash instance inside the module under test without resorting to module mocking utilities that are pretty cumbersome to use (especially when coupled with Browserify).

Mocking `_.debounce` is not very elegant since lodash is a 3rd party lib (that is strictly an implementation detail) which I can't control and don't want to maintain mocks of its API. My tests shouldn't care that the code under test uses `_.debounce` or custom `setTimeout` calls. All they need to care about is that if the clock advances a certain interval then an effect can be observed.

What is the need for keeping references to these global methods anyway?

**Comment by jdalton** [comment]
If possible load your mocks before lodash is loaded. I like our approach of grabbing a reference early because it helps guard against tampering and works well with `runInContext` (our doc example shows replacing `setTimeout` with `setImmediate` in Node). If you're using browserify you may be able to use [aliasify](https://www.npmjs.com/package/aliasify) to assist in mocking modules like `debounce`.

**Comment by NiGhTTraX** [comment]
> If possible load your mocks before lodash is loaded.

That would work the first time the module is loaded, but then the module will be cached and whatever references it grabbed will persist between tests. Moreover, it's not elegant to mock 3rd party code for the reasons I outlined above.

**Comment by jdalton** [comment]
You can load a fresh instance of a module by emptying the `require.cache` object.

**Comment by NiGhTTraX** [comment]
That doesn't work in Browserify because the `require` method doesn't expose the `cache` dict. And plus, I'm leaking way too much implementation details in my unit tests.

> I like our approach of grabbing a reference early because it helps guard against tampering

Can you elaborate on a case where it's helpful for lodash to protect you? Maybe it's not the responsibility of lodash to care about how other libs integrate with it?

**Comment by jdalton** [comment]
> Can you elaborate on a case where it's helpful for lodash to protect you?

Underscore was used by a service that injected comments and feedback into a page. They ran into issues with Underscore and Prototype being used on a page because Underscore at the time would use whatever was on `Array.prototype.reduce` which turned out to be invalid with that old version of Prototype. The devs switched to lodash and things just worked. I'd like to keep that up.

In your case mock whatever abstraction you need or don't. I have a combo of mocked and unmocked timing tests which are reliable enough because I have retry logic built in. I've gone farther than most providing `runInContext` and suggestions for solving your issue but I'm not going to sacrifice stability in lodash for your manufactured and avoidable situation.

**Comment by micha149** [comment]
Would it be suitable to add a function wich disables use of the cached functions in lodash? We need to test code which makes use of `_.debounce` in a ES6 project. So, a function like `_.runInContext` makes no sense unless it would change the context of the current lodash instance instead of returning an new one…

**Comment by jdalton** [comment]
@micha149 You could create a module which loads lodash pre-mocked and module swap with your bundler.
```js
import _ from 'lodash';
let mock = _.runInContext({ ... });
export default mock;
```

**Comment by dallonf** [comment]
@jdalton I'm running into the same issue. Unfortunately `runInContext` still isn't a solution for module-based environments, even when mocking lodash, because sinon's fake timers is designed to be added and removed as needed:

```
it("should work", function() {
  var clock = sinon.useFakeTimers();
  try {
    callSomethingThatInTurnCallsDebounce();
    clock.tick();
    expect(something).toHaveHappened();
  } finally {
    clock.restore();
  }
});
```
Unless I'm mistaken, a mock lodash would still cache relevant globals from the first time it was loaded. Clearing the cache is not an option, because that's not possible in bundlers like Webpack or Browserify (they effectively _are_ the cache). I seem to be left without a way to make this work.

**Comment by jdalton** [comment]
> I seem to be left without a way to make this work.

Yep.

**Comment by dallonf** [comment]
So... uh... would you accept a PR?

**Comment by jdalton** [comment]
I've given plenty of options. Maybe hacking lodash isn't the level at which you should be mocking. Move up the abstraction to the APIs of your application.

**Comment by bruceharris** [comment]
@dallonf I ran into the same as well; dealt with it by extracting the debounce timeout period as a constant which is injected as a dependency into the implementation code. The test code in turn injects a 0 into the unit under test so the debounced function executes on the next tick when it's being tested.

`
beforeEach(function() {
  // mock out the debounce period constant, substitute a 0
});

it("should work", function(done) {
    callSomethingThatInTurnCallsDebounce();
    setTimeout(function() {
        expect(something).toHaveHappened();
        done();
    }, 0);
});
`

**Comment by micha149** [comment]
@bruceharris @dallonf I think thats is not the way you should test and abstract your code. Lodash is not an instance what you inject typically. I think what you test is something like „method X will only called once if button is clicked 5 times” and you do not care about the implementation which uses lodash. So, your test looks a bit like „click() click() click() letTimeGoBy() click(), assert spy was called once“. And this is currently hard…

@jdalton I think this is not hacking on lodash. I will called it „Lets increase the testability or test support”
