### ISSUE TITLE
Leaking global

### ISSUE THREAD

**Issue by Vanuan** [lodash/lodash#3052]
As described in https://github.com/webpack/webpack/issues/4465, lodash assigns itself to `window` when compiled using webpack.

While a workaround is to switch to `lodash-es` and alias `lodash`, IMHO this should fixed in lodash.

**Comment by jdalton** [comment]
Webpack is doing a source transform replacing our AMD check with `if (true)`. This looks like a webpack issue. I'll continue the discussion on their end.

**Comment by Vanuan** [comment]
![finger-pointing-o](https://cloud.githubusercontent.com/assets/361985/23821506/f41173ec-063c-11e7-8551-28deee98e66b.gif)

**Comment by Vanuan** [comment]
BTW, what about AMD case? What if I opened the same issue about loading using RequireJS? Would you also close it as invalid?

E.g. I want to load 2 different versions of lodash using requireJS: one using `window` and another using `define`.

**Comment by jdalton** [comment]
It turns out this issue is due to a Webpack transform [that's catered to end users and not libraries](https://github.com/webpack/webpack/issues/4465#issuecomment-285850829), like Lodash, that have AMD support. For the time being, Webpack recommends [opting-out of their AMD parsing](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512) if you're running into issues.
