### ISSUE TITLE
_.get(obj, [])

### ISSUE THREAD

**Issue by mathHeadInClouds** [lodash/lodash#3115]
why on earth does that not return obj? Seems very illogical to me.

Reason:

the equation
```js
_.get(_.get(obj, arr.slice(0,-k)), arr.slice(-k)) === _.get(obj, arr)
```
in the current implementation is `true` for `1 <= k <= arr.length-1`

if `_.get(obj, [])` were properly defined, it would be true for `1 <= k <= arr.length`

A good definition is a definition making "nice laws" as the above as universally true as possible.

Think of the power law as an analogue.

Not defining `_.get(obj, []) = obj` is as illogical as not defining that a number to the power of zero is one.

**Comment by jdalton** [comment]
Dup of #3049.

The method is defined in a way that it's "get something from object". If you don't provide a path then it's "get nothing from object".

**Comment by mathHeadInClouds** [comment]
[] _is_ a path. Of length zero. Like "/" is a file path of length zero. "Drilling down" a file path, or drilling down into an object is like going into a building, entering doors. If you have entered zero doors, you're standing in front of the building.

It is absolutely certain that more people will complain about this nonsense in the future.

**Comment by jdalton** [comment]
>  "Drilling down" a file path, or drilling down into an object is like going into a building, entering doors. If you have entered zero doors, you're standing in front of the building.

Naw. I've already made it super clear this a property selector. A property selector will not return the parent object. It is to select properties of the object. This also makes the behavior between string and path array consistent since there would be no way to specify returning the parent from the string path. The string path `''` is seen as requesting the property `''` or an array path of `['']`.
