### ISSUE TITLE
Lodash in web workers.

### ISSUE THREAD

**Issue by Fresheyeball** [lodash/lodash#313]
I would like to humbly request extending support for lodash to webworkers as an environment. Currently importing lodash into a web worker crashes to the worker. Unit tests for lodash in web workers would also be keen. Just say'n.

**Comment by sebmck** [comment]
@jdalton Can't seem to get the current lodash build to work in a web worker via browserify. There's no `window` in web workers and `this` refers to the exports. In web workers the global context is `self`. Any ideas?

**Comment by jdalton** [comment]
Which build? You've got to be specific this close to release. Do you mean 2.4.1 or 3.0 and then do you mean AMD modules, Node modules, ES6 modules, or npm packages?

**Comment by sebmck** [comment]
@jdalton Sorry I wasn't more specific. I'm using `2.4.1` with the npm release. I've also tried the `compat` build available in `dist` but that didn't work either.

**Comment by jdalton** [comment]
I believe this [is fixed](https://github.com/lodash/lodash/blob/f40d2cce4f49bc1042fd195f76e1ddb4f89c40d0/lodash.src.js#L275-L279) in our 3.0. You can try pointing to [our 3.0](https://github.com/lodash/lodash/tree/3.0.0-npm) the commit sha is `eae964f408637800804d5fe0215198db93d42a94`.

**Comment by jdalton** [comment]
Related to #458.

**Comment by sebmck** [comment]
@jdalton That does the trick, thanks! I only searched issues instead of pull requests as well. Thanks for the help!

**Comment by eternalko** [comment]
This is probably the most relevant place on internet to share. 
A bug (and a fix) that took me 15+ coffees to figure out.

Safari. There is an issue with Safari when we wrap lodash with webpack in a WebWorker context. 
It doesn't work. `TypeError: undefined is not an object (evaluating 'Array.prototype')`
If we undo all the fancy minifications we will get a line number somewhere around this place:
```js
context = context ? _.defaults(root.Object(), context, _.pick(root, contextProps)) : root;
/** Native constructor references. */
var Array = context.Array,
```

My preliminary findings show, that  Safari 'root' object is not `self`, but `this`. Thanks for keeping up with standards Safari. This renders a problem. Both webpack and lodash try to make things smooth for others and themselves by finding what *the most truthful true* global is.  

*seconds from disaster music plays in the background*

At first webpack, injects a global variable `global` into the scope and wraps lodash. Fine. Next:

```js 
var root = (objectTypes[typeof window] && window !== (this && this.window)) ? window : this;
```
Now, lodash  registers `root` to `this`, that is (I think) an empty Object 2 prototype chains away from null.

Then, lodash tries to figure out a global
```js
 /** Detect free variable `global` from Node.js or Browserified code and use it as `root`. */
var freeGlobal = freeExports && freeModule && typeof global == 'object' && global;
```
and it works. We can confirm it with `throw(Object.getOwnPropertyNames(freeGlobal));`. `console.log` doesn't work in Safari WebWorker context.

Then lodash wants to confirm that freeGlobal is really a global:
```js
if (freeGlobal && (freeGlobal.global === freeGlobal || freeGlobal.window === freeGlobal 
|| freeGlobal.self === freeGlobal) )) {
  root = freeGlobal;
}
```
and this works, since `freeGlobal.self` is an instance of *true global object*. `(freeGlobal.self === freeGlobal) === true`. Both freeGlobal.self and freeGlobal point to the *true global object*. Injected `global` worked as expected. 

But our Safari 'birthday boy' is different: `(freeGlobal.self === freeGlobal) === false`. Boom.
This leaves `root` pointing to something unknown (empty object). 

Mystery solved Scoob!

My trivial solution looks like this:
```js
if (freeGlobal && (freeGlobal.global === freeGlobal || freeGlobal.window === freeGlobal 
|| freeGlobal.self === freeGlobal || freeGlobal.hasOwnProperty('DedicatedWorkerGlobalScope') )) {
  root = freeGlobal;
}
// or
// WorkerGlobalScope
```

**Comment by eternalko** [comment]
A careful reader may ask:
If all this is true, how on earth loadash was working on Safari before 

If we use `importScripts` or copy&paste, at this line:
`var root = (objectTypes[typeof window] && window !== (this && this.window)) ? window : this;`
`this` is pointing to a `true global object` and we assign `root` correctly. And then we skip `trueGlobal` redefinition.

Tadaa.

**Comment by jdalton** [comment]
@eternalko Can you see if `(freeGlobal.self == freeGlobal)`, note the double `==`, is `true` in Safari.

**Comment by eternalko** [comment]
```js

	  throw((1 == 1)); // true
	  throw((1 == '1')); // true
	  throw((1 === '1')); // false
	  throw((freeGlobal.self == freeGlobal)); // false
	  throw((freeGlobal.self === freeGlobal)); // false

	  freeGlobal.self = freeGlobal;
	  throw((freeGlobal.self == freeGlobal)); // true
	  throw((freeGlobal.self === freeGlobal)); // true
```

**Comment by jdalton** [comment]
Fun times.

**Comment by eternalko** [comment]
Indeed. My pleasure!

**Comment by jdalton** [comment]
I'm going to do an `freeGlobal.self instanceof freeGlobal.WorkerGlobalScope` check.

**Comment by eternalko** [comment]
> I'm going to do an freeGlobal.self instanceof freeGlobal.WorkerGlobalScope check.

Oh, that sounds much better than `hasOwnProperty` hackish approach.

When it comes to a fix, according to my tests:
```js
throw(typeof freeGlobal.WorkerGlobalScope === 'function'); //false
throw(typeof freeGlobal.WorkerGlobalScope == 'function'); //false
throw(typeof freeGlobal.WorkerGlobalScope); // object

throw((freeGlobal instanceof freeGlobal.WorkerGlobalScope)); // true
```

Referenced code:
```js
if (freeGlobal && (freeGlobal.global === freeGlobal || freeGlobal.window === freeGlobal 
  || (typeof freeGlobal.WorkerGlobalScope == 'function' 
  && freeGlobal instanceof freeGlobal.WorkerGlobalScope))) {
    root = freeGlobal;
  }
```

**Comment by patrickkettner** [comment]
@jdalton I am hitting the same `TypeError: undefined is not an object (evaluating 'Array.prototype')` inside of a webworker on chrome, on lodash 3.5.0.

For added fun, it only happens when lodash is added as an AMD module with requirejs

**Comment by jdalton** [comment]
@patrickkettner can you create a small step by step repro (I didn't know require.js would work in a web worker, neat).

**Comment by patrickkettner** [comment]
sure, I'll put together a proper gist. But in the mean time, it is basically just this

requireFile.js
```js
  require(['lodash'], function(_) {
    console.log(_);
  })
```

worker.js
```js
  loadScript('require.js', 'requireFile.js')
```

**Comment by patrickkettner** [comment]
@jdalton [here ya go](https://rawgit.com/patrickkettner/765f2ebb05762c88d901/raw/index.html)

**Comment by jdalton** [comment]
Thanks, it looks like the `this` value is that of the xhr request made by requirejs. I could see this as a bug on them but I'll patch.

**Comment by jdalton** [comment]
I [filed a bug](https://github.com/jrburke/r.js/issues/794) on r.js too.

**Comment by patrickkettner** [comment]
awesome - thanks so much @jdalton. Are you planning on patching until their fix? No worries either way, just wondering.

**Comment by jdalton** [comment]
> Are you planning on patching until their fix?

Yep : )

**Comment by patrickkettner** [comment]
You are a beautiful man.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash/commit/afc93257ca7e91af48c0c3a7df92faf59a770305.

**Comment by iggied** [comment]
Same issue discussed but not resolved in https://github.com/lodash/lodash/issues/223

**Comment by trusktr** [comment]
Hey guys, how do you guys import lodash into a worker with Webpack? Can we do something like

```js
import _ from 'lodash'
//...
```

in the worker file, like we can with Browserify's webworkify?

**Comment by patrickkettner** [comment]
Have you tried it?

**Comment by jdalton** [comment]
Hi @trusktr! You might try the webpack support channels.

**Comment by trusktr** [comment]
Ah, it works beautifully.

**Comment by bharatpatil** [comment]
@jdalton I am getting error `Uncaught ReferenceError: _keys3 is not defined` while importing as follows in web worker

`import _keys from '../../../node_modules/lodash/keys';`
