### ISSUE TITLE
Better documentation for lodash/fp

### ISSUE THREAD

**Issue by m-lautenbach** [lodash/lodash#3173]
I really like how `lodash/fp` promotes functional programming.
Unfortunately, the documentation is not very friendly to new users, especially if they are also not that familiar with lodash itself, as it is relative to the 'normal' lodash docu.
This gives me a hard time promoting its usefulness.

Would it be possible to have a stand alone `lodash/fp` documentation, with full descriptions and signatures? Maybe by programmatically merging the two?

**Comment by jdalton** [comment]
I think the level of docs is appropriate.

**Comment by m-lautenbach** [comment]
I understand that you are very busy as a maintainer.
`lodash/fp` though seems to me the closest thing to mainstream functional programming there currently is, at least potentially.
If there is a way some day, I'd be happy to hear about it.

**Comment by jdalton** [comment]
I'd love to see something like a community cook book for it.

**Comment by QuotableWater7** [comment]
+1 on better documentation.  We just switched to ramda solely because of their awesome docs + repl

**Comment by tungv** [comment]
@m-lautenbach, you might want to take a look at this https://gist.github.com/jfmengels/6b973b69c491375117dc

**Comment by LandonSchropp** [comment]
@jdalton I'd also really love to see this. It would be great if there were a simple toggle in the Lodash documentation that would allow me to switch on FP. I know that you mention the rules for converting between the method signatures in the FP guide, but there are a lot to remember and it's not always clear. It would be really nice to quickly look up methods instead.

I personally prefer Lodash to Ramda, but I usually use Ramda because I can quickly look up method signatures.
