### ISSUE TITLE
Request for deep omit (omitDeepBy)

### ISSUE THREAD

**Issue by peteranny** [lodash/lodash#3198]
I would like to make a request for `omitDeepBy`.
Different from shallow `omitBy`, here is the expected behavior:

```
var obj = {
  a: {
    b: {
        c: null,
        d: 123,
    },
    e: null,
  },
  f: null,
};

_.omitDeepBy(obj, _.isNull)
// which returns
// {
//   a: {
//     b: {
//       d: 123,
//     },
//   },
// }
```

I have searched for issues, only to find discussions over "deep" omit w.r.t path, e.g. `_.omit(obj, 'a.b.c')`.
The difference is that `omitDeepBy` is provided a recursive function, but not an explicit known path.

I wonder why there are `cloneDeep`, `defaultsDeep`, `merge`(Deep), but no `omitDeep` (which I need)? Or has it been discussed before?

**Comment by jdalton** [comment]
Hi @peteranny!

In v5 we're removing `omit` to keep things simpler. Omit requires collecting all properties, own, inherited, symbols, and then omitting a handful which isn't the best approach. If possible picking properties is a better and more-to-the-point approach.

**Comment by ephetic** [comment]
(not sure where to put `_.omit` discussion, but this was the most recent place you mentioned its future removal; I can just repost this as a new issue if you'd prefer.)

I'd like to see `_.omit` kept because using `_.pick` in its place may introduce a sort of coupling that `_.omit` avoids -- e.g. some component in the middle of things that only knows that _these_ properties need to be omitted but doesn't need to know what other properties mean or might be added in the future.  

More generally, I use `_.omit` about 6x as often as `_.pick` (just grepped it), so if I had to Sophie's Choice one of them...

Thanks!

**Comment by jdalton** [comment]
Hi @ephetic!

If you need omit I'd suggest simply `delete`ing the properties you don't want.

**Comment by ephetic** [comment]
That would require an explicit (forgettable) clone and n explicit `delete`s, lacking the safety and inlinable terseness of `_.omit`.  Whereas (taking the non-existent other side), replacing `_.pick` with destructuring takes two lines without being significantly less declarative.

**Comment by jdalton** [comment]
`_.omit` isn't a great method. It has to clone everything, walk the inheritance chain, and then exclude certain properties. It's super complex when if you need to omit something there are more straightforward ways to accomplish it.
