### ISSUE TITLE
Update _.isNumber documentation about NaN

### ISSUE THREAD

**Issue by apaatsio** [lodash/lodash#320]
Documentation of `_.isNumber` should have a mention that `NaN` is considered to be a number.

I find it misleading that `_(NaN).isNumber()` is true. Basically that says "not a number is a number".

E.g. `_(parseInt("foo")).isNumber()` equals true.

**Comment by apendua** [comment]
@jdalton Man, it's so misleading. I understand your reasons here, but still "not a number" is not a number, really. I am not telling you that I think the specs of `_.isNumber` should ever change. I am just expressing my confusion here because initially I thought that the routine is a workaround for the well known BUG in JavaScript, i.e. `typeof NaN === "number"`, which is bad m'kay? Yet, it looks like `isNumber` is just an "alias" of that BUG.

**Comment by apendua** [comment]
:+1: For `_.isFinite`.
