### ISSUE TITLE
lodash-es and lodash/fp

### ISSUE THREAD

**Issue by mvanlonden** [lodash/lodash#3247]
Hi! It seems like the fp variety of lodash isn't supported in the `lodash-es` package. Is this intentional? 

I'm using CRA and would like to reduce my bundle size through tree shaking. I've read through this thread https://github.com/facebookincubator/create-react-app/issues/1069 and it seems like the CRA's lodash babel plugin implementation is waiting for lodash v5. Is there still a way to benefit from tree shaking using `lodash/fp` and something like `lodash-es`?

**Comment by jdalton** [comment]
Tree-shaking is a bit of a lie. Tooling tends to be overly sensitive to potential side-effects, of which Lodash has none. I recommend using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) *(it works for `lodash/fp` too) and if you're feeling adventurous combo it with [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) with the `"currying"` feature set enabled.

**Comment by jscinoz** [comment]
Given the main lodash package in NPM uses commonjs-style modules, and tree-shaking requires ES6 modules, babel-plugin-lodash would not be sufficient for proper tree shaking support, as the re-written imports still reference 'lodash', not 'lodash-es'.

Using lodash-webpack-plugin in conjunction with babel-plugin-lodash does reduce the final bundle size further, but there appears to still be significant amounts of unused code that can't be dropped due to the legacy (commonjs) exports/imports.

I've had a look myself at doing a custom build that uses both ES6 modules, and builds the fp-converted functions, but it seems existing tooling (both lodash-cli, and the package.json scripts available on the 4.17.4 tag - no longer present on master) does not support this use case.

**Comment by exarus** [comment]
@jdalton Why should I use `lodash-webpack-plugin` only if I'm feeling adventurous. What should I use if I want to have production-ready solution?
