### ISSUE TITLE
why not move *.js to `src` sub dir?

### ISSUE THREAD

**Issue by lovetingyuan** [lodash/lodash#3275]
why not move *.js to `src` sub dir?

**Comment by jdalton** [comment]
Hi @lovetingyuan!

Lodash will be using [@std/esm](https://github.com/standard-things/esm) (standard esm loader) so there will be no transpiling (no need for a `src` dir) and things will just work.

**Comment by poppinlp** [comment]
@jdalton  Hi.
I think the question is not about what the way lodash build it's modules since there's many ways to make it and i think that has nothing to do with the directory structure.
I think this question is about the directory structure which root directory includes many meta files and maybe sources files should be in a sub directory not be with those meta files.
No offense :)
