### ISSUE TITLE
Supporting Maps and Sets with _.get/_.set and friends

### ISSUE THREAD

**Issue by bradennapier** [lodash/lodash#3331]
Hey There!

  Saw some discussions about supporting iterables and I think your response there makes a lot of sense.  They are easy enough to coerce to standard arrays anyway.

  However, I can see the benefit in supporting, in some fashion, getting (and setting) of map values with the _.get and _.set  and friends. 

  Obviously we can only accept string keys when using the string-style paths, but could even support object and other keys if an array-style path is created instead.

  While maps don't have many of the issues that objects have, it can still be tremendously helpful when working with nested object values.  

```js
const obj = {
  map: new Map([['foo', 'bar'], ['baz', 'qux']]),
};

const foo = _.get(obj, 'map.foo')
_.set(obj, 'map.lux', 'dax')
// or
_.set(obj, [ 'map', { s: 'lux' } ], 'dax')
```

which could also go further 

```js
const obj = {
  map: new Map([['foo', 'bar'], ['baz', 'qux']]),
};

const foo = _.get(obj, 'map.foo')
_.set(obj, 'map.lux',{ val: 'dax' })

const luxVal = _.get(obj, 'map.foo.lux.val')
```

Similarly, it would make sense to handle sets as well for setting them similar to how an array is set/get.

LOVE lodash - Thanks to all that put time into the development!

**Comment by jdalton** [comment]
Hi @bradennapier!

I think is more appropriate for a separate method for maps/sets since they are so different.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by bradennapier** [comment]
@jdalton Yes I can see a separate method for them might make sense, although that method should likely handle both and/or have one that does support both.  Something like `_.setObject` since Arrays, Maps, Sets, and Plain objects are all objects in a sense.

A separate method is also a good idea since technically a Map instance can have properties on it separate from the Map values themselves.

**Comment by ronen-e** [comment]
I would be nice to have a utility method that treats `obj[propName]` same as `map.get(propName)` so that this would work:
```javascript
const innerMap = new Map(['key', 'value']);
const map = new Map(['innerMap', innerMap]);
const obj = {
  innerMap: innerMap
}

_.get(map, ['innerMap', 'key']) // 'value'
_.get(obj, ['innerMap', 'key']) // 'value'
```
The problem is you would get a conflict here:
```javascript
const innerMap = new Map(['key', 'value']);
const map = new Map(['innerMap', innerMap]);

map.innerMap = { key: 'some other value' }
_.get(map, ['innerMap', 'key']) // 'some other value'
```
So a different method is a better option.

OR you might allow setting 'mode' options for `_.get, _.set, _.has` to handle such conflicts by using the new types native methods.

For example setting a `native` mode which overrides the default process like this:
1. checks if object at path is instance of Map
2. if instance of Map -> try getting using native Map.prototype.get
3. if undefined -> try getting value for as for native object

```javascript
const innerMap = new Map(['key', 'value']);
const map = new Map(['innerMap', innerMap]);
map.innerMap = { key: 'some other value' }

_.get(map, ['innerMap', 'key'], undefined, 'native') // 'value'
```
The tricky part is how to set that `native` option. the above example forces you to set the default value as well, which is not ideal.

Either way, having this logic backed by lodash would definitely make life easier for me and other developers, as Maps and Sets have their advantages over arrays and native objects in certain use cases.

**Comment by ronen-e** [comment]
On second thought, another custom method would probably be best since you would have to support non string keys.
Maps allow using virtually anything as a key,  and `_.get` only allows string or string array values as path you might have trouble supporting something like this with the current implementation:

```javascript
let obj = { }
let map = new Map()
map.set(obj, 'some value') 

map.get(obj)     //  'some value'
_.get(map, obj)  //  undefined -> same as calling _.get(map, '[object Object]')
```

**Comment by lostpebble** [comment]
I would really love this as well.

My current implementation:
```
function get(map: Map<any, any>, path: [string|number], defaultValue: any) {
  if (map == null || path.length === 0) {
    return defaultValue;
  }

  let cur = map;

  for (const p of path) {
    if (cur instanceof Map) {
      cur = cur.get(p);
    } else {
      cur = cur[p];
    }

    if (cur == null) {
      return defaultValue;
    }
  }

  return cur;
}
```

But as @ronen-e has pointed out, Maps allow types beyond strings or numbers as a key. So this won't work. It would probably be best to create another custom method, or the current method will have to allow non-string / number values as well.

`set` gets a little more complicated (do you make portions of a path that don't exist create new Maps, or objects?). I have a working implementation (creates new objects when encountering non-existent values in the path) but it's not perfect. Was hoping for something like lodash to abstract away that complexity though.

```
function set(map: Map<any, any>|object, path: [string|number], value: any) {
  if (map == null || path.length === 0) {
    return map;
  }

  const key = path.shift();

  if (path.length === 0) {
    safeSet(map, key, value);
  } else {
    safeSet(map, key, set(getOrCreateEmptyObject(map, key), path, value));
  }

  return map;
}

function safeSet(mapOrObject: Map<any, any>|object, key: string|number, value: any) {
  if (mapOrObject instanceof Map) {
    mapOrObject.set(key, value);
  } else {
    mapOrObject[key] = value;
  }
}

function getOrCreateEmptyObject(mapOrObject: Map<any, any>|object, key: string|number) {
  if (mapOrObject instanceof Map) {
    if (mapOrObject.get(key) != null) {
      return mapOrObject.get(key);
    }

    return {};
  }

  if (mapOrObject[key] != null) {
    return mapOrObject[key];
  }

  return {};
}
```
