### ISSUE TITLE
Importing issue with lodash/fp 

### ISSUE THREAD

**Issue by crswll** [lodash/lodash#3335]
I'm sorry to jump right in with code but I don't know how else to explain the situation. Not sure if it's a bug or something I'm doing wrong.

```
import { unzipWith as fpUnzipWith, add as fpAdd } from 'lodash/fp'
import { unzipWith as normalUnzipWith, add as normalAdd } from 'lodash'

fpUnzipWith(fpAdd, [[1,2,3]]) // returns 3 functions (incorrectly?)
fpUnzipWith(fpAdd, [[1,2,3], []]) // returns correctly [1, 2, 3]

normalUnzipWith([[1,2,3]], normalAdd) // returns correctly [1, 2, 3]
normalUnzipWith([[1,2,3], []], normalAdd) // returns correctly [1, 2, 3]
```
However, the first example works if I don't import and just `<script src>` a lodash/fp build.

```
_.unzipWith(_.add, [[1,2,3]]) // returns correctly [1, 2, 3]
```

**Comment by jdalton** [comment]
Double check that the fp build in the browser is the same version or that you're not using the uncurried `add` by mistake.
```js
fp.unzipWith(_.add, [[1,2,3]]) // using uncurried `add`
// [ 1, 2, 3 ]
```

The behavior of returning an array of three partially curried functions looks to be correct when providing it `[[1,2,3]]` because it's being padding add only one param.

Normally
```js
_.unzipWith([[1,2,3],[]])
// [[1, undefined], [2, undefined], [3, undefined]]
_.unzipWith([[1,2,3]])
// [[1], [2], [3]]
```
