### ISSUE TITLE
_.sortBy() is error?

### ISSUE THREAD

**Issue by GrantColeman** [lodash/lodash#3340]
### Demo
```js
var obj = [{
    "name": "测试",
},
{
    "name": "张三",
},
{
    "name": "李四",
},
{
    "name": "王五",
},
{
    "name": "白展堂",
},
{
    "name": "铁无心",
},
{
    "name": "董颖",
}]
console.log(_.sortBy(obj, 'name'));
```

But the result is error, I hope result like this.
```js
[{
    "name": "白展堂",
},
{
    "name": "测试",
},
{
    "name": "董颖",
},
{
    "name": "李四",
},
{
    "name": "铁无心",
},
{
    "name": "王五",
},
{
    "name": "张三",
}]
```

**Comment by jdalton** [comment]
Hi @GrantColeman!

You're expecting an awful lot from a general purpose utility sorting method.
You might be able to get your desired order with a custom iteratee instead of the property name as the second argument. I think you'll have better luck with a custom method or [mixin](https://lodash.com/docs/4.17.4#mixin).
