### ISSUE TITLE
Provide a optional initializer parameter in collection functions keyBy and groupBy

### ISSUE THREAD

**Issue by christophehenry** [lodash/lodash#3341]
By default, collection functions `groupBy`, `keyBy` return JS objects, which prevents to use other key/value implementaions like `Map`. They could provide an optional initializer parameter that construct the key/value implementation that the user wants to be used and returned by the function, and defaults to JS object.

**Comment by jdalton** [comment]
Hi @christophehenry!

The use of `Map` or `Set` complicate these kinds of methods as it's more than just the initializer that would need to be branched. I think it'd be better to have a [mixin](https://lodash.com/docs/4.17.4#mixin) collection of `Map` related methods.

**Comment by splintor** [comment]
There is another reason to allow an initializer parameter. It is because the default initializer is `{}` which contains `Object` methods like `toString`. If I want `keyBy` to create a dictionary of my array, I want to be sure it only contains items from the array.
As it is urrently implemented, the following is always try:
```
'toString' in _.keyBy(myArray, iteratee)
```
So can you either change the default initializer to `Object.create(null)`, or allow users to provide their custom initializer?
