### ISSUE TITLE
Iteratee concept does not seem to be documented

### ISSUE THREAD

**Issue by glasser** [lodash/lodash#3347]
One of the nice features of lodash is that a huge number of its functions take *iteratees*. If I understand correctly, an iteratee is either a function or a simple data structure that describes how to create a simple function.  You can make your own functions accept iteratees by passing iteratee arguments through `_.iteratee`.

However, as far as I can tell, this is not actually documented anywhere in https://lodash.com/docs/

There are a huge number of references to iteratees, and `_.iteratee` is itself documented, but at no point does it actually define what an iteratee is or explain how the `_.iteratee` function relates to the things referred to as iteratees elsewhere in the docs.

**Comment by jdalton** [comment]
Hi @glasser!

The documentation example for `_.iteratee` covers the custom iteratee case. The doc examples for several other methods cover various iteratee shorthands too. I removed the type annotations for the shorthands since it cluttered up the docs for each method. I'm relying on usage examples plus doc references to get the gist across on the meaning of an iteratee.

**Comment by glasser** [comment]
I personally was unable to figure out what "iteratee" meant without reading the source code.  I think a simple sentence added to the `_.iteratee` documentation saying something this would be nice:

>Whenever a Lodash method takes an "iteratee" as an argument, that argument is converted to a function using this method.

I would send a PR but it looks like iteratee support is actually gone on master? Which makes this a moot point, I guess.
