### ISSUE TITLE
Iteratee capping inconsist in Lodash FP

### ISSUE THREAD

**Issue by friday** [lodash/lodash#3358]
Lodash version: 4.17.4

Lodash fp's default behavior is to cap iterates, but sometimes this isn't respected.

This for example works:

```js
_.map(parseInt, ['6', '8', '10']);
```

But this doesn't:
```js
const log = [];
_.map(log.push.bind(log), ['foo', 'bar']);
console.log(log); // ["foo", 0, Array(2), "bar", 1, Array(2)]
```

Capping can be forced with `convert({cap: true})`

```js
_.each.convert({cap: true})(console.log, ['foo', 'bar']); // Will log 'foo' and 'bar' only
```

Capping "_" doesn't change anything (which makes sense I guess, since this should already be the default)

```js
_.convert({cap: true}).each(console.log, ['foo', 'bar']); // Will log `["foo", 0, Array(2), "bar", 1, Array(2)]`
```
I can't seem to grasp how this could be intended, but perhaps it is?

**Comment by jdalton** [comment]
Neat find. You're running into an edge case in your testing with a bound `push`. The bound `push` has a `push.length` of `1`. Since it has a arity of `1` the fp wrapping assumes it doesn't need to cap.

If you were to bind push with `_.bind` which produces a function with a `length` of `0` then the FP wrapper would cap appropriately. I'll keep an eye on this issue and see if others report problems with the inference we use. If it turns out to be an issue I'll force cap even if the function `length` is of the capped length.

**Comment by friday** [comment]
Thanks for the explanation and fast response 👍  The length of `console.log` in my other example is also `1` it seems, although `console.log` also takes more than one argument. The same goes for `[].concat` too, and I'm guessing other parts of the JS API that takes one or variable number of arguments.
