### ISSUE TITLE
Add µ to _.deburr?

### ISSUE THREAD

**Issue by ahamid** [lodash/lodash#3399]
I'm wondering if it would be appropriate to add the Latin-1 Supplement `µ` `\u0B5` ("micro sign") to `deburr`.  It is listed it under "Latin-1 Punctuation and Symbols", but it "decomposes" to the visually indistinguishable Greek letter mu (`\u03BC`) and elsewhere is categorized as "Letter, Lowercase".

**Comment by jdalton** [comment]
What would you deburr it to?

**Comment by ahamid** [comment]
just a normal 'u'

**Comment by jdalton** [comment]
Do you have a specific use case for this character?

**Comment by ahamid** [comment]
Sanitization/standardization of unit name text for lookup or search: e.g. enter `mL` -> match `mL` and `µL` (milliliter, microliter)
(it's simple enough to make an exception on my end for this particular character, i had assumed `deburr` was converting it, before I checked the Latin-1 table and source)

**Comment by c-dante** [comment]
If this is SI unit related, I'd actually argue not to convert µ inside deburr -- it's not a Latin character, and it has meaning not represented by `m` for the use case -- accidentally deburring away an important unit indication seems like a bad idea.

**Comment by jdalton** [comment]
Ah ok!

Since there's some debate I'll leave it open to reactions.
We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).

**Comment by ephetic** [comment]
Since `_.deburr` already remaps compound characters, deburring `µ` seems reasonable.  My previous 👍 objection/vote was about conflating `mL` with `µL`, but that's a use case issue.  Maybe someone else has a use case where `Þ` shouldn't be conflated with `Th` and they just need to be aware when using `_.deburr` -- lodash shouldn't preemptively second guess them.

**Comment by c-dante** [comment]
`µ` isn't a compound character -- it's a Greek letter that is also used as an SI prefix for `micro`, and very unfortunately, the [only non-Latin SI prefix](https://www.wikiwand.com/en/Metric_prefix#/List_of_SI_prefixes).

No other Greek letter is handled by deburr.

My friction to the change is the contract of deburr is very clear: 
```
Deburrs string by converting Latin-1 Supplement and Latin Extended-A letters to basic Latin letters and removing combining diacritical marks.
```

**Comment by ephetic** [comment]
My point was that the contract of `_.deburr` actually isn't completely clear because -- in addition to removing diacriticals -- it disintegrates compounds like `ß` and `Þ`.  `µ -> m` keeps with the idea that `_.deburr` smooths rough edges off extended characters beyond just stripping diacriticals.

The only question is whether `µ` is far more different from `m` than `Þ` is from `Th` (etc).  I think the answer is no with respect to the transliteration between alphabets.  

The SI issue is a valid objection but is too specific a use case to carry all the weight.

**Comment by c-dante** [comment]
I'm sorry, how is it not completely clear? Both `ß` and `Þ` are in the [Latin-1 Supplement - Character Table](https://www.wikiwand.com/en/Latin-1_Supplement_(Unicode_block)#/Character_table), referenced by deburr.


If we're talking about extending deburr to include a much larger set of unicode characters, I'm almost fine with that too -- it is a string utility function after all.

**Comment by ephetic** [comment]
`µ` is in Latin-1 Supplement too, right?  But agreed on the string utility point.

**Comment by c-dante** [comment]
Yep -- `µ` falls in the latin suppliment -- which 100% means it should fall in deburr's territory as a character to consider decomposing. For the record:

```
_.deburr(`
  SP  	¡	¢	£	¤	¥	¦	§	¨	©	ª	«	¬	 SHY
®	¯
°	±	²	³	´	µ	¶	·	¸	¹	º	»	¼	½	¾	¿
À	Á	Â	Ã	Ä	Å	Æ	Ç	È	É	Ê	Ë	Ì	Í	Î	Ï
Ð	Ñ	Ò	Ó	Ô	Õ	Ö	×	Ø	Ù	Ú	Û	Ü	Ý	Þ	ß
à	á	â	ã	ä	å	æ	ç	è	é	ê	ë	ì	í	î	ï
ð	ñ	ò	ó	ô	õ	ö	÷	ø	ù	ú	û	ü	ý	þ	ÿ`)
// Yields:
  SP  	¡	¢	£	¤	¥	¦	§	¨	©	ª	«	¬	 SHY 
®	¯
°	±	²	³	´	µ	¶	·	¸	¹	º	»	¼	½	¾	¿
A	A	A	A	A	A	Ae	C	E	E	E	E	I	I	I	I
D	N	O	O	O	O	O	×	O	U	U	U	U	Y	Th	ss
a	a	a	a	a	a	ae	c	e	e	e	e	i	i	i	i
d	n	o	o	o	o	o	÷	o	u	u	u	u	y	th	y"
```

So, `µ` and `¶` are the major offenders of not being deburred.

I'm willing to support `mc` as the deburr for `µ`
