### ISSUE TITLE
throttle with trailing: false allocates timer that keeps process from exiting

### ISSUE THREAD

**Issue by jdiamond** [lodash/lodash#3421]
Hi,

The following script doesn't exit for 10 seconds:

```
const _ = require('lodash');

const f = _.throttle(() => console.log(new Date()), 10000, { trailing: false });

f();
f();
f();

console.log('ready to exit');
```

I understand it's because a timer is scheduled, but I have `trailing` set to false and was surprised to find out that this timer was making my AWS Lambda functions sometimes time out.

Would it be possible to skip calling `setTimeout` when `trailing` is false?

Thanks.

**Comment by c-dante** [comment]
Looks like the way the debounce works is by calling a `timerExpired` after a timeout, so doesn't seem to be a way to end early when trailing is false (can't just skip the timeout since it's being used to drive when you can call).

Unsure if you'd want to not use `setTimeout` to clear the timer and instead check at call, or just accept that lodash's debounce and throttle aren't suitable for an AWS lambda or a process that wants to end once its work is done.

Curious of the use case for a throttle inside a lambda.

**Comment by jdiamond** [comment]
AFAICT, the timer is only used to invoke the function on the trailing edge (which I want to avoid).

The `debounced` function invokes `shouldInvoke` which invokes `leadingEdge`. If `timerId` never gets set (because `trailing` is false), `leadingEdge` will invoke my function.

I _think_ adding `if (trailing)` around the `setTimeout` in `leadingEdge` and `debounced` would avoid allocating the timer. I would have tried changing it myself and submitting a PR if it worked, but there doesn't seem to be a way to build or run the tests in the repo's current state.

**Comment by ephetic** [comment]
No luck with `f.cancel()`?

**Comment by jdiamond** [comment]
I think I would have to call `f.cancel()` after every call to `f()` because it would allocate a timer every time it sees there wasn't one?

**Comment by jdalton** [comment]
Hi @jdiamond!

Our implementation is by design. It looks like it may not be suitable for your needs. No worries though. A custom throttle implementation or one of npm package will probably do.

**Comment by ephetic** [comment]
@jdiamond I don't think you would have to call cancel after every call; I think you would just need to call `clear` once on each throttled function immediately before exiting.
