### ISSUE TITLE
_.map({}) fails with object containing property 'length'

### ISSUE THREAD

**Issue by tombburnell** [lodash/lodash#3451]
node -e "var _ = require('lodash'); console.log(_.map({ length: 1 }, function(v,k) { return k+'-'+v }));"

result: [ '0-undefined' ]

expected [ 'length-1' ]

**Comment by troywoy** [comment]
The root of your issue is caused by `_.isArrayLike`. `_.isArrayLike({ length: 1 })` is true so `_.map` treats your collection as an array, not an object.

In master, `_.map` was split out so it no longer accepts a collection, only arrays. Not sure when a new release is planned, but master has `_.mapObject` which is what you'd use instead.

**Comment by ephetic** [comment]
What will happen with `_.mapValues` and `_.mapKeys`?  What besides `{}` will count as a "collection"?  This is all I found: `collection (Array|Object): The collection to iterate over.`

Thanks!
