### ISSUE TITLE
[memoize] Cache by key made from all arguments by default

### ISSUE THREAD

**Issue by evilj0e** [lodash/lodash#3607]
Here we memoize function only by first argument and sometimes it causes unexpected behavior.
I think we need use all arguments by default or print some message to console with info about keys.

Example: http://jsbin.com/retivewefa/edit?html,js,console
Sources: https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L10560

What do you think?

**Comment by jdalton** [comment]
Hi @evilj0e!

I'm not a fan of that for a general purpose util. Memoizing is a balance between how complex computing the cache key is and the actual operation being memoized. Computing your key in some custom way is preferable to blindly computing a key from all provided arguments.

**Comment by chrisdothtml** [comment]
> Computing your key in some custom way is preferable to blindly computing a key from all provided arguments

@jdalton I would actually argue that arbitrarily only using the first argument for the key is much more confusing than just using all of them. Every memoization library I've used uses all arguments to generate the key by default ([fast-memoize](https://github.com/caiogondim/fast-memoize.js#usage), [mem](https://github.com/sindresorhus/mem#cachekey), [reselect](https://github.com/reduxjs/reselect)). This definitely seems to be the standard approach.

I figured I'd give lodash's implementation a try (since it *is* pretty nice to have a standard library for utils), but it took me quite a bit of debugging to notice my app wasn't working because of this. That's mostly my fault for not properly testing the newly memoized function, but it was still confusing nevertheless
