### ISSUE TITLE
Lodash not working for NodeJS ESM modules

### ISSUE THREAD

**Issue by damianobarbati** [lodash/lodash#3775]
Neither  `import { sum } from 'lodash-es';` or `import { sum } from 'lodash';`.

```
$node -v
v10.0.0
```

```
$ node --experimental-modules test.js
import { sum } from 'lodash-es';
                ^^^
SyntaxError: The requested module 'lodash-es' does not provide an export named 'sum'
```

**Comment by jdalton** [comment]
Hi @damianobarbati!

The experimental module support in Node is only supported with the `.mjs` file extension. Because it's experimental I'm not adopting it any time soon for stable Lodash releases _(as what is and what isn't supported is likely to change)_. If you'd like ESM support in Node 6+ you can use [`esm`](https://www.npmjs.com/package/esm) _(Lodash 5 will use `esm` too)_.
