### ISSUE TITLE
how much smaller could lodash be if...

### ISSUE THREAD

**Issue by jaketodaro** [lodash/lodash#3875]
These are hard questions to answer, but I'm curious. How much smaller would lodash be (minified and gzipped) if...

It was written either with typescript or flow? API flexibility might suffer, but a lot of type safety code could be removed.

It only supported modern browsers, say ie11 and evergreen latest - 2?

Lodash has so many advantages, but size often keeps it from being adopted which is a bummer.

**Comment by jdalton** [comment]
Hi @jaketodaro!

There are plenty of options to manage Lodash's size. You can use [lodash-es](http://npmjs.com/lodash-es) with Webpack 4 to enable cherry-picked and scope hoisting, you could use [`babel-plugin-lodash`](http://npmjs.com/babel-plugin-lodash) to automate cherry-picking syntax, and [`lodash-webpack-plugin`](http://npmjs.com/lodash-webpack-plugin) to opt-in to Lodash functionality (instead of opt-out) creating substantially smaller bundles.

**Comment by jaketodaro** [comment]
Thanks for the info, but that doesn't really answer my question 😛 

If I use lodash-es and pull in just `lodash/reduce`, I've added 6kb to my project. It's great that lodash's reduce has lazy eval and is faster than native, but 6kb is a lot for something I could just replace with native in most cases. How much smaller do you think reduce could be for the above conditions?

**Comment by jdalton** [comment]
The Lodash flavor of `reduce` is not a 1:1 for native. It handles objects and array-likes as well. However, with [`lodash-webpack-plugin`](http://npmjs.com/lodash-webpack-plugin) that would be bytes and not kBs. Native is a good fit for many cases, so feel free to choose that when it's more practical.
