### ISSUE TITLE
Q: Lodash roadmap for v5.0 states _.find will be removed. What will it be replace with?

### ISSUE THREAD

**Issue by abenitesDC** [lodash/lodash#3897]
Hello,
In the [Lodash roadmap docs](https://github.com/lodash/lodash/wiki/Roadmap), it is stated that _.find will be removed. If that is correct, I would like to know if there will be an alternative for that function. 

```
v5.0.0 (~2018)
...
Remove _.find
```

Thanks!

**Comment by dnalborczyk** [comment]
> I would like to know if there will be an alternative for that function.

@abenitesDC   yes, there is: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by jdalton** [comment]
Hi @abenitesDC!

Yep, @dnalborczyk is correct there is `Array#find`. In v5 we want to reduce the number of collection methods. Pushing users to builtin methods and possibly object-centric variations when no builtin exists.

**Comment by rafde** [comment]
The unfortunate part of the removal is shorthand
```js
_.find(
  [
    {test:1},
    {test:2},
    {test:3},
  ],
  {test: 2}
);
```

**Comment by abenitesDC** [comment]
Indeed is unfortunate to see this go away. It is a very useful function (along with other collection ones). This kind of functions make us avoid adding defensive code as well as writing cleaner and shorter code by using the shorthands. 
```
// we will go from this:
items => _.find(items, {id: 1});

// to this: :(
items => {
  if (items) {
    return items.find((item) => {
      return item.id === 1;
    });
  }
});
```

A very useful function. I hope this could seriously be reconsider.

**Comment by elias6** [comment]
@jdalton I am in favor of simplifying Lodash and removing functions that do things that can easily be done using built-in functions. But I am not sure if removing `_.find` is a good idea. @dnalborczyk suggested `Array.find`, but that does not look like an adequate replacement:
* `Array.find` [doesn't work in IE](http://kangax.github.io/compat-table/es6/#test-Array.prototype_methods_Array.prototype.find_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;) without a polyfill.
* `Array.find` doesn't work on DOM node lists. `_.find(document.querySelectorAll('div'), x => x.classList.contains('container'))` works, but `document.querySelectorAll('div').find(x => x.classList.contains('container'))` doesn't. I know I can do `[...document.querySelectorAll('div')]`, but that adds a bit of clutter, the [spread syntax doesn't work in IE](http://kangax.github.io/compat-table/es6/#test-spread_syntax_for_iterable_objects) (without a polyfill), and it is one more thing that everyone has to know about and remember to do. Lodash is supposed to eliminate annoyances like this.
* `Array.find` matches by identity. `_.find([{foo: 1}], {foo: 1})` returns the object in the array, while `[{foo: 1}].find(x => x === {foo: 1})` returns `undefined`. I know I can do `[{foo: 1}].find(_.matches({foo: 1}))` or `[{foo: 1}].find(x => _.isEqual(x, {foo: 1}))` or `[{foo: 1}].find(x => x.foo === 1)` (depending on exactly what I'm trying to do), but neither of those are as obvious or elegant IMO. @dnalborczyk suggested destructuring the parameter passed to `Array.find`, but [object destructuring doesn't work in IE](http://kangax.github.io/compat-table/es6/#test-destructuring,_parameters_with_objects).
* `Array.find` doesn't work on objects. `({foo: 1}).find(x => x === 1)` throws an exception. I know I can do something like `_.find({foo: 1}, x => x === 1)`, but that is not as obvious or elegant.
* It returns `undefined` when passed something falsy, instead of throwing an exception. As [@abenitesDC pointed out](https://github.com/lodash/lodash/issues/3897#issuecomment-410764385), it can make code simpler and less error-prone to write by removing the need for defensive code.

I know that in most of these cases, I can do `Array.filter({ whatever })[0]` or `_.filter(stuff, { whatever })[0]`, but those are not as obvious, and they require looking through the whole collection instead of stopping when they find what is being looked for, which may cause performance problems.

I am going to miss `_.find` if it is removed.

**Comment by jdalton** [comment]
Many seem to be missing this bit from earlier reply
> Pushing users to builtin methods and possibly object-centric variations when no builtin exists.

Where there aren't object-flavors we'll provide object forms of the method. We're slashes methods at the moment. As always if there turns out to be a need for an array flavor we'll correct course and provide one.

**Comment by falsyvalues** [comment]
Guys no worries, its not like @jdalton is about to release Lodash in current state on `master` branch. Its still WIP and probably it will take some more time to shape up v5 to be ready for release.

**Comment by abenitesDC** [comment]
@jdalton @rafde, within our project, for all cases we use `_.find` to find one single element within a collection. Due to the `_.find` deprecation, someone suggested to use `_.findLast` instead of _.find so that we still leverage the useful lodash short hands. Will `_.findLast` be deprecated too or do you foresee any future issue? Thanks!

**Comment by jdalton** [comment]
@abenitesDC `_.findLast` is not deprecated at this time.

**Comment by abenitesDC** [comment]
@jdalton Thanks! This is our final custom implementation to deal with the `_.find` deprecation just in case someone else is interested. We decided not to use `_.findLast` as replacement:
```javascript
  find: (array, callback) => {
    const index = _.findIndex(array, callback);
    return index === -1 ? undefined : array[index];
  }
```

**Comment by illuminist** [comment]
@abenitesDC This should hold the same function as an original `_.find` except for starting index.
```javascript
_.mixin({find: (array, predicate) => array.find(_.iteratee(predicate))});
```

**Comment by elias6** [comment]
@illuminist, that won't always work. Try running `document.querySelectorAll('div').find(x => x.classList.contains('header'))`
