### ISSUE TITLE
How intersectionWith() compares arrays?

### ISSUE THREAD

**Issue by lacivert** [lodash/lodash#4015]
(For version 4.17.10, using NPM)

I have two arrays:
```
const array1 = [{
    id:1,
    category: 1
},{
    id:2,
    category: 1
},{
    id:3,
    category: 2
},{
    id:4,
    category: 2
},{
    id:5,
    category: 1
},{
    id:6,
    category: 1
},{
    id:7,
    category: 3
}]

const array2 = [1,3]
```

I need objects in array1 which has the categories in array2, so I think intersectionWith() may work, but I see that it doesn't compare two items as I expected;

```
const result = _.intersectionWith(array1, array2, function (item1, item2) {
    console.log('item1', item1)
    console.log('item2', item2)
    if(item1.category == item2){
        return true;
    } else {
        return false;
    }
})

console.log(result);
```

The output is:

```
item1 { id: 1, category: 1 }
item2 1
item1 { id: 2, category: 1 }
item2 { id: 1, category: 1 }
item1 { id: 2, category: 1 }
item2 1
[ { id: 1, category: 1 }, { id: 2, category: 1 } ]
```

I see that it compares only some elements and also it doesn't get the item1 from array1 and item2 from array2. Instead, it looks it gets items mixed? IIf this is not a bug, I believe a very nice example in documentation will make it clear.

Thanks

**Comment by brussee** [comment]
I think this is basically the same question I had, with this given answer: https://github.com/lodash/lodash/issues/4012#issuecomment-430266536

**Comment by lacivert** [comment]
@brussee Thank you for the answer provided to your question. Still I don't get ho wit works. I only understand that it does not work as I thought. It could be meaningful if it took the item1 from array1 and item2 from array2. It still does not make sense for me and I think it needs a clarification.

**Comment by brussee** [comment]
The documentation states this: "...comparator which is invoked to compare elements of arrays..." It is evident whenever you have more than 2 arrays to compare the user should not make assumptions about the origin of the elements to compare, as also elements from a 3rd array have to be compared to elements of the 2nd array. So the first argument for the comparator definitely will not be an element from the 1st array, you see?

And as jdalton stated in the answer linked above, in addition to the above, also the resulting array will be checked against the 1st array to avoid duplicates, since we are talking set-theory with the intersection function. Hope this makes things clear. If not, play around with an example that compares more than 2 arrays. Good luck!

**Comment by B1aZer** [comment]
This seems like a bug, why not elements of the arrays are checked? Does it mean the arrays should be the same length?
