### ISSUE TITLE
Request to publish latest npm package loadash.memoize

### ISSUE THREAD

**Issue by mboughaba** [lodash/lodash#4030]
Please publish latest improvements added in `v4.16.0` `Added a cache limit to internal _.memoize use`
https://github.com/lodash/lodash/wiki/Changelog#sept-19-2016--diff--docs

Currently the latest version is `4.1.2` https://www.npmjs.com/package/lodash.memoize

**Comment by jdalton** [comment]
Hi @mboughaba!

Yes, the individual method package are behind the primary. I plan to update the lot of them this fall, before the end of December.

**Comment by kachkaev** [comment]
I just discovered quite a few security errors for modularized packages reported by [BlackDuck](https://www.blackducksoftware.com/):

![screenshot 2019-03-06 at 18 23 14](https://user-images.githubusercontent.com/608862/53904075-233e9f00-403d-11e9-9508-0e5ac5c16d03.png)

Despite that the lines say just `lodash` and not `lodash.something`, it's not the case of us having multiple instance of `lodash`. Yarn.lock contains just one copy of `lodash` and a bunch of individual modules like `lodash.keys` etc.

We can't resolve the errors unfortunately because all `lodash.something` dependencies are sub-dependencies of other modules. Re-publishing these would be awesome!

**Comment by armenzg** [comment]
Is there a non-closed issue for this?
