### ISSUE TITLE
findKey function works not as expected with integer

### ISSUE THREAD

**Issue by anking** [lodash/lodash#4069]
```
myobject: {
            zero: 0,
            one: 1,
            two: 2
        }
console.log(_.findKey(myobject, 0));
/// => undefined
```

expected to get a "zero" got undefined... why?
it works perfect this way:
```
myobject: {
            zero: '0',
            one: 1,
            two: 2
        }
console.log(_.findKey(myobject, '0'));
/// => zero
```

**Comment by jdalton** [comment]
Hi @anking!

You're using the shorthands incorrectly. You're providing a property shorthand. Which is trying to do `value[prop]` so when you provide `0` your creating a function that checks `0[0]` which is `undefined` but on a value `'0'[0]` you get `'0' since it's a string and you're accessing the first character of the string.

**Comment by anking** [comment]
can you please provide an example on how to check if there is an integer 0?

**Comment by jdalton** [comment]
If you're wanting to check for the value `0` you can just pass a function:
```js
_.findKey(myobject, (v) => v===0)
```

**Comment by anking** [comment]
Thank you!
