### ISSUE TITLE
set function bug?

### ISSUE THREAD

**Issue by drdevelop** [lodash/lodash#4306]
When i put a set in the class and set the function value to the object, it becomes an empty object.

**Comment by drdevelop** [comment]
this is my code:
```js
const obj = {};
class A {
 setValue() {
   console.log('this is set value');
 }
  init() {
   _.set(obj, 'a', this.setValue);
 }
}
new A().init();
console.log(obj.a); // {} response a null object
```

**Comment by viniciusls** [comment]
Hi @drdevelop, there are two errors in your logic:

1) You are not calling `setValue` as a function on your `init()` method. The way you're doing, you're just setting the role function on obj.a, so if I execute your code the `console.log(obj.a)` returns `[Function: setValue]`. There's two ways to make it work this way:  `_.set(obj, 'a', this.setValue());` or `console.log(obj.a());`;

2) Your `setValue` function is not returning anything. If you try to use the first solution (`_.set(obj, 'a', this.setValue());`), it'll simple run the `console.log` and print `this is set value` on your **terminal** not on `obj.a`. You should change it to `return` instead of `console.log`.

Hope it helps!

**Comment by viniciusls** [comment]
And through it all, it's not a lodash bug!

**Comment by drdevelop** [comment]
@viniciusls Thanks for your reponse, my intention is set obj.a to setValue function, then if i execute command console.log(obj.a), will be showing function body of setValue, but now that is showing empty object

**Comment by drdevelop** [comment]
sorry, That is the command line is displayed incorrectly
