### ISSUE TITLE
_.round doesn't work as intended when using it as iteratee shorthand

### ISSUE THREAD

**Issue by Nephylhim** [lodash/lodash#4343]
Hi!

I encountered an unexpected behavior when working with:

* _.round
* as iteratee shorthand
* when iterating on an object with numbers as keys

Here what it looks like:
```javascript
const count1 = {
  "2": 33.333333333333336,
  "5": 66.66666666666667
};

const countPercent1 = _.mapValues(count1, _.round);

console.log('iteratee shorthand / numbers => NOK', countPercent1);
// "iteratee shorthand / numbers => NOK" Object {
//   2: 33.33,
//   5: 66.66667
// }
```

It works well when working with strings or when using a callback instead of the shorthand iteratee.
Here is a CodePen with the example: https://codepen.io/anon/pen/orooXW?editors=0012

When I was creating the pen, I realized why it behaved like this. When using a function (_.round here), lodash passes it 3 arguments:

* the value
* the index/key
* the whole object

As round take the precision as second argument, it alter the function behavior... It also mean that the same problem occurs with arrays.

I don't know if this can be considered a bug. I suppose that any modification on this matter will have too much aftermath.

However I didn't see any documentation on this. Is there any somewhere? It would prevent some people to fall into this trap.

**Comment by falsyvalues** [comment]
Hi @Nephylhim!

This sounds like `.map(parseInt)` case, so I will refer this stackoverflow question: [Why does parseInt yield NaN with Array#map?](https://stackoverflow.com/questions/262427/why-does-parseint-yield-nan-with-arraymap).

**Comment by jefffriesen** [comment]
I know this is closed, but I wanted to give an example of this happening with an array:
<img width="591" alt="Screen Shot 2019-11-07 at 8 14 44 PM" src="https://user-images.githubusercontent.com/445733/68446889-49ec4100-019b-11ea-98a1-e35619a5205f.png">

The reason, as explained in that stack overflow link that @falsyvalues provided, is that the second argument to `_.round` becomes the index of the array element. That's why the precision increases with each number.
