### ISSUE TITLE
memoize: a way to preserve name of function?

### ISSUE THREAD

**Issue by json2d** [lodash/lodash#4389]
there doesn't seem to be a way to get the name of the original function after it's been memoized.  should there be?

maybe store the original name on the function:
```js
const myFun = () => "hello lodash"
const memoizedMyFun = _.memoize(myFun)
console.log(memoizedMyFun.originalName) // myFun
```

better for logging and debugging

**Comment by jdalton** [comment]
Hi @json2d!

In modern JS engines you can just use `Object.defineProperty` or `Reflect.defineProperty`:
```js
Reflect.defineProperty(memoizedMyFun, 'name', 
  Reflect.getOwnPropertyDescriptor(myFun, 'name'))
```

**Comment by leewz** [comment]
Currently, there is no way to access the original function, or even its name, from a memoized version of the function. You'd have to store it manually, at the point of creation. One way is to wrap `_.memoize` with a function that stores it.

The issue is requesting that `_.memoize` itself do the storing. Python's `functools.lru_cache` stores information about the original function, and even rewrites the name and signature of the memoized function.
