### ISSUE TITLE
Exception about process.binding on react native

### ISSUE THREAD

**Issue by pvinis** [lodash/lodash#4428]
When running a react native project with lodash as a dep, when I remote debug, I get this:
<img width="847" alt="Screen Shot 2019-08-21 at 13 40 32" src="https://user-images.githubusercontent.com/100233/63425475-e874cb80-c410-11e9-8145-05d0b4a26df0.png">

lodash version `4.17.15`

Related to https://github.com/lodash/lodash/issues/2920?

**Comment by falsyvalues** [comment]
Hi @pvinis!

Please correct issue title and add more information. We didn't get any reports regarding #2920 later on.

**Comment by pvinis** [comment]
I know you didn'y hence me making this issue.

**Comment by pvinis** [comment]
@falsyvalues that should help a bit more.

**Comment by falsyvalues** [comment]
@pvinis Can post also node version and react native?

**Comment by pvinis** [comment]
rn `0.59.9` (latest 0.59), and node `11.9.0`

**Comment by jdalton** [comment]
Hi @pvinis!

This is because they've (ReactNative?) nooped `process.binding` out to just throw an error (as seen from your screenshot). This is the expected behavior then. Again since it's in a try-catch you're only having to deal with this when you pause on caught exceptions which you should just be able to continue to the next without much fuss.
