### ISSUE TITLE
Omission of certain functions for version 5.0.0

### ISSUE THREAD

**Issue by leanhvie** [lodash/lodash#4478]
Having gone through the roadmap for version 5.0.0, it is a pity that some functions will be omitted. The native implementation in JS are not as strong as the ones in `lodash` with regards to null-safety or currying capability for functional patterns.
Additionally, at least for the functional approach, it would make sense to keep functions like `curry`, `spread` and others for function composition patterns.

Certainly we could attempt to create our own functions but I reckon that the reason why many use `lodash` is that we don't want to reinvent the wheel when it is already somewhere implemented and well tested.

**Comment by jdalton** [comment]
Hi @leanhvie 👋 

Nice to meet you at WebExpo! You raise an excellent point about null-safety and currying. I will re-evaluate our choice to drop some of these methods.

**Comment by blikblum** [comment]
I have similar worry about removal of `extend` / `assign` whose behavior is not exactly equal to `Object.assign`

As an example, i ported Backbone to use [ES Classes and modern JS features](https://github.com/blikblum/nextbone). I tried to replace most of underscore methods by native ones including `_.extend`.

But when i replaced `_.extend` by `Object.assign` some tests failed because `Object.assign` crashes when passing null or undefined as one of the sources.

This would prevent to replace underscore/lodash v4 by lodash v5 as dependency

**Comment by jdalton** [comment]
> This would prevent to replace underscore/lodash v4 by lodash v5 as dependency

Lodash is not the defacto utility lib so I'm not too worried about that scenario.

I am concerned out the null-safety case. I wonder if a babel-plugin or a functional wrapper method for null-safe would do.

```js
const safeAssign = nullSafe(Object.assign)
```

**Comment by blikblum** [comment]
> Lodash is not the de facto utility lib now

Currently, lodash v4 works but v5 will not work for cases where `extend` are used with null arguments. Users will need to bring your own `assign` / `extend` implementation

Regarding the cost of maintain such functions is pretty low given they are self contained, well tested, and won't affect who doe not uses

**Comment by jdalton** [comment]
maybe smth like:
```js
function mapArgs(func, iteratee) {
  return function (...args) {
    return Reflect.apply(func, this, args.map(iteratee))
  }
}

const assign = mapArgs(Object.assign, Object)
```

**Comment by blikblum** [comment]
> maybe smth like:

IMO, keeping the functions that null-safety functionality is required is cheaper than adding an function like the proposed above:

 - the functions already exists and are well documented and tested (in unit tests and in the wild). The introduction of a new function always carries the risks of unforeseen caveats
 - the users already know how to use them. No need to learn another concept / function
 - similar mapArgs functions, in concept, like ary, unary were removed from lodash
 - there's a performance overhead in such approach
 - keeping functions will not affect the users that don't use them because of the new lodash architecture

**Comment by jacksonrayhamilton** [comment]
I’m also curious about the rationalization for some methods being dropped:

- `find`: We won’t be able to do `_.find(users, { 'age': 1, 'active': true })` anymore?  Or chain `find`?  Is there an alternative?
- `omit`: The roadmap says `pick` can replace this.  I can imagine using `pick` to pick out two sets of keys, where the two sets sum back up to the original set.  But what if I want to omit some keys and keep an unknown set of remaining keys?  This can be useful for developing APIs, where the set of keys one would want to keep is changing a lot over time.

**Comment by amc1804** [comment]
The harder it is to migrate from v4 to v5, the fewer people will do it. Every breaking change adds more work to the upgrade task. Which of the proposed breaking changes bring enough benefit to justify that cost?

My favorite things about Lodash are that it uniformly treats null and undefined as empty collections, uniformly supports iteratee/predicate shorthands, uniformly defaults to the identity function, supports chaining, and comes with lots of useful convenient functions. The combination of those features lets me write very concise easy-to-understand code (which is therefore less likely to have bugs). The performance overhead is low, and the library is only about 2% of my total code size.

What does "Split Collection methods into array & object methods" mean? Does that mean I'll need to find every place I call any Collection method, determine whether the data is an array or an object, and alter the code accordingly? What if the type of the data is not obvious (it's passed in from somewhere else, which passed it along from somewhere else...) That could be a lot of work.

Unless a proposed breaking change has a workaround that's as concise and readable as the v4 interface, and the workaround can be applied simply and mechanically, please consider keeping that feature in v5. People who don't want it won't need to take it, because v5 will be modular, right?

**Comment by csvan** [comment]
Sorry if I'm hitting a tangent, but are there any updates regarding the progress towards 5.0?

**Comment by hustcc** [comment]
Any progress on 5.0, When will it be released?

**Comment by 1valdis** [comment]
Seeing that `find` is going to be removed in v5, I will consider staying on v4 just to be able to use `find` with objects as search criteria.
