### ISSUE TITLE
Improve tree-shaking

### ISSUE THREAD

**Issue by Triplecorpse** [lodash/lodash#4527]
Hello! I have read, then tested tree-shaking with Angular 8 and `ng build --prod`.
I claim that tree shaking works not very well. If I import like this

    import {concat} from 'lodash';

the whole library imports. That is not very good. To import only 1 function `concat` I should write

    import concat from 'lodash/concat'

It is okay if I need only 1 function. but what if I need 2 or 10 of them? The code looks then extremely ugly.

I suggest to improve the module sysytem and import in casual way like 

     import {concat, map, filter, whatever} from 'lodash';

**Comment by Triplecorpse** [comment]
And yes, For this purpose I used the latest version

**Comment by falsyvalues** [comment]
Hi @Triplecorpse!

Because of how current version is build,
```js
import {concat, map, filter, whatever} from 'lodash';
```
this will not make your bundles smaller (see [this post](https://nolanlawson.com/2018/03/20/smaller-lodash-bundles-with-webpack-and-babel/) for more). Until version 5 of Lodash we are slightly limited in options.
Please take a look also on #4275 for some details.
