### ISSUE TITLE
orderBy functions don't work as advertised

### ISSUE THREAD

**Issue by daveisfera** [lodash/lodash#4608]
The PR ( #3764 ) to resolve custom compare function for sorting ( #3763 ) gives an example of doing a case insensitive sort, but it doesn't actually work. Here's an extend version of that example that actually has mixed case and you can see that the result is not sorted as expected:
```
import orderBy from 'lodash/fp/orderBy';

const users = [
    { user: 'fred', age: 48 },
    { user: 'barney', age: 34 },
    { user: 'fred', age: 40 },
    { user: 'barney', age: 36 },
    { user: 'Fred', age: 49 },
    { user: 'Barney', age: 35 },
    { user: 'Fred', age: 39 },
    { user: 'Barney', age: 33 },
];

// Sort by `user` then by `age` using custom compare functions for each
const usersSorted = orderBy(
    ['user', 'age'],
    [(a, b) => a.localeCompare(b, 'de', { sensitivity: 'base' }), (a, b) => a - b],
    users,
);

console.log(usersSorted);
```

**Comment by beaunus** [comment]
I also got an unexpected result when using `_.sortBy` with the above mentioned comparison function.

```js
function byLocaleCompare(a, b) {
  return a.localeCompare(b, "de", { sensitivity: "base" });
}

console.log(_.sortBy(["Barney", "Fred", "barney", "fred"], byLocaleCompare));
// (4) ["Barney", "Fred", "barney", "fred"]

console.log(["Barney", "Fred", "barney", "fred"].sort(byLocaleCompare));
// (4) ["Barney", "barney", "Fred", "fred"]
```

I expected `_.sortBy` to return the same result as `Array.prototype.sort`.

**Comment by illuminist** [comment]
`orderBy` and `sortBy`'s second parameter is iteratee function, which means it's a function accept one parameter for one object and output one value to be used to for further compason with another result from another object. Unlike comparator function, where it accepts 2 parameter to compare 2 objects and output gt/lt/eq result.

I think the library is missing `orderWith` and `sortWith` which both should accept comparator function instead of iteratee function.

**Comment by beaunus** [comment]
Thank you, @illuminist .

**Comment by daveisfera** [comment]
The statements made by @illuminist are correct, but that's not what the documents and current code ( see https://github.com/lodash/lodash/blob/86a852fe763935bb64c12589df5391fd7d3bb14d/orderBy.js#L31 ) state and this PR is requesting that the implementation be fixed to match the documentation or vice versa

**Comment by mr-aspex** [comment]
Same issue here, we need implementation with a possibility to pass custom comparator instead of just ['asc', 'desc']. 

For instance, the change could help with natural alphanumeric sorting:
` orderBy(models, 'name', (a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base', }) )`

**Comment by leonardoanalista** [comment]
There is nothing wrong with the `orderBy/fp`, apart from the inexisting and poor quality docs for `lodash/FP`.

The callback function does not take 2 parameters. It takes only 1. All you need to do is return an `int` so that `lodash` can compare it against the other items:

```
const usersSorted = orderBy(
    (item) => item.age,
    'desc|asc here'
)(users); 
```

**Comment by shifragoldstone** [comment]
> There is nothing wrong with the `orderBy/fp`, apart from the inexisting and poor quality docs for `lodash/FP`.
> 
> The callback function does not take 2 parameters. It takes only 1. All you need to do is return an `int` so that `lodash` can compare it against the other items:
> 
> ```
> const usersSorted = orderBy(
>     (item) => item.age,
>     'desc|asc here'
> )(users); 
> ```

Hi @leonardoanalista - is there a way to use that with natural sorting (the localeCompare method that was mentioned in the original question)
