### ISSUE TITLE
lodash requires a lot of inodes/file-space

### ISSUE THREAD

**Issue by staabm** [lodash/lodash#4632]
searching thru all projects we deploy using `find /root/of/all/our/projects/sources -xdev -printf '%h\n' | sort | uniq -c | sort -k 1 -n` we see almost uniquely that lodash consumes the most inodes of all dependencies, no matter which project we look at. 
its even the biggest source folder thru all projects (in our php based product).

in our use case we install lodash as a transitiv dependency, which makes it even less appealing.
it is installed via npm.

`node_modules/lodash$ ls -l *.js | wc -l`
shows me that lodash contains contains 631 javascript files.

interesstingly it also contain a `fp` subfolder, which - again - contains 415 javascript files.

I never used lodash and dont know the package structure nor the internals of it.
do you see some room for improvement, so it will contain less files and therefore would consume less inodes?

measured on lodash v4.17.15

**Comment by falsyvalues** [comment]
Hi @staabm!

I would say that this is typical for node ecosystem that libraries like this use a lot of separated files because thats the way we separate functionalities just like in PHP. We have many files because Lodash covers quite wide range of functionalites. Version 5 probably will have smaller i-nodes footprint .
