### ISSUE TITLE
intersectionBy returns unexpected array when invalid iteratee is used

### ISSUE THREAD

**Issue by stonefruit** [lodash/lodash#4724]
I am trying to use `intersectionBy`, but it seems to be giving me this problem when the iteratee is not present.

Lodash version: 4.17.15
```
const _ = require('lodash');
let arr1 = [{ v: 'a' }, { v: 'c' }];
let arr2 = [{ v: 'b' }, { v: 'd' }];

let val1 = _.intersectionBy(arr1, arr2, 'v');
console.log(val1); 
// works fine: expecting [], got []

let val2 = _.intersectionBy(arr1, arr2, 'i');
console.log(val2); 
// works strange: expecting [], got [ { v: 'a' } ]
```

**Comment by libor-vilimek** [comment]
@stonefruit - it is expected value, I will explain why:

**Reason why there is no empty array**
By putting `i` as last parameter basically mean "if there are same value of `i` in arr1 and arr2, then its intersection". 

What happens is that both is `undefined` and therefore it equals, its something like this

```
const a = undefined;
const b = undefined;

console.log(a === b);
```

**Reason why there are not both values**
Based on previous statement you probably think "ok, but then it is undefined for all objects, why does it return just first one and not both?"

Its because it intersects the values as uniques, similar to that, if you have 

`console.log(_.intersectionBy([2.1, 1.2, 2.3], [2.3, 3.4, 2.4], Math.floor));`

It will also return only `[2.1]`, because both `2.1` and `2.3` are `2` when you put them to `Math.floor`, so the first one "wins" over the uniqueness.

**Comment by stonefruit** [comment]
Hey. Thanks for the explanation. So it means that value of `i` is `undefined` in all cases, and the function returns the first value from the first array. Thanks!
