### ISSUE TITLE
sortBy ignores negative numbers

### ISSUE THREAD

**Issue by alamothe** [lodash/lodash#4736]
```
console.log([{
	a: 10,
	b: -20,
}, {
	a: 10,
	b: -10,
}].sortedBy(e => [e.a, e.b]))
```

This prints:
```
0: {a: 10, b: -10}
1: {a: 10, b: -20}
length: 2
```

Why?

**Comment by benji-dubs** [comment]
What exactly is .sortedBy on the array prototype and what does it have to do with lodash?

This is not reproducible with eg. `_.sortBy(array, ['a', 'b'])`

**Comment by alamothe** [comment]
Sorry I changed the example:
```ts
const a = _.sortBy(
	[{
		a: 10,
		b: -20,
	}, {
		a: 10,
		b: -10,
	}],
	e => [e.a, e.b])

console.log(a)
```
It still outputs wrong result:
```
[ { a: 10, b: -10 }, { a: 10, b: -20 } ]
```

**Comment by alamothe** [comment]
Looks like it will use lexicographical order for numbers. 🤦

**Comment by mayank-mittal** [comment]
What exactly are you trying to do.
Where you're sorting a set of data, its usually is done using a property (Math duh)

e.g. 
1. Sort `["abc", "abb", "dda", "bac"]` by the length of element
2. Sort `["abc", "abb", "dda", "bac"]` by the first alphabet of the element
3. Sort `[{
		a: 10,
		b: -20,
	}, {
		a: 10,
		b: -10,
	}]` by property `a` of the element.

What you're doing is sorting by array [a,b], what does it mean..
If you take this question to a Math's undergrad he might change his profession.

You're only getting the output whatever it is, its because how javascript handle things i.e. in this case it is similar to the below examples

`const b = _.sortBy(array, (e) => [e.a, e.b].join())`
`const c = _.sortBy(array, (e) => e.a + "-" + e.b)`

**Comment by mayank-mittal** [comment]
Explain what exactly you're trying to do here, i might be able to explain you a bit better.

**Comment by mayank-mittal** [comment]
It has nothing to do with numbes, it just how javascript handle things,

When you run this 

`[[1], [2], [1, "a"], ["a"]].sort()`
As javascript can't sort out arrays directly (cause it doesn't make sense), it runs the `toString()` function on element, which converts the code into
`["1", "2", "1,a", "a"].sort()` and that returns `[[1],[1,"a"],[2],["a"]]` by lexicographical sort

Similary in your case
Sorting by `[e.a, e.b]` equals `[e.a, e.b].join()` equals `${e.a}, {e.b}'`
so you're actually sorting by the values you get by concatenating `a` and `b` of each element, by which the output is correct.

**Comment by daedalus28** [comment]
Since `_.sortBy` is behaving as expected, I think this issue is safe to close.

**Comment by alamothe** [comment]
Why should:
- `_.sortBy(array, ['a', 'b'])`
- `_.sortBy(array, e => [e.a, e.b])`

behave differently? Both are saying the same thing, first sort by `a` then by `b`.

Things are surely not "behaving as expected" if you have a giant bug in a sort function in a library used by millions.

**Comment by bnjmnt4n** [comment]
Your second example is invalid, it causes lodash to try to sort by an array, which occurs as mentioned via typecasting to a string. The correct version should be `_.sortBy(array, [e => e.a, e => e.b])`.

**Comment by alamothe** [comment]
Thanks that makes sense.
