### ISSUE TITLE
Naming of 'Last' vs 'Right'

### ISSUE THREAD

**Issue by geoynomous** [lodash/lodash#4748]
I understand all "regular" functions, but for the reverse function you use "Last" and "Right" - and I do not see a consistency. 

* drop -> dropRight
* dropWhile -> dropRightWhile
* findIndex -> findLastIndex
* indexOf -> lastIndexOf 

See also the confusion between 'last' (whose 'reverse' is 'head' while 'first' is deprecated) and 'lastIndexOf' (which should be 'firstIndexOf' if using the same grammar rules). 

So here is proposal to create new pairs

* drop/dropReverse
* dropWhile/dropWhileReverse
* findIndex/findIndexReverse
* indexOf/indexOfReverse

and there is new ones that can come up
* nth/nthReverse

or you keep the names and alias them in a subfield:

```
_.r = {}
_.r.dropWhile = _.dropRightWhile;
_.r.drop = _.dropRight;
_.r.indexOf = _.lastIndexOf;
// and similar
```
The 'r' could be read as 'right' or 'reverse'. I couldn't find a valid symbol that can be used instead of 'r'

PS what is the reverse operation of 'initial'?

**Comment by daedalus28** [comment]
My personal view here is that there is some consistency - it seems like the convention is to use `right` when it's describing iteration order, whereas `last` is used when it's describing what is returned. In `dropRight`, iteration order is the thing that matters - you care that it starts at the right because you expect your iteratee called in that order. In the case of `findLastIndex`, the iteration order itself is an implementation detail and doesn't affect your usage - what you care about is that it returns the last one in the list, regardless of the direction in which it iterated.
