### ISSUE TITLE
For different font weight I am getting different kebabCase result

### ISSUE THREAD

**Issue by mianusmankhalid** [lodash/lodash#4794]
I want to slugify the SEO friendly Title but having different results on same but different font weighted text.

e.g.

_.kebabCase('SC BOOKING FROM HOME');
"sc-booking-from-home"

_.kebabCase('𝗦𝗖 𝗕𝗢𝗢𝗞𝗜𝗡𝗚 𝗙𝗥𝗢𝗠 𝗛𝗢𝗠𝗘');
"𝗦-𝗖-𝗕-𝗢-𝗢-𝗞-𝗜-𝗡-𝗚-𝗙-𝗥-𝗢-𝗠-𝗛-𝗢-𝗠-𝗘"

Need some extra input parameter for kebabCase which gives the same output for same text

**Comment by daedalus28** [comment]
This took me a minute to figure out because I had never seen bold characters as part of a string like that :smile:

My understanding here is that you're using unicode characters [outside the BMP](https://stackoverflow.com/questions/3744721/javascript-strings-outside-of-the-bmp) to make things bold which is preventing lodash from understanding the casing here. This is an underlying javascript string handling question and seems to be outside the realm of lodash's concern. For example: `'SC BOOKING FROM HOME'.length === 20`, but `'𝗦𝗖 𝗕𝗢𝗢𝗞𝗜𝗡𝗚 𝗙𝗥𝗢𝗠 𝗛𝗢𝗠𝗘'.length` === 37

As an actionable suggestion, especially if you're worried about SEO, I'd suggest you do font-weight with styling instead of with unicode characters with questionable browser support.

Either way, I think this is the expected behavior and is safe to close.

**Comment by mianusmankhalid** [comment]
Thanks @daedalus28 for the comprehensive answer and actionable suggestion. 👍 
I also did some investigation of this behaviour and found almost similar details.

There are three different kind of English alphabets

1. Latin alphabet
2. Latin alphabet become bold with styles applied on it
3. Bold alphabet which will keep it's bold characteristic for rest of its life

For example let us discuss alphabet S here in terms of its unicode to identify the difference

Character        UTF-16               UTF-32          Uni­co­de char­ac­ter name
S                      \u0053               00000053     LATIN CAPITAL LETTER
**S**                      \u0053               00000053     LATIN CAPITAL LETTER (STYLE BOLD)
𝗦                      \ud835\udde6   0001d5e6      SANS-SERIF BOLD CA­PI­TAL

So if we will use Unicode BOLD CAPITALS or Unicode BOLD SMALL unicode characters, it will not be convertible for slugify the title, lower or upper cases and bold to normal with javascript functions. And will always be shown with its original characteristics because that is outside the scope of Javascript.

for ref: https://unicode-search.net/unicode-namesearch.pl?term=BOLD

Proposed Solution:
While creating and updating an article, No problem with the copying and pasting of title or translating it from other languages but make sure the end result is using LATIN LETTERS
