### ISSUE TITLE
`_.isEmpty` return `false` for non-falsey number values

### ISSUE THREAD

**Issue by josser** [lodash/lodash#483]
``` js
_.isEmpty(123); // true
_.isEmpty('123'); // false
```

**Comment by sgarbesi** [comment]
I think the problem is that other languages that have empty Functions don't seem to coincide with this Functionality (or other languages for that matter, it's almost different in all of the major langs).

I wound up just writing my own _.isTruthy Function.

_.isTruthy =>

!== 0
!== false
!== ""
!== undefined
!== isNaN()
!== null
