### ISSUE TITLE
It seems _.intersectionBy and intersectionWith has wrong behavior.

### ISSUE THREAD

**Issue by rkalkani** [lodash/lodash#4832]
Hi Folks,
I was trying intersectionWith to find the items in two array with same semantics. The intersectionBy/With does not return all intersect but only the first value based on response.

Following is the simple case to reproduce unexpected behavior (Or may be i misunderstood, in that case better to update example in doc with following.)

Actual:
```
_.intersectionBy([1.2, 1.3, 3.3, 3.1], [1.2, 2.2], Math.floor)
> [1.2]
_.intersectionBy([1.2, 1.3, 3.3, 3.1], [1.3, 2.2], Math.floor)
> [1.2]
_.intersectionWith([1.2, 1.3, 3.3, 3.1], [1.3, 2.2], (a, b) => Math.floor(a) === Math.floor(b));
> [1.2]
```

Expected ??

```
_.intersectionBy([1.2, 1.3, 3.3, 3.1], [1.2, 2.2], Math.floor)
> [1.2, 1.3]
_.intersectionBy([1.2, 1.3, 3.3, 3.1], [1.3, 2.2], Math.floor)
> [1.2, 1.3]
_.intersectionWith([1.2, 1.3, 3.3, 3.1], [1.3, 2.2], (a, b) => Math.floor(a) === Math.floor(b));
> [1.2, 1.3]
```

I was expecting its behavior similar to diffferenceWith :) 
Actual:
```
_.differenceBy([1.2, 1.3, 3.3, 3.1], [1.2, 2.2], Math.floor)
> [3.3, 3.1]
```

**Comment by rkalkani** [comment]
For now i used following, Main aim for this issue is to understand if intersection has a bug or its actual purpose was not clear to me.
```
[1.2, 1.3, 3.3, 3.1].filter(a => [1.2, 2.2].findIndex(b => Math.floor(a) === Math.floor(b)) !== -1)
> [1.2, 1.3]
```

**Comment by Doatti** [comment]
The documentation describes `_.intersection` like this
>Creates an array of unique values that are included in all given arrays using SameValueZero for equality comparisons. The order and references of result values are determined by the first array.

When you use `intersectionBy` or `intersectionWith`, your custom function is used for equality comparisons. So, when you use `Math.floor`, 1.2 and 1.3 are considered equal in the first array of your examples. That is why it only returns the first one, because it only returns *unique* values with respect to the comparator/iteratee used.

By that reasoning, I think the functions are working correctly. Admittedly, it is a bit confusing and probably should be clarified in the documentation.

**Comment by rkalkani** [comment]
@Doatti Yes it make sense now in the context of unique result. Thank you for explanation. 

I think we can add one of above example in doc to make returning unique behavior more clear. I will see where doc is stored and open PR.
