### ISSUE TITLE
Low severity vulnerability reported by npm

### ISSUE THREAD

**Issue by neilbryson** [lodash/lodash#4836]
I just got a [vulnerability report](https://www.npmjs.com/advisories/1523) from our CI telling that all versions of lodash are vulnerable to prototype pollution.

**Comment by leonardorb** [comment]
Same here: `found 4327 low severity vulnerabilities` here on a brand new project.
Example:
![](https://leo.d.pr/IHhFL4+)

**Comment by adevine** [comment]
This is a dupe of https://github.com/lodash/lodash/issues/4744. It's been open for a couple months but my guess is that it will start hitting a lot more people today as NPM released an advisory for it so it will start failing builds that rely on `npm audit`.

My suggestion:
1. Use [npm-audit-resolver](https://github.com/naugtur/npm-audit-resolver) to make more granular decisions about audit failures.
2. Together with step 1 above, use [patch-package](https://www.npmjs.com/package/patch-package) to patch this issue. There are a bunch of open PRs that address this vulnerability.

**Comment by NehaNaithani** [comment]
Same here found 4989 low severity vulnerabilities in my new project.
![image](https://user-images.githubusercontent.com/35979902/86316393-c975d580-bc80-11ea-9e38-7b3168ca5b5c.png)

**Comment by SantiagoMolinaOrozco** [comment]
for me, found 4812 low severity vulnerabilities in 2367 scanned packages

![image](https://user-images.githubusercontent.com/17752391/86318976-f1215b00-bbf8-11ea-82e9-87e9eec973e5.png)

**Comment by dieguiviti** [comment]
I have a react application presenting the same issue with lowdash. 

out of 1675 packages, 4982 low sev vul

**Comment by rally25rs** [comment]
There have been an open PRs for a while: #4744 #4745 #4759

I believe the most up-to-date discussion is happening in #4759 so you may just want to "subscribe" to that PR thread.

-----

🙏  Please do not post "me too" comments and flood the issues.
`npm audit` now recognizes this vulnerability as well, and since this is one of the most used JS packages on npm, it affects millions of projects (literally; Github alone says >7mil repos on github use lodash).

**Comment by taxonomic-blackfish** [comment]
Please merge #4745 as all of our automated security scanning is broken due to mass amounts of reporting in `yarn audit` (https://github.com/yarnpkg/yarn/issues/8012). This may not be high priority for you, but all of our builds are broken.

**Comment by petershaw** [comment]
@jdalton  `for me at least this is not a high priority issue` comment in the pull request means to me: "do not use this in production". :-/
For us it is a a show-stopper for lodash while we have a `npm audit` in our CI-System for all our products. Projects are failing since this vulnerabilities is reported. I acknowledge that `some report ruin my week or plans` should not happens to you at all, but from an enterprise point of view this is urgent, because `npm audit` denies building all of our projects that requires lodash. 
To get this done, maybe we can help to maintain?  Please give me a hint how one of our developers can help you out to get your time management back on track.
Thanks a lot. 
ps

**Comment by RobertoGongora** [comment]
Also, that comment was posted on May 1st, it's been many weeks already so which week was he talking about? I'm aware this is an open source package, but if he's the sole responsible for a transitive dependency then he should either delegate to someone else while he's on vacation, or just hand the project off to someone whom's week or plans won't get ruined by just clicking a big green button to help thousands of developers who are just trying to do their jobs.

**Comment by NomaanAhmed** [comment]
Looks like the [PR](https://github.com/lodash/lodash/pull/4759) has been merged, but we'll still need a publish.

**Comment by fabb** [comment]
+ someone needs to inform npm support to whitelist the new version
