### ISSUE TITLE
Why use constructor to copy objects of type RegExp?

### ISSUE THREAD

**Issue by owiki** [lodash/lodash#4840]
When I read the source code of `cloneDeep`, I found that you use a `constructor` to create a new object of type `RegExp`, why not just use `new RegExp`? In my opinion, the `constructor` may be changed, is it not safe?
This is the source code:
```javascript
function cloneRegExp(regexp) {
    var result = new regexp.constructor(regexp.source, reFlags.exec(regexp));
    result.lastIndex = regexp.lastIndex;
    return result;
}
```

And this link is the function —— [cloneRegExp](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L4550)

**Comment by thxiami** [comment]
In my opition, use `regexp.constructor` could avoid that `RegExp` has been overwritten.

```js
class RegExp {}

const regexp = /a/
const result1 = new regexp.constructor(regexp.source, reFlags.exec(regexp)) // will return a real RegExp object
const result2 = new RegExp(regexp.source, reFlags.exec(regexp)) // will return an user-defined object, not a real RegExp object
```

As you said,
> In my opinion, the `constructor` may be changed, is it not safe?

You're right. We can't prevent user from changing the `constructor`or overwriting the `RegExp`. So I guess the author choose to only consider the common situations.

**Comment by bathos** [comment]
I’d guess that `constructor` is preferred for two reasons:

1. To account for subclasses of RegExp
2. To account for cross-realm objects

Intrinsic RegExp methods do this, too, so lodash’s behavior is mostly consistent with operations like `RegExp.prototype[Symbol.matchAll]`, which also has to create a local copy of the original pattern (they do differ in the details though, since those operations honor `Symbol.species`, while lodash doesn’t).

Most libraries assume intrinsic properties (like `globalThis.RegExp` and `RegExp.prototype.constructor`) are untainted (or that they’re only tainted by faithful polyfills). It’s sometimes possible to avoid such assumptions (aside from the fact that you always have to assume the realm is unpoisoned at evaluation time), but it is much more difficult than might be initially apparent, so usually is only done in code that has to run against a direct adversary (e.g. adblockers vs anti-adblockers).

**Comment by owiki** [comment]
> In my opition, use `regexp.constructor` could avoid that `RegExp` has been overwritten.
> 
> ```js
> class RegExp {}
> 
> const regexp = /a/
> const result1 = new regexp.constructor(regexp.source, reFlags.exec(regexp)) // will return a real RegExp object
> const result2 = new RegExp(regexp.source, reFlags.exec(regexp)) // will return an user-defined object, not a real RegExp object
> ```
> 
> As you said,
> 
> > In my opinion, the `constructor` may be changed, is it not safe?
> 
> You're right. We can't prevent user from changing the `constructor`or overwriting the `RegExp`. So I guess the author choose to only consider the common situations.

Thanks! you are right! `RegExp` can also be changed, that's more confusing...🤣 🤣 🤣

**Comment by bnjmnt4n** [comment]
I believe the reasons are largely what @bathos has mentioned.
