### ISSUE TITLE
Passing partially applied function defintions as an argument to other lodash functions leads to strange results

### ISSUE THREAD

**Issue by mikegin** [lodash/lodash#4867]
**Example 1:**
`_.map([1, 2, 0, 2], _.partialRight(_.gt, 0))
`
expected: `[true, true, false, true]`
actual: `[true, true, false, false]`

**Example 2:**
`
function greet(greeting, name) {
  return greeting + ' ' + name;
}
`
`
var greetFred = _.partialRight(greet, 'fred');
`
`
console.log(_.map(['hi', 'hello'], greetFred))
`
expected: `['hi fred', 'hello fred']`
actual: `['hi 0', 'hello 1']`

"lodash": "^4.17.19"

**Comment by ShaiDemri** [comment]
Not a fix but a workaround: If you pass the explicit callback inside the map function you'll get the expected output.

```
  function greet(greeting, name) {
    return greeting + " " + name;
  }
  const greetFred = _.partialRight(greet, "fred");
  const arr = ["hi", "hello"];
  console.log(
    _.map(arr, (g) => {
      return greetFred(g);
    })
  );

```
will print `[ 'hi fred', 'hello fred' ]`

**Comment by bnjmnt4n** [comment]
This behaviour is working as intended. _.map invokes its callback with 3 arguments. Applying `partialRight` on your function thus just adds the argument as the 4th argument, so your greet function does not work as intended.

```js
_.map(['hi', 'hello'], _.partialRight((...args) => console.log(args), "fred"))
// => Array(4) [ "hi", 0, (2) […], "fred" ]
// => Array(4) [ "hello", 1, (2) […], "fred" ]
```

You can try adding _.ary to limit the callback to accepting only 1 argument, so that your partialRight call works.
```js
_.map(['hi', 'hello'], _.ary(_.partialRight((...args) => console.log(args), "fred"), 1))
```
