### ISSUE TITLE
does _.throttle() work as expected?

### ISSUE THREAD

**Issue by sunderls** [lodash/lodash#4869]
To be honest I'm struggling to understand the behavior of how exactly `_.throttle()` works.

I tried some code and find some results which I'm not sure if it is expected

here is the code
```js
const start = Date.now()

// just log down the time passed and character.
const func = (char) => {
  console.log((Date.now() - start) + ':' + char)
}

const throttled = _.throttle(func, 10000, {leading: true, trailing: true})

setTimeout(() => throttled('A'), 0)
setTimeout(() => throttled('B'), 7000)
setTimeout(() => throttled('C'), 12000)
setTimeout(() => throttled('D'), 22000)
setTimeout(() => throttled('E'), 25000)
setTimeout(() => throttled('F'), 45000)
```

This works as expecteded https://medium.com/@ellenaua/throttle-debounce-behavior-lodash-6bcae1494e03

```
6:A
10006:B
22001:D
32002:E
45001:F
```

But when trigger `D` with 2 seconds  latter, we get some something different
```
setTimeout(() => throttled('A'), 0)
setTimeout(() => throttled('B'), 7000)
setTimeout(() => throttled('C'), 12000)
setTimeout(() => throttled('D'), 24000) // only D is triggered 1 second than prev example
setTimeout(() => throttled('E'), 25000)
setTimeout(() => throttled('F'), 45000)
```

here is what I got
```
7:A
10008:B
22002:C
24001:D  // D now triggered after C, just 2000, but delay of 10000 is passed
34001:E
45002:F
```

see the gap between C and D, I think the gap between each invoke should be at least 10000, but clearly it is not in this case.

anyone could help me clear things up?

**Comment by scplay** [comment]
I was just reading the source code of debounce, and find the same question, the source code is a little bit hard for understanding, But I guess the leading & trailing param not work like What we expect, the leading means at every round start, It would invoke immediatly, In the second section, when C invoke, after 10s it fired just meet the trailing of the first round, So when D was invoked, is just like you invoke A, It become the leading of the new round. So If you want it work as you will, Just change either leading or trailing false.

**Comment by SomeoneIsWorking** [comment]
throttle with `{trailing: false}` is just throttle
throttle with `{leading: false}` is just debounce
throttle with `{}` is whatever is available so if it can throttle then it will but if it can't throttle then it will debounce
Things like this turn me into an internet Karen making me want to complain for hours
I was wondering why my throttle was actually debouncing and turns out it was because I didn't set trailing to false
Have to pass an option to make the function do what it says on the function name
Imagine `addNumbers(1, 2, {divideThemInstead: false})`
And this is also standard practice because RxJS does it the same way too
