### ISSUE TITLE
_.add(0.2,0.1) not got the expect value

### ISSUE THREAD

**Issue by jch866** [lodash/lodash#4870]
_.add(0.2,0.1)   =>   0.30000000000000004

**Comment by Alan-Liang** [comment]
**TL; DR**: It's not a issue on lodash.

Try executing `0.1 + 0.2` on a REPL (`node -p 0.1+0.2`), you would get `0.30000000000000004`. JavaScript uses double-precision floating point numbers for all numbers (except for BigInt), which leads to [floating-point errors](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems). Consider using a [big decimal library](https://www.npmjs.com/search?q=big%20decimal) instead?

**Comment by jch866** [comment]
Isn't the library used to deal with this problem? And to ensure that the calculation results are correct;Otherwise this method _. Add cannot be used in the production environment

**Comment by Alan-Liang** [comment]
You should **never, ever** use native numbers except integers between [ `Number.MIN_SAFE_INTEGER`, `Number.MAX_SAFE_INTEGER` ] (at least in JavaScript) to represent accurate data. And Lodash is not a library for numbers.

Disclaimer: my opinion below, not affiliated with anyone else nor lodash: In my understanding, methods like `_.identity` and `_.add` are used to provide a clearer method to use (as opposed to using `(a, b) => a + b`), not to provide a bigdecimal library. For example, we would use `_.reduce(array, _.add, 0)` instead of `_.reduce(array, (a, b) => a + b, 0)`. The calculation **is** correct by the standards of floating-point arithmetic. If you are trying to decide equality for some values, you can use `Math.abs((0.1 + 0.2) - 0.3) < Number.EPSILON`.

Maybe add some explanation in the docs?

It seems that you are Chinese, so 中文解释：lodash 不是用来精确地进行数值计算的，类似 `_.add` 这样的方法只是用来简化代码、提升代码可读性的。大多数情况下这个精度就够用了。如果您是在做金融等等对数字极其敏感的领域，请用一个 big decimal 库。(如果您只是想比较两个值，可以这样写：`Math.abs((0.1 + 0.2) - 0.3) < Number.EPSILON` 。)

**Comment by jch866** [comment]
OK   thank you !

**Comment by Alan-Liang** [comment]
dupe of #4792
