### ISSUE TITLE
sumBy returns boolean instead of number

### ISSUE THREAD

**Issue by marian-galik** [lodash/lodash#4878]
`_.sumBy([true], (i) => i === true)`

Actual returns:

`true`

Expected:

`1`

**Comment by asvsfs** [comment]
#2058

**Comment by maximillianfx** [comment]
Hi! The behavior is really wrong, I made a simple solution here, can I take this like a bug-fix?

**Comment by LarryBattle** [comment]
Easiest solution is to always make sure your `iteratee` function always return a number.

Example: `_.sumBy([true], (i) => +(i === true)) // returns 1`

I created a PR for the fix here https://github.com/lodash/lodash/pull/4883

Anyone know how to run all the tests for lodash? I didn't have time to figure it out.
```
npm install && npm test
``` 
fails because it can't create `node lib/main/build-dist.js`.... :-(

**Comment by dopecodez** [comment]
Same here, I was looking at #4865 , and could not figure out how to run all the tests.
Only test script that worked was `test:wip` and that only seems to run a certain number of tests. In my case, the `at.test.js` was running but not the `pullAt.js` test. It'd be helpful for maintenance if you guys could clear up the tests.

**Comment by bnjmnt4n** [comment]
I believe this behaviour is working as intended for now. Although `_.sum` and `_.sumBy` are Math methods, they have been able to perform `_.sum(["a", "b"])`. I believe that summing should also occur with strictly defined and consistent types, and passing booleans or null and undefined to `_.sum` is always going to lead to unexpected issues.

**Comment by tshma-lex** [comment]
I am not sure how is this issue is closed (as well as the closed "duplicates" for null), as I can sum strings (it will concatenate). It might be expected behaviour, but if so - the documentation should change to reflect the return value is not always a number (it can also still return a null or undefined, if all the values are such)

**Comment by tshma-lex** [comment]
Where is the "fresh start" for this issue? I see many like issues (for instance, the sum() return 0 for null, and [null, null] yet return null for [null]), but all are closed, or marked as duplicate to other closed one. It seems no solution was expected. We use the overhead of lodash in our codebase, as it is stable - on opposition to many quirks of pure javascript. So, it's not an excuse that js has unexpected behavior to leave it like this.
