### ISSUE TITLE
There is a problem with the .pull method.

### ISSUE THREAD

**Issue by YYago** [lodash/lodash#4899]
Env:

* Lodash v4.17.19;
* Node v12.18.2 ;
* Windows 10 Pro;

**Example:**

```JavaScript
"use strict";

const lodash = require('lodash');
const a = [1, 2, 3, 4, 5]
let b = a;

for (let i = 0; i < a.length; i++) {

    lodash.pull(b, a[i]);
}
console.log('a ==>' + a)
console.log('b ==>' + b)
```

**Result:**

```
a ==>2,4
b ==>2,4
```

Why variable ` a ` is changed?

**Comment by LarryBattle** [comment]
Because `let b = a` creates a variable that's a reference to the value of `a`. 
To make them independent set `b` as a copy of `a`.

Example:
```js
const a = [1, 2, 3, 4, 5]
let b = lodash.clone(a);

for (let i = 0; i < a.length; i++) {
    console.log(JSON.stringify( {i, a, b, value: a[i]}))
    lodash.pull(b, a[i]);
}

console.log("Output: %s", JSON.stringify({a, b}));
```

Output of example.

```js
{"i":0,"a":[1,2,3,4,5],"b":[1,2,3,4,5],"value":1}
{"i":1,"a":[1,2,3,4,5],"b":[2,3,4,5],"value":2}
{"i":2,"a":[1,2,3,4,5],"b":[3,4,5],"value":3}
{"i":3,"a":[1,2,3,4,5],"b":[4,5],"value":4}
{"i":4,"a":[1,2,3,4,5],"b":[5],"value":5}

Output: {"a":[1,2,3,4,5],"b":[]}
```

Side note: The reason why you're getting 2,4 for `a` and `b` is because `lodash.pull()` removes elements from `a` while you're looping through `a`, so you end up only processing a subset of the elements.

More info:
- https://lodash.com/docs/#cloneDeep
- https://lodash.com/docs/#clone

**Comment by YYago** [comment]
I get it, I'm new to JavaScript 🤣 🤣  . Thanks.   @LarryBattle
