### ISSUE TITLE
documentation improvement: sortBy: document the how values are compared

### ISSUE THREAD

**Issue by gabor** [lodash/lodash#4913]
the documentation for `sortBy` does not specify how values are compared. this makes it hard to know how things will get sorted.

for example:

`_.sortBy([1,10,2,20])` returns `[1,2,10,20]`, which is correct.
but, it is different from what the javascript builtin  `.sort()` method returns.

**Comment by bnjmnt4n** [comment]
We use the standard lesser than operator for comparisons. JavaScript's built in `Array#sort` is unique and less intuitive in that it sorts by casting to a string first. I think lodash's behaviour is intuitve enough, and I'd prefer to avoid adding this documentation to the docs, since we have many sort methods.
