### ISSUE TITLE
`merge` is skipping elements in arrays

### ISSUE THREAD

**Issue by jsumners** [lodash/lodash#4933]
https://runkit.com/embed/y5oav2cr6u3m

```js
var _ = require('lodash');

console.log(
    _.merge(['foo', 'bar'], ['baz'])
)
```

Yields: `['baz', 'bar']`

Expected: `['foo', 'bar', 'baz']`

**Comment by freakymittal** [comment]
Function `merge` is to combine two objects, so merging two arrays is not its intentional purpose.
If you want to merge two or more array, look into `concat`.

**Reasoning for this behaviour.**
As arrays are also objects in javascript, the behaviour of `merge` is such that it overwrites the values of the key in an object with a value of the same key in another object (most right object with same key takes precedence). 
Now in this case the first array `["foo", "bar"]` has keys `["0", "1"]` (Try it by `Object.keys([1,2,3])` or `Object.keys(["foo", "bar"])`) which is basically the indices, so by that logic the resulting output makes sense cause the key `0` in the right most object which is `["baz"]` overwrites the value of the same key and as there is no value for key `1` (value `bar`), it remains the same.

**Comment by freakymittal** [comment]
Please close the issue, if i was able to clarify.

**Comment by jsumners** [comment]
When these two arrays are values of a `foo` property on two different objects, and those two objects are merged with this function, the new object will have a `foo` property set to an array like described above. Is this still intentional behavior? I see it as surprising behavior.

**Comment by freakymittal** [comment]
Didn't quite understand your last comment.

**Comment by jsumners** [comment]
```js
_.merge({ foo: ['foo' , 'bar'] }, { foo: ['baz'] })
// =>
{ foo: ['bar', 'baz'] }
```

**Comment by martingreilinger** [comment]
@jsumners  I believe you got the output mixed up, as your example is _merged_ as expected by lodash: 

```javascript
_.merge({ foo: ['foo' , 'bar'] }, { foo: ['baz'] });
// Object {foo: ["baz", "bar"]}
```

As @freakymittal and the documentation pointed out, 
> Array and plain object properties are merged recursively. Other objects and value types are overridden by assignment. 

Based on this, the array value of `foo` is merged as if you would merge the array directly ( as seen in your first comment).

As suggested previously, take a look at `Object.keys` as well as `_.assign`/`Object.assign` to get a better understanding how arrays behave when "merged".

**Comment by akkiei** [comment]
use _.mergeWith to merge arrays. the mergeWith method comes with a customizer to customize the behaviour.

`function customizer(objValue, srcValue) {
  if (_.isArray(objValue)) {
    return objValue.concat(srcValue);
  }
}
 
var object = { 'a': [1], 'b': [2] };
var other = { 'a': [3], 'b': [4] };
 
_.mergeWith(object, other, customizer);
// => { 'a': [1, 3], 'b': [2, 4] }`

**Comment by adityaprasoon** [comment]
@jsumners Please consider closing the issue if you are satisfied with the discussion here.

**Comment by jsumners** [comment]
I'm not. I think the documentation reads that it _should_ merge arrays attached to object properties. But I seem to be in the minority.

**Comment by bnjmnt4n** [comment]
The documentation (https://lodash.com/docs/4.17.15#merge) states that:

> it recursively merges own and inherited enumerable string keyed properties of source objects into the destination object

There is no special behaviour for arrays, as merge performs the operation using the keys of the source object, so `[1, 2]` would have the keys `["0", "1"]`, as will `{ 0: 1, 1: 2}`.

This is also shown explicitly in the example, where the two arrays are merged instead of concatenated:

```js
var object = {
  'a': [{ 'b': 2 }, { 'd': 4 }]
};
 
var other = {
  'a': [{ 'c': 3 }, { 'e': 5 }]
};
 
_.merge(object, other);
// => { 'a': [{ 'b': 2, 'c': 3 }, { 'd': 4, 'e': 5 }] }
```

The recommended approach for concatenating arrays would be `_.mergeWith`, as previously mentioned.
