### ISSUE TITLE
VM2670:1 MiniProgramError Illegal invocation

### ISSUE THREAD

**Issue by bravekingzhang** [lodash/lodash#4948]
```java
TypeError: Illegal invocation
    at lo (http://127.0.0.1:62750/appservice/common/vendor.js:3205:23)
    at VueComponent.f (http://127.0.0.1:62750/appservice/common/vendor.js:2940:89)
    at http://127.0.0.1:62750/appservice/common/vendor.js:1347:32
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:62750/appservice/common/vendor.js:1320:23
    at Array.forEach (<anonymous>)
    at Xe.handleEvent [as __e] (http://127.0.0.1:62750/appservice/common/vendor.js:1310:17)
    at Object.r.safeCallback (http://127.0.0.1:62750/appservice/__dev__/WAService.js:2:1911732)
    at http://127.0.0.1:62750/appservice/__dev__/WAService.js:2:2052326
    at r (http://127.0.0.1:62750/appservice/__dev__/WAService.js:2:1989147)
```

**Comment by FelixRilling** [comment]
Can you provide additional information about which lodash function was called? It is not visible from the minified stacktrace.

**Comment by Alan-Liang** [comment]
Is it a WeChat Mini Program/微信小程序? It might be an error in WeChat itself due to some search results on the internet such as these:

- https://developers.weixin.qq.com/community/develop/doc/00082c136bcf80625299d3f435b000?_at=1601835051605
- https://developers.weixin.qq.com/community/develop/doc/00028ea7460400fbff09511255b800
- https://developers.weixin.qq.com/community/minigame/doc/000cc66f33c248b9dc1976db251000

btw, could you provide a minimal reproducible sample code? That would help.

于 2020年10月5日 GMT+08:00 下午6:24:27, hz <notifications@github.com> 写到:

**Comment by may365-media** [comment]
> ```java
> 
> TypeError: Illegal invocation
> 
>     at lo (http://127.0.0.1:62750/appservice/common/vendor.js:3205:23)
> 
>     at VueComponent.f (http://127.0.0.1:62750/appservice/common/vendor.js:2940:89)
> 
>     at http://127.0.0.1:62750/appservice/common/vendor.js:1347:32
> 
>     at Array.forEach (<anonymous>)
> 
>     at http://127.0.0.1:62750/appservice/common/vendor.js:1320:23
> 
>     at Array.forEach (<anonymous>)
> 
>     at Xe.handleEvent [as __e] (http://127.0.0.1:62750/appservice/common/vendor.js:1310:17)
> 
>     at Object.r.safeCallback (http://127.0.0.1:62750/appservice/__dev__/WAService.js:2:1911732)
> 
>     at http://127.0.0.1:62750/appservice/__dev__/WAService.js:2:2052326
> 
>     at r (http://127.0.0.1:62750/appservice/__dev__/WAService.js:2:1989147)
> 
> ```
> 
> 

tricknotes

**Comment by bnjmnt4n** [comment]
There doesn't seem to be any lodash function called at all. Feel free to post more details if you can confirm that this is a lodash issue.
