### ISSUE TITLE
_.isEmpty returns false for numbers

### ISSUE THREAD

**Issue by ghafran** [lodash/lodash#496]
`console.log(_.isEmpty(123456));`

this returns `true`, should be `false`.

**Comment by msafi** [comment]
I expected _.isEmpty(100) to return false. After debugging, I realized it's returning true. Confusing.

**Comment by sankargorthi** [comment]
@msafi `!!100` would evaluate to `true`. I'm not sure I'd want `_.isEmpty(100)` to return `false`.

**Comment by jdalton** [comment]
> I expected _.isEmpty(100) to return false. After debugging, I realized it's returning true. Confusing.

Try reading the documentation first. Should save on confusion. The [_.isEmpty](lodash.com/docs#isEmpty) function is used to detect empty collections. If you do `_.map(100, _.identity)` it returns an empty array because `100` is seen as an empty with regards to collections.

**Comment by msafi** [comment]
@jdalton I thought I understood how the function works based on its name. That's why I didn't read every line in its documentation. I don't mean to argue. I'm just trying to say what happened.

Anyway, I still don't understand why it's more intuitive to have `_isEmpty(100)` be equal to `_.isEmpty(_.map(100, _.identity))`. 

Maybe that makes sense for other developers who do things differently from me.

**Comment by jdalton** [comment]
As I said it's about the value being considered an empty collection. `100` is empty you can't iterate over it, it's `_.size(100)` is `0`.

**Comment by huguangju** [comment]
I think it is renamed to ```_.isEmptyCollection()``` is more appropriate and easier to understand, ```0``` or ```1``` or ```123456``` should be considered illegal parameter

**Comment by jdalton** [comment]
Naw.

**Comment by Sija** [comment]
I’m confused by this too, not by semantics, but in terms of functionality, which begs for sth to check 0 cases as well as the rest of falsey values.
Maybe we could have `_.isBlank` or `_.isPresent` (see rails) to extend to this one case?
