### ISSUE TITLE
_.sumBy

### ISSUE THREAD

**Issue by LiST-GIT** [lodash/lodash#4983]
为什么_.sumBy的array参数不能是object?

**Comment by Alan-Liang** [comment]
Translation: Why the `array` parameter in `_.sumBy` could not be an object?

This parameter accepts an [array-like object](https://tc39.es/ecma262/#sec-lengthofarraylike). 0 is expected to be returned if it is not. What kind of object do you want to sum, and what is the expected behavior? Adding a piece of sample code helps.

**Comment by LiST-GIT** [comment]
```javascript
var o = { a: { value: 11 }, b: { value: 22 } };
_.sumBy(o, 'value');    // print 33
```

**Comment by Alan-Liang** [comment]
You should use [`_.values`](https://lodash.com/docs/4.17.15#values): `_.sumBy(_.values(o), 'value')`.

**Comment by LiST-GIT** [comment]
我知道可以这么写，我是想提意见可以加入直接输入object，还有_.minBy和_.maxBy这些都必须输入array，之前都要先_.values，这不是浪费效率么

**Comment by Alan-Liang** [comment]
That's intentional; see #21 #1812 #1506 #4468.

**Comment by LiST-GIT** [comment]
谢谢
