### ISSUE TITLE
meta: your method for per-method packaging? 

### ISSUE THREAD

**Issue by olets** [lodash/lodash#5088]
I imagine lodash has an automated system for packaging up each module and pushing updates to npm. Is the solution public? Can you point me to any info? Thanks!

**Comment by bnjmnt4n** [comment]
We used https://github.com/lodash-archive/lodash-cli to transform our monolithic lodash.js file into individual packages, but I've never used it for publishing individual modules, and lodash-cli is deprecated since it's getting kind of unwieldy to maintain. In the next version of lodash, we're likely deprecating individual `lodash.x` modules in favour of `import x from "lodash.x"`.
