### ISSUE TITLE
toArray splits string with emojis incorrectly.

### ISSUE THREAD

**Issue by Dhanraj-Naik** [lodash/lodash#5112]
var _ = require('lodash');

`_.toArray('🏴󠁧󠁢󠁥󠁮󠁧󠁿');`

**outputs as:**

["🏴", "󠁧", "󠁢", "󠁥", "󠁮", "󠁧", "󠁿"]

Same thing happens with 🏴󠁧󠁢󠁳󠁣󠁴󠁿 scotland , 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales flag.

**Comment by itsdeekay** [comment]
@Dhanraj-Naik These are [variation selectors](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) Unicode character used with emoji. The `_.toArray` method check for Unicode string and create array from the string with these blank Unicode characters. @jdalton @jashkenas Can we remove the Unicode  from `U+FE00 to U+FE0F` to be matched in string in regex so that the result does not contain these blank values?
