### ISSUE TITLE
_.throttle is being executed more than once every x seconds

### ISSUE THREAD

**Issue by mattfrancis888** [lodash/lodash#5134]
Lodash version: 4.17.21

Sandbox: https://codesandbox.io/s/embla-carousel-y-axis-react-forked-2jrbg?file=/src/js/EmblaCarousel.js:1337-1353

Issue Description: Using _.throttle with the "wheel event.". When using your mouse wheel or trackpad, the  console.log("delta Y neg") gets triggered multiple times rather than **once** every x seconds.

**Comment by jedierikb** [comment]
Unable to reproduce in this simplified case:
https://codesandbox.io/s/embla-carousel-y-axis-react-forked-4wgpt?file=/src/js/index.js

**Comment by mbehnasr** [comment]
@mattfrancis888  ] test your codesandbox and It works properly .

**Comment by gregor-mueller** [comment]
> Unable to reproduce in this simplified case: https://codesandbox.io/s/embla-carousel-y-axis-react-forked-4wgpt?file=/src/js/index.js

Please have another look!
You've set `leading` to false, **instead of `trailing`**.

I got the same issue and it is reproducible in your sample (if you change the option to `trailing: false`).
https://codesandbox.io/s/embla-carousel-y-axis-react-forked-fgrh3p?file=/src/js/index.js

Just scroll up and down within 2 seconds and you will be able to observe that it is wrongly being executed at the end again:

1. The value will update instantly 👍 
1. After the `wait` time (2s), it will update again 👎
