### ISSUE TITLE
_.clone  Bug?

### ISSUE THREAD

**Issue by interiv** [lodash/lodash#5138]
`a=[1,1];
b=a;
c=_.clone(a);

d=_.cloneDeep(a)

a[0]=2;
c[1]=2;

console.log(a,b,c,d);`
[2, 1] 
[2, 1]
[1, 2] 
[1, 1]

modify a ,but c is not change

why?

**Comment by sokarax** [comment]
> `a=[1,1];
> 
> b=a;
> 
> c=_.clone(a);
> 
> 
> 
> d=_.cloneDeep(a)
> 
> 
> 
> a[0]=2;
> 
> c[1]=2;
> 
> 
> 
> 
> 
> console.log(a,b,c,d);`
> 
> [2, 1] 
> 
> [2, 1]
> 
> [1, 2] 
> 
> [1, 1]
> 
> 
> 
> modify a ,but c is not change
> 
> 
> 
> why?
> 
> 
> 
> 
> 
> 
> 
>

**Comment by onwd** [comment]
@interiv

This is expected, because **[_.clone](https://lodash.com/docs/4.17.15#clone)** returns a shallow clone of any value that you pass into it, meaning that a new array instance will be created in your case. In your example, `c` and `a` are different array instances, hence re-assigning `a`'s child elements won't affect `c`, and vice versa.

**Comment by interiv** [comment]
thanks
