### ISSUE TITLE
using == in `startsWith.js` may have problems.

### ISSUE THREAD

**Issue by kaushik-rishi** [lodash/lodash#5199]
Link to current code:
- https://github.com/lodash/lodash/blob/master/startsWith.js#L33

Linked Pull Request
- https://github.com/lodash/lodash/pull/5198

**Comment by itsdeekay** [comment]
Hi @kaushik-rishi

Can you please site any reason or problem which could be faced with == as it seems no problem with the use of ==. If you could provide some example then it would be useful.

**Comment by baremaximum** [comment]
@itsdeekay using `==` instead of `===` allows for type coercion, and could lead to security vulnerabilities and unexpected, very hard to debug errors arising from some of JavaScript's more counterintuitive behaviors.

For example,

```
let result = _.startsWith("true", true) // target is a boolean, not a string
console.log(result) // prints true, since JavaScript only compares value, not type when == is used instead of ===
````

Anyone using this function would expect the example above to return false. This is a serious, yet easily remediable solution.

**Comment by itsdeekay** [comment]
Well this is expected behavior, the function check whether the the string starts with target string. So both the arguments should be string. At line https://github.com/lodash/lodash/blob/master/startsWith.js#L32 you can see the target argument is converted to string before doing any operation. You are suggesting that this function take any kind of arguments and check if there are strings otherwise return false even if the arguments could be converted to string

**Comment by baremaximum** [comment]
This may be expected by the authors, but it certainly wouldn't be expected by most people using this function. Here are other examples that pass unexpectedly:

```
let x = _.startsWith("undefined") // true


let x = _.startsWith("[object Object]", {}) // true
```

No one would expect this function to cast the target to a string.  The documentation doesn't suggest that behavior at all, and even if it did, many users would not understand what that means.

It's not hard to imagine a situation where someone would write a function that returns a string starting with the word "undefined", and they use this function to test their function. The test would pass even if their function returns nothing.

It's not hard for users to cast values to strings themselves if they need to. Most users probably do this already since they expect to have to pass a string.

I think that the function should throw a TypeError if the inputs aren't strings. This would guarantee intuitive behavior. It would also eliminate the need to create a template string every time the function is run, so there would probably be a performance improvement. 

The only downside would be that making this change would break any existing code that assumes this function will do the casting for them.

**Comment by itsdeekay** [comment]
@baremaximum totally agree with you in this case. Let's see what the contributor's has to say about this. 
@jashkenas @jdalton could you look into it and provide your feedback?

**Comment by airarrazaval** [comment]
@baremaximum It is mentioned in the documentation

https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/startsWith.js#L1-L8

This method explicitly mentions that it treats both arguments as strings.  This is the expected behavior and I doubt it will change.   I think the responsibility relies on the implementer rather than the implementation.

**Comment by baremaximum** [comment]
@airarrazaval There is a very big difference between telling uses that a function expects a string, and telling uses that your function will coerce whatever it gets into a string.

I would bet a good amount of money that out if 100 developers read this documentation, less than 10 would correctly guess how this function behaves.
