### ISSUE TITLE
the value is array, but its type is string? WHEN?!

### ISSUE THREAD

**Issue by wqcstrong** [lodash/lodash#5211]
I don't know the reason of use `Array.isArray(value)` to exclude array in [`isString#L20`](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/isString.js#L20), hope response. 

Thx!

**Comment by alainrk** [comment]
I think it's because:
- an array is an object, so `typeof [] === 'object'`
- you can have strings as literal but also as String objects, as tested afterwards with `getTag(value) == '[object String]'`
- so you're checking for `type === 'object'` in order to test for String object type, but excluding arrays beforehand

**Comment by itsdeekay** [comment]
But use of `getTag(value) == '[object String]' `will take care of that even we don't need to test type object so using only this `getTag(value) == '[object String]'` and `null` condition is suffice

**Comment by wqcstrong** [comment]
> But use of `getTag(value) == '[object String]' `will take care of that even we don't need to test type object so using only this `getTag(value) == '[object String]'` and `null` condition is suffice

I know that, and do it so in the work. Just for explore and fun 😁

**Comment by wqcstrong** [comment]
> I think it's because:
> 
> * an array is an object, so `typeof [] === 'object'`
> * you can have strings as literal but also as String objects, as tested afterwards with `getTag(value) == '[object String]'`
> * so you're checking for `type === 'object'` in order to test for String object type, but excluding arrays beforehand

I agree. Actually, I also thought so at the begining! But then I still think it's not necessary to do that at all, since the `getTag(value) == '[object String]'` is sufficient.

**Comment by itsdeekay** [comment]
@bnjmnt4n can we make improvement in function and remove unnecessary condition or it has some specific use case which we are missing?

**Comment by tshinnic** [comment]
Please note duplicate issue #4604 having the same query.

I've found the original change https://github.com/lodash/lodash/commit/14e62ae8d24ade984d67dba3b0955c6df3063c1d back in Sep 2015. Rather cryptic, yes?

The mystery change is at line 8932 in that commit, but note the lines changed below there - the interesting reference to stringToArray() in function toArray(). 

It looks like the need for  !Array.isArray(value)  has less to do with "what is logical for isString()" than to how isString() is used _within lodash_, such as in [toArray()](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/toArray.js#L43-L45)

I don't see any tests for [isString()](https://github.com/lodash/lodash/blob/master/test/isString.test.js) that seem related. Does this test of [toArray()](https://github.com/lodash/lodash/blob/master/test/toArray.test.js#L29-L33) give any clues?

Summary: I think there's a reason for it, but related to _usage patterns_ rather than _logic_.

**Comment by itsdeekay** [comment]
Yeah, it could be. That's why we wanted to know the exact reason for its inclusion
