### ISSUE TITLE
_.chunk([], 5) returns []

### ISSUE THREAD

**Issue by mboudreau** [lodash/lodash#5293]
My expectations for a chunking function whose whole purpose is suppose to return a 2D array is to return a 2D array no matter the circumstance.  But I discovered that if you give it an empty array, it just returns an empty 1D array which breaks expectations and typings.

I can create a quick PR to fix this but would be keen to hear about why this.

**Comment by lesha-co** [comment]
If I understand you correctly, you want it to return `[[]]`, but in my opinion, that would not be correct. 

`[[]]` has length of `1`. It has one "row" that happens to be empty. `[]` is more correct in this sense as it has length of 0 and therefore no particular dimensionality. 

Returning null/undefined is not an option either because you can't map over its return.

**Comment by mboudreau** [comment]
@lesha-co 
I disagree.  I understand that `[[]]` has a length of `1`, but that doesn't really matter in a _2D array_ where we expect rows _and_ columns to be available.  `[[]]` is still length of `0` since you wouldn't never evaluate the row only, but the row-column combination which is _the whole point of a 2D array in the first place_.  

> Returning null/undefined is not an option either because you can't map over its return.
I wholeheartedly agree with this point and this is the exact argument I'm trying to make about returning an _empty 2D array_ instead of an _empty 1D array_.  You cannot use this function without adding your own conditional because, in your own words, _you cannot map over null_.  Same as trying to map over `_.chunk([], 5).map(x => x.map(someFunction))` which will fail because one of the key dependencies, the columns, are now empty.  So now this simple bit of code needs to be much more complex in cases where the chunked array is empty as I now need to make sure it always returns a 2D array:

```
const chunks = _chunk([], 5);
if(!chunks.length) {
chunks.push([]);
}
chunks.map(x => x.map(someFunction));
```

This is unacceptable IMO since the typing is now completely wrong as well as the assumption that a 2D array will always be spat out.

**Comment by lesha-co** [comment]
`[[]]` comes with its own bag of disadvantages if not treated properly. Suppose you have a list of items that you want to arrange in 2d grid and use `chunk()` to break it up into lines of certain length.

Let's now assume `chunk()` returns `[[]]` for empty arrays.
```
const grid = chunk([],x) // = [[]]
```
I now want to manually add a row:
```
grid.push([item1, ..., itemN])
console.debug(grid) // [[], [item1, ..., itemN]]
```
oh no, this looks like a problem — I've got an empty row and added row is in `grid[1]` not `grid[0]`. This __will__ bite you in one of many ways. You could mitigate it but it's not convenient:
```
const grid = chunk([],x) // = [[]]
const newLine = [item1, ..., itemN]
if(grid.length == 1 && grid[0].length == 0) {
    grid[0] = newLine
} else grid.push(newLine)

```
And this is just to add a row.

Now let's say we do have a grid with one row: 
```
[
    [1,2,3,4,5]
]
```
You want to remove it. What do you do? You can just `.pop()`. Or `.splice()`. Real simple. But then you've left with an empty array (`[]`) and you don't want that, you want `[[]]`. This is another edge case when you need to test for "last" row and another source of bugs.

---
Now, your case

```
const chunks = _chunk([], 5);
```
This will create an empty array. 
As I said, empty arrays have no dimensionality because they don't have _anything_, exactly because of examples above. You have a 2d array and remove the last row, what is left? An empty array: `[]`.

```
chunks.map(x => x.map(someFunction));
```
`chunks` is an empty array and `map()` will work fine. That is, it will **do nothing but return an empty array**. `someFunction` won't be called at all because there are no elements to process.
