### ISSUE TITLE
CVE-2021-41720 Has been Rejected

### ISSUE THREAD

**Issue by plambrechtsen** [lodash/lodash#5325]
Even though you deleted the two issues I raised no matter how polite I was, you still deleted it nonetheless:

https://github.com/lodash/lodash/issues/5294
and
https://github.com/lodash/lodash/issues/5296

Mitre has finally responded saying they will reject the CVE after I repeatedly asked why the original requestor had asked for it to be rejected and Mitre had ignored them.

`
After further internal review and discussion, the description has been changed to:

** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.

Expect the CVE entry to be updated on http://cve.mitre.org in the next few hours.
`

I am sure you don't care but I consider this a win.

**Comment by jdalton** [comment]
Thanks for the update! Yes @plambrechtsen I'm still trying to work through a meaningful approach to bogus CVE noise. Having a record seems to attract more attention than not. I've also had individuals solicit exploits in the issue tracker. Since most are bogus and context unaware my current strategy is to remove them. Once you realize that these CVE don't actually represent real risk and are only there to justify the existence of a start-up or someone's promotion vehicle (feature set) you lose a lot of motivation in dealing with them.
