### ISSUE TITLE
_.setWith does not allow to prevent array creation by _.set

### ISSUE THREAD

**Issue by arturohernandez10** [lodash/lodash#5338]
I have seen this issue come up several times here. And the response has been to use the customizer. Except that the customizer is being called with a string.

_.setWith({}, ['prop',9,'prop','9','prop'],'a', console.log)

undefined 'prop' {}
undefined '9' []
undefined 'prop' {}
undefined '9' []

I did not define this structure. But I will have to write a new version of setWith just to keep the code clean. Look I disagree with the decision to default numbers to arrays. This is free software and I appreciate that, particularly since there "was" a workaround. So I really had nothing to say.

But there is no workaround.

Would you take a pull request?

**Comment by jedwards1211** [comment]
@jdalton  I disagree with this too, since there's no way to force `_.set` or `_.setWith` to always create an object for missing string keys and always create an array for missing numeric keys.

It seems like the way `_.set` decides to create an array or object is modeled after [the way array property assignment is defined in the spec](https://tc39.es/ecma262/#sec-array-exotic-objects-defineownproperty-p-desc).

I kind of get that, but it makes `_.set`/`_.setWith` unusable for the common case where I need it, where some/all of the path elements come from variables, and I always intend for string keys to represent object properties and numeric keys to represent array indices.

**Comment by mechabubba** [comment]
> there's no way to force _.set or _.setWith to always create an object for missing string keys while always creating an array for missing numeric keys.

thirding this. the customizer is completely useless for me simply because the keys are coerced to a string internally. for the curious: you can see this string coercion in the `baseSet` method [here](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/dist/lodash.js#L3977), which calls the `toKey` method [here](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L6753-L6757).
