### ISSUE TITLE
Inconsistent _.trimEnd behavior

### ISSUE THREAD

**Issue by sudarshankarande** [lodash/lodash#5350]
When we use the `_.trimEnd` function with specific string then it gives us the invalid output.
Below are the different examples where I found the inconsistencies - 
Eg- 1
`let name = 'my-engine:my-engine/$site';`
`_.trimEnd(name, '/$site');`

Actual output - `my-engine:my-engin`
Expected output - `my-engine:my-engine`

Eg- 2
`let name = 'my-engine:my-engines1/$site';`
`_.trimEnd(name, '/$site');`

Actual output - `my-engine:my-engines1`
Expected output - `my-engine:my-engines1`

Eg- 3
`let name = 'my-engine:my-engines/$site';`
`_.trimEnd(name, '/$site');`

Actual output - `my-engine:my-engin`
Expected output - `my-engine:my-engines`

Please let me know if this is expected behavior or an actual bug?

**Comment by davadams97** [comment]
According to the documentation, the second parameter (chars) expects the characters to trim. 

In the following cases:

Eg- 1
```
let name = 'my-engine:my-engine/$site';
_.trimEnd(name, '/$site');
```
Actual output - `my-engine:my-engin`
Expected output - `my-engine:my-engine`

The actual output is correct since the last character "e" in "my-engine:my-engine" is a character provided to the character set ($site). 

Eg- 3
```
let name = 'my-engine:my-engines/$site';
_.trimEnd(name, '/$site');
```

Actual output - `my-engine:my-engin`
Expected output - `my-engine:my-engines`

The actual output is correct since the last two characters "es" in "my-engine:my-engines" are characters provided to the character set ($site).  

It is important to remember that the second parameter is a character set and not a string.
