### ISSUE TITLE
Feature Request: `amend` family

### ISSUE THREAD

**Issue by ElectricCoffee** [lodash/lodash#5367]
Something I think would be nice to have, keeping in the spirit of functional programming, is a way to update lists non-destructively.

For this I propose the `amend` family of functions, which take a collection, position or criteria, and returns an updated collection, which leaves the original untouched.
```js
const a = _.range(6);
const b = _.amend(a, 2, 'X');

console.log(a); // prints [0, 1, 2, 3, 4, 5]
console.log(b); // prints [0, 1, "X", 3, 4, 5]
```
This could possibly also work on strings, which are already immutable:
```js
const c = 'bat';
const d = _.amend(c, 0, 'c');

console.log(c); // prints "cat"
```
Furthermore, an `amendMany` could be used to update multiple values at once:
```js
const d = _.range(6);
const e = _.amendMany(d, [0, 2, 4], 'xyz')

console.log(e); // prints ["x", 1, "y", 3, "z", 5]
```
And lastly an `amendWhen`:
```js
const f = [1, 2, 3, 0, 7, 1];
const g = _.amendWhen(f, (x) => x > 2, (x) => -x);

console.log(g); // prints [1, 2, -3, 0, -7, 1]
```
Admitedly, `amendWhen` is less useful, as it can be achieved with some clever application of mapping and reduction, but it's sill nice and straightforward

**Comment by ajitjha393** [comment]
@ElectricCoffee I also think this addition can be nice to keep in `lodash` 

I just want to point out that for `amendMany` when we are trying to update multiple values, we should accept a list as a 3rd argument as well.

The reason being that in JS we don't have char, everything is considered as string which means these can be of variable length 
Hence we can't split each of these char in string and assign to these positions 

So Instead of `xyz` we should accept `['x', 'y', 'z']` 
This way we will have clear distinction of what string we want to assign explicitly

Here is my implementation for the above utility ->
ps : Not covered all corner cases but the crux of the utility and maintained immutability

```js 

// Just few helper functions which we can replace with lodash ones ofc :b

function replaceAt(str, pos, replacement) {
    return str.substr(0, pos) + replacement + str.substr(pos + replacement.length);
}

function getAllIndexes(xs, predicate) {
    return xs.reduce((acc, x, i) => {
        if(predicate(x)){
            acc.push(i)
        }
        return acc
    }, [])
}

// ->

function amend(xs, pos, val) {    
    if(pos >= xs.length){
        throw new Error(`pos ${pos} is out of bounds`)
    }
    
    if(typeof xs === 'string') {
        return replaceAt(xs, pos, val)
    }else {
        let newCollection =  xs.slice()
        newCollection[pos] = val
        return newCollection
    }
        
}

function amendMany(xs, posList, repList) {
   return posList.reduce((acc, pos, index) => {
		acc[pos] = repList[index]
		return acc  
	},  xs.slice())
    
}


function amendWhen(xs, predicate, mapFn) {
    const posList = getAllIndexes(xs, predicate)
    const repList = posList.map(p => mapFn(xs[p]))
    return amendMany(xs, posList, repList)
}



```

![image](https://user-images.githubusercontent.com/42679346/151713442-4e352533-f311-46f8-8ee8-ecf6f5478df3.png)

**Comment by ElectricCoffee** [comment]
@ajitjha393 My idea was just that since strings also act as arrays for the purpose of iteration, a string can just be used in place of an array in both contexts. But I do see the case where you want to splice a whole string into one spot in the array not being easily feasible with a bare string, so you might be right.
