### ISSUE TITLE
`_.map` implementation in lodash doesn't consider the case of empty array elements 

### ISSUE THREAD

**Issue by ajitjha393** [lodash/lodash#5369]
`Array.prototype.map()` :
Doesn't iterate over the empty sparse array declared and hence map transformation doesn't happen 

![image](https://user-images.githubusercontent.com/42679346/151020453-a0af3651-d6d3-4a4d-be0d-126801c6d429.png)

In case of `_.map()` : 
 It only considers the length property and iterates it with a while loop even tho no actual value exists for that location in the array which might not be mathematically sound.

![image](https://user-images.githubusercontent.com/42679346/151020658-12640d9d-f6a8-4369-86d6-bbcfddaf1f56.png)

**Comment by davadams97** [comment]
When we use the Array construction method for creating an array, JavaScript creates an array with the specified slots each set to undefined, since they do not have a value. We can confirm this by the following:

```
var arr = new Array(2);
console.log(arr[1]); //undefined
```

Now, in JavaScript, if we were to create an array as the following, we get an interesting result,

```
var arr = [undefined, undefined, undefined];
console.log(arr.map(x => 1)); // [1,1,1]
```

To me this is interesting since JavaScript behaves differently. It is worth spending the time to see how JavaScript performs the `map` operation behind the scenes.

**Comment by ajitjha393** [comment]
@davadams97 
> When we use the Array construction method for creating an array, JavaScript creates an array with the specified slots each set to undefined, since they do not have a value. We can confirm this by the following:

Hey, it seems like each empty slot is set to `undefined` but it is not the case,
Javascript has the concept of sparse arrays, which basically means that it doesn't need to have the elements in a continuous memory location, hence the index in the array is just for lookup key just like an object.

So `empty` basically means nothing is present or initialized or created at the location yet, consider it as a hole.

And when you try to access from the empty slots array, you see undefined because of `Prototypal Inheritance` in Js.

So when we can't find that index lookup on the array itself we go down the prototype chain until the ` __proto__` of Object is encountered and it sends back undefined  

Here is the proof that it send undefined from `__proto__` not the lookup value stored in the Array : 

I have set up a proxy which returns "Returning value" whenever the index is not present on the Array itself

Hence basically we don't have anything created yet for that empty spot, and `_.map` should pragmatically not produce mapping transformation 

![image](https://user-images.githubusercontent.com/42679346/151289980-ef63645c-073e-4e99-8edf-a26c64abbfa7.png)

**Comment by davadams97** [comment]
@ajitjha393 Thank you for sharing your thought on the internal workings of javascript. I am new to this concept and I really appreciate the detailed explanation that you left. I guess you learn something new every day! :)

I did my own tests as well, and I agree with you that an "hole" should not map to anything since it is not a defined value.
