### ISSUE TITLE
_.get accesses properties on prototype chain

### ISSUE THREAD

**Issue by bytasv** [lodash/lodash#5421]
Hello,

I accidentally bumped into a really weird bug which I tracked down to `_.get` method.

Seems that given a path that at the end includes the property name of something that lives on the object prototype, `get` method will return that value.
I.e.:
```
a = { b: { c: 'd' } }

_.get(a, 'b.c.link')

// -> ƒ link() { [native code] }
```
I was able to reproduce this in my code as well as on https://lodash.com/docs/4.17.15 directly in the console

This seems like a bug and maybe even a potential security hole?

Thank you

**Comment by crazoter** [comment]
I don't think this is an error. According to lodash documentation for [_.get](https://lodash.com/docs#get):
> Gets the value at path of object. If the resolved value is undefined, the defaultValue is returned in its place.

The `link()` you have obtained there is the string prototype's [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/link). As far as Lodash (or JS for that matter) is concerned, the function obtained is a valid value.

Some more examples: you can get the functions of a string using lodash get: 
- `_.get("text", "split")`
- `_.get("text", "indexOf")`

Seems intentional and I don't foresee any security flaws here.

**Comment by bytasv** [comment]
I can't figure out how this could be exploited regarding a security hole, but I'd still consider this a bug and unexpected behavior. It is really non-intuitive to be able to access props on object prototype this way 🤔
