### ISSUE TITLE
Sorting is not working if we have a single character.

### ISSUE THREAD

**Issue by santoshraulo07** [lodash/lodash#5444]
`var priceList = [{"Date":"5/24/2022","Client Name":"a","Client_Country":"India","Deal Description":"acquired by","Deal Value":"$22 million","Deal Size ($m)":"$22","Category":"X","FileCount":"0","Deal Records":"Complete","RowNumber":0,"isChecked":false},{"Date":"5/18/2022","Client Name":"Heetch","Client_Country":"Cote d'Ivoire","Deal Description":"acquired by","Deal Value":"$112 million","Deal Size ($m)":"$112","Category":"G","FileCount":"0","Deal Records":"Complete","RowNumber":1,"isChecked":false},{"Date":"5/18/2022","Client Name":"Heetch","Client_Country":"Cote d'Ivoire","Deal Description":"acquired by","Deal Value":"$112 million","Deal Size ($m)":"$112","Category":"O","FileCount":"0","Deal Records":"Complete","RowNumber":2,"isChecked":false},{"Date":"5/18/2022","Client Name":"HCL","Client_Country":"Cote d'Ivoire","Deal Description":"acquired by","Deal Value":"$550 million","Deal Size ($m)":"$550","Category":"H","FileCount":"0","Deal Records":"Complete","RowNumber":3,"isChecked":false},];
SortedCollection = orderBy(collection, ["Client Name"], ["asc"]);
`

client Name "a" stays on top after soring desc and at the bottom if sorted desc.

**Comment by thevinitgupta** [comment]
This might because of the fact that in the `ascii` value of `a` is 97 whereas the ASCII values of `A-Z` ranges from `65 to 90`.
Technically, this means `a>A`.

**Comment by crazoter** [comment]
@thevinitgupta is correct. The issue is due to the mixing of cases when you're making your comparison. Consider converting everything to either lower or uppercase when performing your orderBy function.

Modified example based on the [documentation](https://lodash.com/docs/4.17.15#orderBy):
```
var users = [
  { 'user': 'A',   'age': 48 },
  { 'user': 'a', 'age': 34 },
  { 'user': 'Z',   'age': 40 },
  { 'user': 'barney', 'age': 36 }
];
 
// Sort by `user` in ascending order and by `age` in descending order. Notice that I transform the `user` field to lower case before comparing so that the case doesn't interfere with the order.
_.orderBy(users, [(item) => item.user.toLowerCase(), 'age'], ['asc', 'desc']);
// => objects for [['barney', 36], ['barney', 34], ['fred', 48], ['fred', 40]]
```

This is not a bug because...well, string comparison has always been like that in JS, and there is no mention in the documentation that Lodash intends to make ordering of strings case insensitive either (unless someone intends to add a new feature for case insensitive comparison).

**Comment by santoshraulo07** [comment]
Thanks!!
