### ISSUE TITLE
cloneDeep doesn't copy the custom property in an Array.

### ISSUE THREAD

**Issue by hansf14** [lodash/lodash#5505]
To reproduce the issue,

    let arr1 = [1];
    console.log(snapshot(arr1));

    //arr1.customProp = "custom";
    arr1["customProp"] = "custom";
    console.log(snapshot(arr1));
    console.log(arr1);

    function snapshot(obj) {
        return _.cloneDeep(obj);
    }

Is this an intended behaviour?
I think if lodash supports this it would be much helpful to make a snapshot of an object when debugging.

**Comment by mehrankhaksar** [comment]
let arr1 = [1];
console.log(Array.isArray(arr1)); // true - type of arr1 is array of length 1
console.log(snapshot(arr1));

arr1["customProp1"] = "custom1";
arr1["customProp2"] = "custom2";

console.log(snapshot(arr1));
console.log(arr1.length); // still length is 1

function snapshot(obj) {
	return _.cloneDeep(obj);
}

Because the cloneDeep function thinks it's currently an array, So it doesn't treat it like an object and because the length of the array is still 1, It only copies the first one and ignores the rest.
