### ISSUE TITLE
Is it correct that lodash v4.0 is still base on underscore 1.8.3?

### ISSUE THREAD

**Issue by tedyyu** [lodash/lodash#5579]
```
/**
 * @license
 * Lodash <https://lodash.com/>
 * Copyright OpenJS Foundation and other contributors <https://openjsf.org/>
 * Released under MIT license <https://lodash.com/license>
 *** Based on Underscore.js 1.8.3 <http://underscorejs.org/LICENSE>**
 * Copyright Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
 */
```
seen in 
https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js 
https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.js

latest underscore version is v1.13.6.
Is it possible that this is somehow not updated when generating the production js file?

another question: 
I assume lodash has no dependency on underscore, right? 
"Base on" just means the API compatibility. Correct me if I'm wrong.

**Comment by Arun-Rangasamy** [comment]
@jdalton @jashkenas  @falsyvalues  @bnjmnt4n   @blikblum... 

Our security scanning team is behind us, since the underscore.js version 1.8.3 has got the below vulnerability:

CVE-2021-23358: Affected version of Underscore.js are vulnerable to Arbitrary Code Injection via the template function, particularly when the variable option is taken from _.templateSettings as it is not sanitized.

Can you please confirm if latest release of lodash is affected because of this? and how can we remediate this vulnerability?

**Comment by falsyvalues** [comment]
Hi @tedyyu lodash doesn't have underscore as dependency.

@Arun-Rangasamy Currently we have no opened CVE in lodash https://security.snyk.io/package/npm/lodash

**Comment by jaceklubzinski** [comment]
Hi @falsyvalues 
thanks for the clarification, additional question, if lodash doesn't have underscore library as a dependency, why it keeps showing up there triggering different security scanners :thinking: 
Is there any way to get rid of this message?

![obraz](https://github.com/lodash/lodash/assets/13852206/abcb7a6c-e292-43b7-9cf3-38fcc5e7ae0b)

**Comment by Trott** [comment]
> if lodash doesn't have underscore library as a dependency, why it keeps showing up there triggering different security scanners 🤔

This seems like a bug in the security scanner you are using, not lodash.

**Comment by jdalton** [comment]
@jaceklubzinski as @Trott wrote this is a bug in the security scanners.

**Comment by jrrodgers68** [comment]
For clarification, this text is NOT coming from a security scanning tool -- its the EXACT text that shows up under the license section on the NPM web site for lodash:  https://www.npmjs.com/package/lodash-core.

It would be nice if that could be changed so that this text does get copied into bundles when they are generated.

**Comment by umeshnevase** [comment]
@jdalton @Trott @falsyvalues 
Please can you check this vendor directory, the underscore js is used 1.8.3 version.
https://github.com/lodash/lodash/blob/main/vendor/underscore/underscore.js it is also used for performance analysis in lodash script
