### ISSUE TITLE
some method is incorrect 

### ISSUE THREAD

**Issue by jiangtutu0529** [lodash/lodash#5597]
VERSION = '^4.17.21';

Problem description
When I use the some method, as shown in the figure, the result does not run correctly
example:
const arr = [true,fasle,fasle]
const res = _.some(arr,true)--->res = false
I think the res may be true
<img width="1191" alt="企业微信截图_16752421647760" src="https://user-images.githubusercontent.com/45190794/216001408-90d980b5-816b-4f94-901a-4aa43f2ca6f1.png">

**Comment by WheelerCC** [comment]
I'm a little surprised this doesn't do a little more than just return an unexpected result (I'd have thought something would either throw an error your intellisense would start complaining!). 

Either way, the reason this isn't behaving as you'd expect is that the second argument of `_.some()` is a 'predicate', or in other words some generic function. `_.some(..)` will then call this predicate functions with a few parameters, and if the predicate returns something truthy `_.some(..)` will return true. Otherwise, it will keep going through each index of the provided array until your predicate function returns something truthy, otherwise returning false. See [here](https://github.com/lodash/lodash/blob/master/some.js) for the actual implementation.

To apply this to what you're trying to achieve, you could do something along the lines of 

`_.some(arr, (elementOfArray, indexOfArray, array)=>{
    if (elementOfArray === true) {
        return true
    } else {
        return false
    }
})`

Or in a probably not robust shorthand, but okay in the example you've given...

`_.some(arr, (i)=>i)`

**Comment by PunitSoniME** [comment]
@jiangtutu0529 

Can you give my library a try ?
It's giving expected result if you use my library.

I have made an alternative of lodash.

https://www.npmjs.com/package/alt-lodash

Please check github to report any issue or suggestion
https://github.com/PunitSoniME/alt-lodash

Don't forget to star the repository.

**Comment by vaynevayne** [comment]
@PunitSoniME  I've been tortured by lodash for a long time. I'd love to try, but your file won't open. https://alt-lodash.vercel.app/home#isEmpty

**Comment by PunitSoniME** [comment]
> @PunitSoniME I've been tortured by lodash for a long time. I'd love to try, but your file won't open. https://alt-lodash.vercel.app/home#isEmpty


Thanks for your reply brother,
Actually I have renamed the library from `alt-lodash` to 'purekit'

https://purekit.vercel.app/home#isEmpty

**Comment by vaynevayne** [comment]
@PunitSoniME  can you set window._ = your umd name ? 
<img width="481" alt="image" src="https://github.com/lodash/lodash/assets/124666577/35a3ab82-46f8-42d0-9138-ab25a7b1dd2b">

**Comment by PunitSoniME** [comment]
> @PunitSoniME can you set window._ = your umd name in your docs site? <img alt="image" width="481" src="https://user-images.githubusercontent.com/124666577/240494181-35a3ab82-46f8-42d0-9138-ab25a7b1dd2b.png">

@vaynevayne 
Done

If you found any issue, please raise an issue [here ](https://github.com/PunitSoniME/purekit)

**Comment by vaynevayne** [comment]
@PunitSoniME  thanks, but  It's not for me. What I expect is `isEmpty(1) == false`
 <img width="443" alt="image" src="https://github.com/lodash/lodash/assets/124666577/619c82e6-6873-4bb1-bdeb-fc8140baa3f3">
