### ISSUE TITLE
_.sortBy gives different result when same identity is passed again.

### ISSUE THREAD

**Issue by ashuvyaspm45** [lodash/lodash#5621]
Sharing the example code below:
```
let array = ['json copy 2', 'A', 'json copy 1', 'json copy']
_.sortBy(array, (e) => [e, e])
(4) ['A', 'json copy 1', 'json copy 2', 'json copy']
_.sortBy(array, (e) => [e])
(4) ['A', 'json copy', 'json copy 1', 'json copy 2']
```
The position of `json copy` has changed.

**Comment by ben-yocum** [comment]
Unable to reproduce. [See here](https://codesandbox.io/s/lodash-playground-forked-8ejyzm). Open the console to view output. Can you provide a working example? 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7013825/227385772-f28e02ab-a8e0-4775-9be5-2bbe152d72d9.png">

**Comment by PunitSoniME** [comment]
@ashuvyaspm45 

`sortBy` never mutates the collection, it just give you new collection, so instead of logging array directly will give you source itself, not the result.

So store the data in new variable and console that variable

```ts
let array = ['json copy 2', 'A', 'json copy 1', 'json copy']

let result1= _.sortBy(array, (e) => [e, e])
console.log(result1)
// (4) ['A', 'json copy 1', 'json copy 2', 'json copy']

let result2 = _.sortBy(array, (e) => [e])
console.log(result2)
// (4) ['A', 'json copy', 'json copy 1', 'json copy 2']

```

**Comment by ben-yocum** [comment]
Alright, I've figured it out. You're not passing the right `iteratee` parameter (the second parameter). I'm not sure why your function returns `[e, e]` and `[e]`, `_sortBy()` does not have any special behavior when arrays are returned from the iteratee function. All it does is convert all the `e` values into `[e, e]`.

What's happening is, eventually `_sortBy()` calls javascript/s built-in `Array.prototype.sort()`. [Source code.](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L932)

You've passed a function to transform the results from `e` to `[e, e]` (for example, from`'json copy'` to `['json copy', 'json copy']`). Javascript's sort function converts all non-string array members into strings. `String(['json copy', 'json copy']) returns `'json copy,json copy`.

Well, as it turns out, `json copy,json copy` is later than `json copy 2,json copy 2`. So the array is in fact being sorted correctly. You just can't return `[e, e]` like that. 

What behavior are you trying to achieve?

**Comment by anmol242** [comment]
@ashuvyaspm45 The difference in results you're seeing when using _.sortBy with the same identity function is due to the behavior of the sorting algorithm used by `Lodash`.

In the first case,` _.sortBy(array, (e) => [e, e])`, the identity function returns an array with two elements: the original value e and e itself. When comparing elements during sorting, lodash compares the arrays element by element. Since the arrays have the same length, the first elements are compared, and if they are equal, the second elements are compared. This leads to the sorting order you observed: 'A' comes before 'json copy 1', which comes before 'json copy 2', which comes before 'json copy'.

In the second case,` _.sortBy(array, (e) => [e])`, the identity function returns an array with only one element: the original value e. In this case, lodash performs a standard comparison between the arrays themselves. Since the arrays are different instances, they are compared based on their memory addresses or internal references rather than their contents. This comparison results in a different sorting order: 'A' comes before 'json copy', which comes before 'json copy 1', which comes before 'json copy 2'.

Hence, the difference in results is due to how the elements are compared by lodash's sorting algorithm when using arrays as the comparison values.
