### ISSUE TITLE
Use lodash-es instead of lodash even in dependencies (node_modules)

### ISSUE THREAD

**Issue by gamegee** [lodash/lodash#5642]
Hi,

I am using Vite as a bundler and transpiler for my app. To improve bundle size and enable tree-shaking, I migrated from `lodash` to `lodash-es`, which worked well ✅

However, my dependencies include packages that rely on `lodash`, so my bundle now includes both `lodash` and `lodash-es`. Is there a way to fully replace `lodash` even in my dependencies?

**Comment by deepam-kapur** [comment]
Can I work on this?

**Comment by gamegee** [comment]
Found the solution for vite, you need to define an alias resolution `lodash`:

```tsx
import { defineConfig } from 'vite'

export default defineConfig({
  resolve: {
    alias: {
      lodash: 'lodash-es'
    }
  },
  
  plugins: [
    react()
  ]
})
```

Also if you uses jest, you should define the alias in the `moduleNameMapper`:
```tsx
moduleNameMapper: {
  "^lodash-es$": "lodash"
}
```

**Comment by nirajfu3e** [comment]
@gamegee Thanks for your answer as it helped me solve an issue where when running a production build, it built successfully but kept throwing an error that went `Uncaught TypeError: DataView is not a constructor`. Turns out this error was coming from the [_getTag.js](https://bit.cloud/lodash/lodash/internal/_get-tag/~code) line 35. 

Replacing `lodash` with `lodash-es` and then aliasing it in the `vite.config.js` as follows fixed it!
```js
alias: [
            {
                find: 'lodash',
                replacement: 'lodash-es',
            },
```

**Comment by Malix-off** [comment]
So, is it fixed or we should still use the workaround?

**Comment by FrankFang** [comment]
@nirajfu3e  alias is an object, why is your alias is an array?

**Comment by nirajfu3e** [comment]
> @nirajfu3e alias is an object, why is your alias an array?

I think it can be an arra as [per the doc](https://vitejs.dev/config/shared-options#resolve-alias)

![CleanShot 2024-03-07 at 15 20 42@2x](https://github.com/lodash/lodash/assets/97087509/ea09d42b-017a-4216-8a4d-d0fbeda09d41)
