### ISSUE TITLE
Avoiding Lodash version disclosure

### ISSUE THREAD

**Issue by brsolomon-deloitte** [lodash/lodash#5704]
As documented at https://www.invicti.com/web-vulnerability-scanner/vulnerabilities/version-disclosure-lodash/, Lodash makes its version accessible to the user through a browser's developer tools. 

This is reproducible by adding a dependency on Lodash 4.17.21 in a skeleton React.js project. In Chrome, go to Inspect > Sources, and view the `static/js/*.chunk.js` source, where you'll find a `kn.VERSION = "4.17.21",`, representing the version of Lodash in use.

I realize the difficulty in redacting this information since Lodash is a client-side Javascript utility library, but is there any way to configure Lodash to redact this information, or is it possible that it is not required and can be removed from Lodash?

![image](https://github.com/lodash/lodash/assets/81818815/9e27fe57-16df-4ecd-a9b3-7c545dc20f2a)

**Comment by brsolomon-deloitte** [comment]
```javascript
> console.log(_.templateSettings.imports._.templateSettings.imports._.VERSION);
4.17.21
```

**Comment by arunnambissan** [comment]
Can anyone suggest the exact solution?

**Comment by mfernandes-alcumus** [comment]
This issue is causing some security concerns in my organization is someone able to looking into it

**Comment by Trott** [comment]
The last vestige of this issue was removed from the main branch of `lodash` in 2019 in 40e9c66ca60455d26de752bfbab330771597e7a8.

Unfortunately, that commit wasn't included in the 4.17.21 release that went out the following month, and there hasn't been a subsequent release of `lodash` in that time. (And it doesn't seem like there's a release coming any time soon, although I would be delighted to be wrong about that.)

Fortunately, this is not actually a significant security issue. Your security scanners and information security officers are participating in a false positive race to the bottom. Sure, `lodash` can redact the version information, but that's security through obscurity. Since the version disclosure issue is only a problem on the client side, the attacker can simply inspect the payload to determine the version or not even bother and just run whatever exploit they would use on a vulnerable version and see if it works.

**Comment by arunnambissan** [comment]
This vulnerability might be caused because the lodash object is exported globally and it can be accessed directly using `window._`

You could get rid of this vulnerability issue by following the solution suggested here - https://github.com/lodash/lodash/issues/5704

**Comment by amitpatil321** [comment]
Using webpack we can resolve it thats fine, But what if someone like me is using CRA ? I have to eject the application. Using craco is other other option, but is there any other way which could fix this issue without eject and using craco ?
