### ISSUE TITLE
Avoiding Lodash version disclosure 

### ISSUE THREAD

**Issue by lokeshv12** [lodash/lodash#5829]
As documented at https://www.invicti.com/web-vulnerability-scanner/vulnerabilities/version-disclosure-lodash/, Lodash makes its version accessible to the user through a browser's developer tools.

This is reproducible by adding a dependency on Lodash 4.17.21 in a skeleton **Angular** project. 

I realize the difficulty in redacting this information since Lodash is a client-side Javascript utility library, but is there any way to configure Lodash to redact this information, or is it possible that it is not required and can be removed from Lodash?

How to test it?
Use console.log(_.templateSettings.imports._.templateSettings.imports._.VERSION); on the browser console

**Comment by ThiefMaster** [comment]
If you are in a situation, where you can read the version via devtools, you already have code execution. If you are doing recon you can just guess the version based on the source code (yes, even if minified).

So it makes absolutely no sense to try to hide the version of a client-side library.

**Comment by mfernandes-alcumus** [comment]
This issue is causing some security concerns in my organization is someone able to looking into it?

**Comment by Trott** [comment]
The last vestige of this issue was removed from the main branch of `lodash` in 2019 in 40e9c66ca60455d26de752bfbab330771597e7a8.

Unfortunately, that commit wasn't included in the 4.17.21 release that went out the following month, and there hasn't been a subsequent release of `lodash` in that time. (And it doesn't seem like there's a release coming any time soon, although I would be delighted to be wrong about that.)

Fortunately, this is not actually a significant security issue. Your security scanners and information security officers are participating in a false positive race to the bottom. Sure, `lodash` can redact the version information, but that's security through obscurity. Since the version disclosure issue is only a problem on the client side, the attacker can simply inspect the payload to determine the version or not even bother and just run whatever exploit they would use on a vulnerable version and see if it works.

**Comment by jdalton** [comment]
I'm okay with version numbers. If you're more security focused I'm sure you are running a build or compile step and can change and modify things at will.
