### ISSUE TITLE
Add option to get non-enumerable members with `functions()`

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [lodash/lodash#649]
Specifically, the built-ins like `Array.prototype` have common functions on their ancestors (so trivial enumeration of all members isn't helpful), _and_ those are set as non-enumerable (so `functions()` is non-helpful as well).

_(Array.prototype).functions(nonEnumerable: true) or similar would be a life-saver.

**Comment by jridgewell** [comment]
Surprisingly, I'm going to :+1: this.

I'm in the process of adding Ember.js' [Computed Property](https://github.com/rwjblue/ember-computed-decorators#application-usage) to my Backbone library. Essentially, my version just adds a `_dependentKeys` key to the computing function, then just returns the function.

```js
var Computed = function(...args) {
  var fn = args.pop();
  fn._dependentKeys = args;
  return fn;
};
var View = ComputingView.extend({
  name: Computed('first', 'last', function(first, last) {
    return `${first} ${last}`;
  });
});
```

Now, when you instantiate a view, I find all the computing functions in on the view: 


```js
var ComputingView = Backbone.View.extend({
  constructor() {
    for (var key in this) {
        if (this[key]._dependentKeys) // setup listeners
    }
  }
});
```

Problem is, I want to support both Backbone's "classes", and ES6 classes. And since methods are not enumerable in ES6, my simple `for-in` has to be much more complicated:


```js
// Support ES6 Classes.
// In pre ES6 (no `getOwnPropertyNames` and `getPrototypeOf`)
// just use normal iteration since they don't have classes with
// non-enumerable methods to begin with.
var getOwn = Object.getOwnPropertyNames || _.allKeys;
var getProto = Object.getPrototypeOf || _.constant(null);

var findComputedProperties(object) {
  var proto = object;
  var computeds = [];
  while (proto) {
    _.each(getOwn(proto), function(method) {
      if (proto[method]._dependentKeys) computeds.push(method);
    });
    proto = getProto(proto);
  }
  return _.uniq(computeds);
};
```

Having `_.functions` support ES6 class instances would help greatly.

**Comment by jdalton** [comment]
`Object.getOwnPropertyNames` is not the same as `_.allKeys`. The `Object.getOwnPropertyNames` method gets all own-keys on an object (enumerable and not) while `_.allKeys` gets enumerable own and inherited property keys.

**Comment by jridgewell** [comment]
> Object.getOwnPropertyNames is not the same as _.allKeys

I know. The point wasn't to support `getOwnPropertyNames` in environments without it (`getProto` falls back to `constant(null)`, :wink:). Rather, in ES5 and earlier, there are no "ES6 Classes", so there's no need to look for non-enumerable methods.

The fact that I collect non-enumerables from `Object.prototype` is transparent to my method, since none of them will have a `_dependentKeys` property. Stopping at either `!proto || proto === Object.prototype` would work perfectly as well. The issue is more to do with finding non-enumerables from ES6 classes and subclasses, not the normal prototypes (`Object.prototype`, `Function.prototype`, etc).

**Comment by jridgewell** [comment]
Additionally, `defineProperty`, `getPrototypeOf`, and `getOwnPropertyNames` are all available in roughly the same browser versions. So in the browsers where you _could_ define a non-enumerable method, the native methods are available. In the browsers where you can't define a non-enumerable, you can just fall back to a `for-in` loop to find all enumerable methods.

### defineProperty

| Chrome | Firefox | Safari | IE | Opera |
| ----------- | ------- | --------- | ---- | ------ |
| 5 | 4 | 5 | 9 | 11.60 |

### getPrototypeOf

| Chrome | Firefox | Safari | IE | Opera |
| ----------- | ------- | --------- | ---- | ------ |
| 5 | 3.5 | 5 | 9 | 12.10 |


### getOwnPropertyNames

| Chrome | Firefox | Safari | IE | Opera |
| ----------- | ------- | --------- | ---- | ------ |
| 5 | 4 | 5 | 9 | 12 |

**Comment by jdalton** [comment]
Naw, there's non-enumerable methods in older enviros too.

**Comment by jridgewell** [comment]
That are user defined, not provided by the language?

**Comment by jdalton** [comment]
Provided by the language.

**Comment by jridgewell** [comment]
> Provided by the language.

I'm not concerned with those.

The way I interpret `_.functions` now is "grab all user defined methods". In environments without the native methods, there's no for the user to define a non-enumerable method, so a simple `for-in` "grabs all user defined methods". In environments that do support user defined non-enumerables, the native methods can be used to "grab all (enumerable and non-enumerable) user defined methods".

**Comment by jdalton** [comment]
> I'm not concerned with those.

But I am, I can't have a method that behaves inconsistently across environments.

**Comment by jridgewell** [comment]
I don't see it as inconsistent? The environments where it's not checking for non-enumerables are the environments where you can't define them to begin with.

**Comment by jdalton** [comment]
A user could pass a built-in `prototype` to a function expecting it to list all own properties, including non-enumerable ones, which is why I punted on this originally.

**Comment by jridgewell** [comment]
Oh, so that's where I see the difference. `_.functions` isn't supposed to return any language provided functions, only user-defined. While that may not have been the original intention, JS using non-enumerable methods and `_.functions` using a `for-in` has effectively made it that way.

We can keep the behavior the same going ahead, but it's going to be a pain with ES6 classes. I think it'll be much more useful find _any_ user defined method, not just the enumerable ones.

**Comment by ELLIOTTCABLE** [comment]
@jridgewell (perhaps I could talk you into bringing that up as a new Issue? As the use-case you soldier irrelevant is precisely the one I opened this Issue about. :P)

@jdalton I understand the consistency concerns. If you need to tag and close this, I'll thank you for having explained your reasons. /=

**Comment by jdalton** [comment]
Things that don't quite fit into core are great candidates for mixins.
