### ISSUE TITLE
Bind all methods?

### ISSUE THREAD

**Issue by macalinao** [lodash/lodash#652]
I often do something like this:

``` js
var thing = function() {};
var inst = new MyFunction();
_.forEach(MyFunction.prototype, function(method, name) {
  if (typeof method !== 'function') {
    return;
  }
  thing[name] = _.bind(method, inst);
}
```

Is there some kind of utility method in Lodash that can do this? Thanks.

**Comment by importvault** [comment]
I can see situations where binding to **all** methods would cause issues - especially if the objects are created in an *external* source.

Also for objects with large numbers of methods - binding *each one* all the time would create unnecessary closures if the methods are not used.

However because this is something that is a strong function of use case, I presume its best left to the user to make that call.

anyway @ryannichols @jacksonrayhamilton you could check out the API for [bindall](https://github.com/importvault/bindall).
