### ISSUE TITLE
_.inherit function?

### ISSUE THREAD

**Issue by jtangelder** [lodash/lodash#663]
An idea for a new method, for some simple class inheritance;

``` js
function Animal(name) {
    this.name = name;
}

function Dog() {
    Animal.apply(this, arguments);
}

_.inherit(Dog, Animal, {
    bark: function() {
        alert(this.name);
    }
});

var dog = new Dog('Spaikie');
dog.bark();
```

I know this is fairly easy to do with the _.create and _.extend methods, but it could be easier in my opinion.
Implementation would be something like this;

``` js
function inherit(child, base, properties) {
    child.prototype = _.create(base.prototype, { 'constructor': child };
    child.prototype._super = base.prototype;

    if (_.isObject(properties)) {
        _.extend(child.prototype, properties);
    }
}
```

**Comment by shamasis** [comment]
+1

**Comment by maximkott** [comment]
+1

**Comment by oriSomething** [comment]
There is a known module for it https://github.com/dfilatov/inherit

**Comment by jtlapp** [comment]
It seems to me that the purpose of lodash is to provide working functions that people end up implementing over and over again. I am now lamenting the lack of _.inherit() in lodash because I keep screwing up this function. If I'm writing the function myself, I might as well put it in my own reusable library and throw in the implementation of _.create() so that I don't need to pull in lodash. That seems to undermine the utility of _.create() in lodash.
