### ISSUE TITLE
[Feature Request] _.sum

### ISSUE THREAD

**Issue by philippotto** [lodash/lodash#687]
I know that you can use _.reduce to calculate the sum of an collection, but I think that the sum is a very basic and often needed operation. Thus, a shorthand for it would be appropriate.

Compare the length of the following to lines:

``` javascript
_.reduce(array, function(sum, num) { return sum + num}, 0);
_.sum(array);
```

It could provide a _.pluck style shorthand for summing specific attributes:

``` javascript
_.reduce(array, function(sum, num) { return sum + num.attribute}, 0);
_.sum(array, "attribute");
```

I for myself often find myself trying to use _.sum and then I'm always surprised that it doesn't exist. Do you agree? Or is it inappropriate for lodash?

**Comment by krummi** [comment]
(y)

**Comment by Calamitous** [comment]
:+1:

**Comment by franklinjavier** [comment]
:beers:

**Comment by mocheng** [comment]
:+1:

**Comment by jdalton** [comment]
No need for more :+1:'s, it's on the [roadmap](https://github.com/lodash/lodash/wiki/Roadmap). Thanks everyone!

**Comment by phated** [comment]
:+1: for roadmap :+1: for @jdalton  :+1: for math

**Comment by jdalton** [comment]
Can someone create a PR to add `sum` and some other basic math methods like `add`, `minus`?, `mean`.

**Comment by jdalton** [comment]
Include tests plz.

**Comment by Droogans** [comment]
I have some questions about increasing the chances of a PR getting accepted. The question I'd like to ask is, is it alright to call `lodash.reduce` directly when writing this function?

Looking at your [talk on Javascript performance](https://www.youtube.com/watch?v=NthmeLEhDDM&t=26m12s), you highlight many of the strategies you use to keep lodash operations fast. Part of this is shown in the source for [`_.reduce`](https://github.com/lodash/lodash/blob/6013bb5fad8dc5979432501276edf4402d32b328/lodash.js#L6360):

```js
var func = isArray(collection) ? arrayReduce : baseReduce;
```

Part of me thinks it should be fine creating the function `sum` as it is straight from the docs, using reduce. However, due to reasons I never got resolution on, [a pull request I helped author was closed](https://github.com/lodash/lodash/pull/587/files), and I feel it may have had to do with the function proposed simply calling other lodash functions, instead of doing data-normalizing checks and other performance-minded operations that the others do.

I would think the same thing would apply for `sum`. Is it alright to directly call `reduce` in this case, or should it not rely on other functions to do its work?

**Comment by jdalton** [comment]
> However, due to reasons I never got resolution on

We aren't looking deep property helpers at that time and I believe it was stated in the issue too.

> Is it alright to directly call reduce in this case, or should it not rely on other functions to do its work?

No let's not use `_.reduce` directly as it increases deps for unused callback sugar & object iteration. If anything you can use `arrayReduce` though really a simple for-loop would do.

**Comment by jdalton** [comment]
Related to https://github.com/jashkenas/underscore/issues/2165.
