### ISSUE TITLE
_.count method

### ISSUE THREAD

**Issue by justin808** [lodash/lodash#702]
Would it make sense for lodash to have a `_.count` method?

Like this: http://ruby-doc.org/core-2.1.2/Enumerable.html#method-i-count
I'd be happy to implement one and submit a PR if this is appropriate.

**Comment by artch** [comment]
`_.filter` creates a new array which can be huge overhead if we want to simply count some values by a predicate, rather than get the sub-array.

+1 for `_.count`.

**Comment by nickperkinslondon** [comment]
+1 for _.count  ( and _.countWhere )

I was surprised to find that these don't already exist!  Wouldn't it be nice, when you just want to count something, to simply reach for the "_.count()" function?  Of course you can instead do it with "filter/length" but that seems a tiny bit awkward, and counting is such a simple and fundamental concept -- it deserves it's own function.  ( plus, there's the performance thing -- you could implement it without creating a new array ).

**Comment by jasonmaire** [comment]
+1 for `_.count`.

But instead of  `_.size` & `_.filter` you could use `_.sum` like this (rewriting the example above) to avoid the creation of an array:

```javascript
var all = nextProps.list.length;
var complete = _.sum(nextProps.list, function (prop) {
    return !!prop.isComplete;
});
var incomplete = all - complete;
```

Note : use `!!` in order to convert `undefined` to `false` in the example (as `undefined` in an sum returns `NaN`, unlike `true`, `false` or `null`).

**Comment by Taytay** [comment]
Thanks for the pointer to `sum` @jasonmaire. That looks like it will do the trick. :)

**Comment by Taytay** [comment]
Minor, but just noticed: Could you rewrite the above as:
```
var incomplete = _.sum(nextProps.list, function (prop) {
    return prop.isComplete ? 0 : 1;
});
```

**Comment by elado** [comment]
+1 for `_.count(enumerable, predicate)`
I know it's tagged as wontfix, but all suggestions here are hacks, and `_.filter(..).length` is an overhead.

**Comment by qsona** [comment]
+1 for `_.count`. I feel it's very natural and will be used a lot.

**Comment by nikhilenmudi** [comment]
+1 for _.count

**Comment by artuska** [comment]
+1 for _.count

This is pretty often usecase, e.g.:

```
var checkedLength = _.count(checkboxes, {isChecked: true});
```

Now I'm doing:

```
var checked = _.filter(checkboxes, {isChecked: true}),
    checkedLength = checked.length;
```

`_.count` would be more natural.

**Comment by pykiss** [comment]
+1 for count

**Comment by pykiss** [comment]
[1,2,1,3,4,1].reduce(function (x,y) { return y === 1 ? ++x : x }, 0) => 3

**Comment by c-dante** [comment]
-1 for `_.count`, just a filter with length after as proposed. Not a work around -- just trying to over abstract the method.

Reason: The function would be wrapping you accessing `length` from a filter. It doesn't add anything.

**Comment by elado** [comment]
@c-dante `filter` creates a new unnecessary array.

**Comment by c-dante** [comment]
True that -- would be something like
```
let count = (fn, collection) => _.reduce((c, x) => c + (fn(x) ? 1 : 0), 0, collection)
```

**Comment by elado** [comment]
@c-dante And this code is exactly why `_.count` is needed in the core :)

**Comment by c-dante** [comment]
My only conflict is how count is useful in applications -- I'm trying to think of times where I want how many satisfy a predicate and not which -- I keep coming to UI concerns only.

Is there a meaningful algorithm or use case you can come up with that just wants to know how many and not which? Or rather, one such that you do _not_ want the filtered set (either side)?

**Comment by elado** [comment]
@c-dante real life example I have in my app - unread count of messages: `const unreadCount = _.count(messages, m => !m.read)`

**Comment by jdalton** [comment]
@c-dante Oh neat!
```js
_.sumBy(collection, _.flow(pred, Boolean));
```

**Comment by c-dante** [comment]
@elado that's exactly what I mean with UI concerns -- it's for displaying how many, etc. And in cases where a short lived array doesn't really impact you.

Either way, I can totally see the use of a `count`, but I'm still skeptical if lodash is the place or your own utils (especially given the `sumBy` example)

**Comment by StreetStrider** [comment]
:+1:  I'm for `count` cause it's idiomatic vs. `filter(…).length`. It's a good building block. `count` is win because of:
1. Can evade intermediate array.
2. It allows to build more complex stuff on top of it (devs specific groups, sums, comparsions etc).
3. In future it can also work polymorphic on other types which uses something like `size()` instead of `length`. It will hide complexities of choising proper method/value.

I'm not agree that `filter(…).length` is good, since following that logic we could throw 85% of LoDash methods and just use `Array.prototype.reduce` but we don't do that, do we?

In some cases devs actually do not need `count` when they need to compare it with 0. They need emptiness check, looks like a work for `isEmpty`, but it do slightly different stuff, no one fully understand what it do really :smiley:

**Comment by c-dante** [comment]
@StreetStrider the recent answer is not the `filter.length` especially for the reason your point out.

It's to use `_.sumBy` to achieve count (and my other possible things):

```js
_.sumBy(collection, _.flow(pred, Boolean));
```

As an example.

**Comment by artch** [comment]
`_(array).filter(pred).size()` does not create an intermediate array, does it?

**Comment by jdalton** [comment]
Folks, the intermediate array is a red herring. Let's stop discussing it.

**Comment by artch** [comment]
@jdalton Why? It is actually the crux here. This issue is all about finding a neat way to count the number of filtered items with as less code as possible AND without creating the intermediate array.

**Comment by jdalton** [comment]
The intermediate array is an implementation detail and a micro-optimization and not the crux of the method. The `count` method is a more expressive way to get the count of something than doing a `filter`, `map`, `sumBy`, or `reduce` is all.

**Comment by artch** [comment]
@jdalton I disagree it is a micro-optimization. I'd rather say it quite major, when the case is about traversing an array of thousands of elements constantly when the page data changes in the real-time. It could (and does) noticeably affect FPS and create hiccups in comparison to intermediate-array-free approach. For me this is the main reason I would want such a method. And if `_().filter().size()` doesn't create an intermediate array, I'm fine with it then, it's clean enough, no `count` is needed.

**Comment by jdalton** [comment]
> I disagree it is a micro-optimization. I'd rather say it quite major, when the case is about traversing an array of thousands of elements continuously when the page data changes in the real-time. It could (and does) noticeably affect FPS and create hiccups in comparison to an intermediate-array-free approach. 

It's a micro-optimization. You're describing a scenario like a render loop where much of Lodash wouldn't be appropriate anyways. Lazy evaluation will kick in for large arrays but `size` is not one of the supported methods. The win with lazy evaluation isn't the intermediate array creation it's the massively reduced iteration. If you'd like to continue to discuss the intermediate array thing more, feel free to hit up [our gitter chat](https://gitter.im/lodash/lodash).

**Comment by elado** [comment]
How come `sumBy` made it to lodash but `count` won't? It's the same argument, `sumBy` can be achieved with `reduce`, as plenty of other great lodash helpers. I got the impression this library provides better interfaces to do common things.

**Comment by jdalton** [comment]
`sumBy` came from splitting out the overloaded functionality of `max`, `min`, & `sum`.
We added `sum` due to dev interest [just as this process](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests) here.

**Comment by artch** [comment]
@jdalton This depends on the use case actually. If you filter out ten elements from an array of thousands items, yes, it is a micro-optimization. But if your filter produces 9,999 elements from a 10,000 elements array, then not having an intermediate array for merely counting them makes HUGE difference, since pushing into a non-fixed length array (at least in V8) is really slow. It is pretty obvious and can be easily proved by any benchmark.

Actually, if `size` is not supported in lazy evaluation, IMO it should be addressed first, this would provide a lot of performance improvement possibilities to our code and seems to be a good fit in the whole lazy concept.

**Comment by jdalton** [comment]
As I've already covered the edge perf concern does not interest me. I'd appreciate it if you'd take the discussion to gitter or anywhere off thread as it's a distraction from the feature request.

**Comment by artch** [comment]
OK, now I get it, this is what you should have told from the start - "the performance concern doesn't matter" rather than "it does not affect performance".

As to the feature itself, I'd vote for `_.size(collection, [iteratee])` (preferably with the lazy support). We already got the `size` method with the desired semantics, the only missing feature is to make it customizable. For all other cases `sumBy` should be enough.

**Comment by jonathan-potter** [comment]
:+1: for count. @c-dante if we were okay building everything with reduce we wouldn't need any other methods. `sumBy` looks like it works but it is very high my 'clever' meter. using `true` and `false` as `0` and `1` also works but is too clever for my taste as well.

**Comment by c-dante** [comment]
Yeah, I've revised my opinion on it.

We have `_.countBy` now.

**Comment by elado** [comment]
@c-dante thanks!

I just discovered that `_.sumBy` actually works when counting with a predicate, but this is only because the returned value is a boolean and `0 + true === 1`, `0 + false === 0`.

```js
const messages = [{id: 1, read: true}, {id: 2, read: true}, {id: 3, read: false}, {id: 4, read: false}, {id: 5, read: false}]
_.sumBy(messages, o => !o.read) // => 3
```

So the new `countBy` is like `SELECT read, COUNT(*) FROM messages GROUP BY read` and the `sumBy` in my example is used as `SELECT COUNT(*) FROM messages WHERE read = false` - that was my original intention for `_.count`.

`countBy` doesn't fit the case above as it returns `{true: 2, false: 3}` so I have to check `_.countBy(messages, 'read')['false']`. It's essentially `_(messages).groupBy('read').mapValues(_.size).value()`

So, with `sumBy` being semantically incorrect to count which items in an array pass a predicate, I still think there's room for `_.count`.

**Comment by lindem** [comment]
Just stumbled across this; I'd like to add that `_.count(seq, predicate)` is also self-documenting code. I think `_.countBy()` just doesn't achieve the same degree of simplicity, its return value always being an object. I am really surprised that there's opposition to this particular concept of just returning a number.

**Comment by freewind** [comment]
I'm searching "lodash count" to reach here

**Comment by c-dante** [comment]
@lindem are you suggesting renaming `countBy` to `count`?

I'd disagree since `count` would translate to length in most cases -- not a summing operation. Counting is enumeration of cases -- not aggregation.

Otherwise, what you're doing is summing. So, `sumBy` as per the example.

**Comment by lindem** [comment]
@c-dante no, I (and the OP as well, presumably) want `_.count(pred)` to return the number of items in the collection the predicate returns truthy for. No object, just a number. And I still don't understand the opposition to that simple concept. It's just self-documenting. 

And your sumBy example just doesn't communicate any intent (which is counting -- the verb "count" tells me at a glance what's happening).

**Comment by c-dante** [comment]
I'm for a mixin of:
```js
_.count = _.sumBy(collection, _.flow(pred, Boolean));
```

**Comment by mologie** [comment]
There also is an argument of efficiency to make here.

Most combined functions which achieve the behavior described in this ticket will build some kind of temporary object, which is then further evaluated for deriving the final count. Obvious examples are the filter+length and the map+sum approaches described above.

A more efficient implementation would only require a single integer for counting. This ticket therefore has my vote, because bits are precious.

**Comment by SmedbergM** [comment]
I'd upvote this too. `_.sumBy(collection, predicate)` works but is unidiomatic.

**Comment by gunar** [comment]
The predicate needs to return a number not a boolean, hence
```js
_.sumBy(collection, _.flow(pred, Number));
```

**Comment by SmedbergM** [comment]
> The predicate needs to return a number not a boolean

In a type-safe world, sure. But `+` coerces booleans into numbers, which is why I said it *works*.

**Comment by vance** [comment]
Did somebody really question the use case for counting things?
