### ISSUE TITLE
_.filter and _.reject do not work with a _.partialRight-constructed callback

### ISSUE THREAD

**Issue by emallson** [lodash/lodash#844]
In my particular example I have defined 2 functions in the Node.js REPL.

```
var L = require('lodash');
var someNaN_partial = L.partialRight(L.some, L.isNaN);
var someNaN_explicit = function(x) { return L.some(x, L.isNaN); }
```

These two functions return the same value for every array I tested. However:

```
_.reject([ [1, 2, 3], [1, 2, NaN] ], someNaN_partial);
// -> [ [1, 2, 3], [1, 2, NaN] ]
_.reject([ [1, 2, 3], [1, 2, NaN] ], someNaN_explicit);
// -> [ [1, 2, 3] ]
_.filter([ [1, 2, 3], [1, 2, NaN] ], someNaN_partial);
// ->  []
_.filter([ [1, 2, 3], [1, 2, NaN] ], someNaN_explicit);
// ->  [ [1, 2, NaN] ]
```

Lodash version is 2.4.1 installed through npm

**Comment by CrossEye** [comment]
> Lo-Dash will also offer an `_.ary` method to cap the number of arguments accepted by a method.
>
> ```javascript
> _.map(["1", "2", "3"], _.ary(parseInt, 1)); //=> [1, 2, 3]
> ```

This is perhaps a step in the right direction.  But wouldn't it be better to offer a version of `_.map` that simply doesn't cause these issues?  For the sizable majority of use-cases, the `index` and `collection` parameters to the callback are simply ignored.  For a small minority like these, they are actively harmful.  If there was a version of `map` that didn't include them, then users could choose it over the three-parameter-callback version for their standard usage and only call the current one when they actually need these additional parameters?  And of course the same is true for `filter` and a number of similar functions.

Wouldn't that do a better job of providing quality utility methods to as many devs as possible?

**Comment by jdalton** [comment]
> But wouldn't it be better to offer a version of _.map that simply doesn't cause these issues? 

I don't cluttering the API is necessary when helpers like `_.ary` and `_.rearg` enable the existing API to be customized to taste.

>  For the sizable majority of use-cases, the index and collection parameters to the callback are simply ignored.

I'm not sure what the majority use-case is. I know the language and many popular libs supply 3 arguments so it seems reasonable to continue with the established convention.

> For a small minority like these, they are actively harmful.

I think "harmful" is a bit much. The issue is easily managed with a simple function wrapper, `_.ary`, or [other helpers](https://github.com/bevacqua/but#usage). Lo-Dash also takes steps to mitigate the issue by baking in support for methods to work as iteratees in `_.map`, `_.reduce`, & friends.

Changelog:
>
  * Methods that work as an iteratee for `_.map`, & the like, out of the box:<br>
   `_.ary`, `_.callback`, `_.chunk`, `_.clone`, `_.create`, `_.curry`,  `_.curryRight`,
   `_.drop`, `_.dropRight`, `_.flatten`, `_.invert`, `_.max`, `_.min`, `_.parseInt`,
   `_.slice`, `_.sortBy`, `_.take`, `_.takeRight`, `_.template`, `_.trim`, `_.trimLeft`,
   `_.trimRight`, `_.trunc`, `_.random`, `_.range`, `_.sample`, `_.uniq`, & `_.words`
>
  * Methods that work as an iteratee for `_.reduce`, & the like, out of the box:<br>
   `_.assign`, `_.defaults`, `_.merge`, & `_.sortAllBy`

----
 
> Wouldn't that do a better job of providing quality utility methods to as many devs as possible?

I think following the established convention and offering helpers to customize functions to taste enables us to do that.

**Comment by CrossEye** [comment]
>> But wouldn't it be better to offer a version of `_.map` that simply doesn't cause these issues?

> I don't cluttering the API is necessary when helpers like `_.ary` and `_.rearg` enable the existing API to be customized to taste.

While `_.ary` sounds useful, the thought of the arbitrary API redesign features engendered by `_.rearg` scares me.  I see it this way, you're putting edge considerations over common established expectations and in the process adding more complexity/confusion with alternative and inconsistent APIs in the mix.

>> For the sizable majority of use-cases, the index and collection parameters to the callback are simply ignored.

> I'm not sure what the majority use-case is. I know the language and many popular libs supply 3 arguments so it seems reasonable to continue with the established convention.

Functions like `map` came from the functional programming world.  They were adopted by a few libraries, and eventually became part of the ES5 spec.  But one of the early adopters, jQuery, started by using the iterated item as the `thisObj`, then later (I believe; it could have been at the same time) added the index as a parameter.  When they decided to use the object as a parameter their parameter order was already odd because of backwards compatibility issues.  ES5 made a better  choice with item before the index; this more sensibly takes advantage of Javascript's handling of additional/ignored parameters.

But none of this really followed the conventions established by other languages.  Most functional languages simply pass the iterated item.  This makes sense, because the idea of `map` (and `filter`, and many similar ones) generalizes very easily to other situations where there is no coherent notion of an index: things like streams, lazy/infinite lists, event queues.


>> For a small minority like these, they are actively harmful.

> I think "harmful" is a bit much. 

Perhaps you're right.  "Annoying" is probably closer to the truth.  How often has this come up in the Lo-Dash issues log, do you know?

> The issue is easily managed with a simple function wrapper, _.ary, or other helpers. Lo-Dash also takes steps to mitigate the issue by baking in support for methods to work as iteratees in _.map, _.reduce, & friends.

But this privileges Lo-Dash functions over user functions?  Doesn't that concern you?


>> Wouldn't that do a better job of providing quality utility methods to as many devs as possible?

> I think following the established convention and offering helpers to customize functions to taste enables us to do that.

As Andrew Tanenbaum [almost said][at], "The nice thing about <del>standards</del> conventions is that you have so many to choose from."   [Haskell][h], [Clojure][c], [Scala][s1], and [Scheme][s2] all pass just the list item to the iterator/callback function.

  [at]: http://en.wikiquote.org/wiki/Andrew_S._Tanenbaum
  [h]:http://www.haskell.org/hoogle/?hoogle=map
  [c]:http://clojuredocs.org/clojure.core/map
  [s1]: http://www.scala-lang.org/api/current/index.html#scala.collection.Iterable@map[B](f:A=>B):Iterable[B]
  [s2]: http://en.wikibooks.org/wiki/Scheme_Programming/List_Operations#List_manipulation

**Comment by emallson** [comment]
@CrossEye To be sure, the convention in the FP world contributed to my misunderstanding. I spent most of the past few months writing Haskell and Clojure, so when coming to a FP library in JavaScript-land I assumed (wrongly) that it'd follow the same convention.

**Comment by jdalton** [comment]
>  I see it this way, you're putting edge considerations over common established expectations and in the process adding more complexity/confusion with alternative and inconsistent APIs in the mix.

It's the opposite. I'm putting the conventions established in JS and its lib ecosystem over this edge issue and offering devs a way to customize to taste if needed.

> Functions like map came from the functional programming world. They were adopted by a few libraries, and eventually became part of the ES5 spec.

They've been in engines [~10 years now](https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/1.6), long before ES5 and jQuery.

> How often has this come up in the Lo-Dash issues log, do you know?

Not with any regularity.

> But this privileges Lo-Dash functions over user functions? Doesn't that concern you?

Not concerned at all. It allows Lo-Dash methods to "just work" while offering other non-lodash methods a way as well.

> "The nice thing about standards conventions is that you have so many to choose from."

I'll stick with the ones backed by JS and popular libs. We offer options for those that need it.

**Comment by CrossEye** [comment]
> I'm putting the conventions established in JS and its lib ecosystem over this edge issue 

So if at some point the spec and the implementations change their APIs to add/remove/reorder parameters -- and yes, I know this is unlikely -- will Lo-Dash change to match?  Are you responsible for your API or does Lo-Dash just follow the lead of the other libraries and ES implementations?

> and offering devs a way to customize to taste if needed.

But this doesn't actually offer a way to actually customize these functions.  All you offer is a way for users to wrap up their own functions.  That is hardly the same.  With the radical changes that `_.rearg` will allow, you still don't offer this simple functionality that other libraries and languages do. 

> They've been in engines ~10 years now, long before ES5 and jQuery.

Well, I'd argue that November 2005 is not really long before January 2006, but you're right, they have been around a long time in some engines; I didn't dig though es-discuss archives to find when they were first proposed, but I do think they were actually part of the doomed ES4 proposal.

>> But this privileges Lo-Dash functions over user functions? Doesn't that concern you?

> Not concerned at all. It allows Lo-Dash methods to "just work" while offering other non-lodash methods a way as well.

That's surprising to me.  I would be very concerned by this.  It adds complexity to support and documentation, makes it harder to find compatible functions for inclusion, and runs the real risk of annoying users.

>> "The nice thing about <del>standards</del> conventions is that you have so many to choose from."

> I'll stick with the ones backed by JS and popular libs. We offer options for those that need it.

Wouldn't it be better to stick with the most logical ones?  As pretty much all the engines in modern use already supply `Array.prototype.map` with the same signature as Lo-Dash, it already feels a bit redundant to offer it.

Moreover, how do you respond to the reasonable request that `map` extend to other types than array, string, and object?  What parameters should the callback receive for an event queue?  For an arbitrary stream?  For a lazily-generated list?

**Comment by jdalton** [comment]
> Are you responsible for your API or does Lo-Dash just follow the lead of the other libraries and ES implementations?

We're responsible for our API. We've chosen to align with ES implementations.

> But this doesn't actually offer a way to actually customize these functions. All you offer is a way for users to wrap up their own functions. That is hardly the same. With the radical changes that `_.rearg` will allow, you still don't offer this simple functionality that other libraries and languages do.

Sure it does. Devs are free to use `_.ary` and `_.rearg` on any function, Lo-Dash or otherwise. We provide `_.runInContext` and `_.mixin` to allow creating and extending lodash instances. The functionality is simple enough.

> Well, I'd argue

I'd like to spend my time on other things.

> That's surprising to me. I would be very concerned by this. It adds complexity to support and documentation, makes it harder to find compatible functions for inclusion, and runs the real risk of annoying users.

Added complexity is minimal with no impact on performance of the common case and low risk  due to its narrow check. The result is happy, not annoyed devs.

> Wouldn't it be better to stick with the most logical ones? As pretty much all the engines in modern use already supply `Array.prototype.map` with the same signature as Lo-Dash, it already feels a bit redundant to offer it.

Seems logical to me. It's an API familiar to devs with extra functionality to boot.

> Moreover, how do you respond to the reasonable request that `map` extend to other types than array, string, and object?

I'm fine with map's designation as a collection method. We're not looking to expand "collection" at the moment.

**Comment by karthikhr1437** [comment]
why _.indexOf("##L", "##") is -1 ??
