### ISSUE TITLE
main.js issue

### ISSUE THREAD

**Issue by lucasmciruzzi** [lodash/lodash#863]
main.js doesn't require all the modules like it should, instead it is the compiled version.

Shouldn't the main.js contain a "require" with all the modules, like any regular main file in and AMD project? Something like:

    require([
    	"array",
    	"chain",
    	"collection",
    	"date",
    	"function",
    	"lang",
    	"number",
    	"object",
    	"string",
    	"support",
    	"utility"
    ]);

**Comment by d10** [comment]
The main.js file contains the monolithic version. If you need individual modules you can require stuff like `lodash/array` for all Array methods, and `lodash/array/chunk` style for individual methods.

**Comment by lucasmciruzzi** [comment]
And maybe call the monolithic version "lodash.js"?

**Comment by jdalton** [comment]
@lucasmciruzzi Thanks for the question. This is by design to reduce load times and enable features when including the kitchen sink. With the kitchen sink we enable support for `_.runInContext`, which is not possible in modular builds, and enable our chaining syntax and lazy evaluation.

This was a way to have our cake (`runInContext`, chaining, lazy evaluation) and eat it too (individual method modules). 

Is there an issue you're running into by main.js being a monolithic build vs hundreds of modules?

**Comment by lucasmciruzzi** [comment]
You are right, I changed the title to be more fitting. it was only a question to understand why there was a "compiled" version in the amd branch of lodash. Thanks for the replies!

**Comment by jdalton** [comment]
No prob. In the [readme](https://github.com/lodash/lodash/blob/3.0.0-amd/README.md) you can see where we pave the normal `main.js` module as normally it does reference all those individual modules.

```bash
$ lodash modularize modern exports=amd -o ./
$ lodash modern exports=amd -d -o ./main.js   //<-- replace main.js with monolithic main.js
```
