### ISSUE TITLE
lodash.mixin@3.0.0 regression?

### ISSUE THREAD

**Issue by mreinstein** [lodash/lodash#880]
```javascript
var A, a, b, mixin;

mixin = require('lodash.mixin');

A = (function() {
  function A() {}

  A.prototype.doit = function() {
    return 'executed';
  };

  return A;

})();

a = new A();

b = {};

mixin(b, a);

console.log('result:', b.doit());
```

with v2.4.1 I see `result: executed`. with v3.0.0 it displays `TypeError: undefined is not a function`.

**Comment by jdalton** [comment]
Thank you for reporting this. It's actually a by design breaking change. After release it seems a few fell through the notice cracks. In v3 all source methods are iterated as `Object.assign`, that is they iterate over own properties of source objects. If you want to flatten an object like `new A` down you can use:

```mixin(b, toPlainObect(a));```

**Comment by jdalton** [comment]
I'll add a compat notice to the [changelog](https://github.com/lodash/lodash/wiki/Changelog) tonight.

**Comment by mreinstein** [comment]
@jdalton I'm confused about what `toPlainObject` does, can you elaborate?

**Comment by jdalton** [comment]
See https://lodash.com/docs#toPlainObject.

**Comment by mreinstein** [comment]
ah sorry! for some reason the link didnt come up when I searched the api doc page for toPlainObject.

thx!
