### ISSUE TITLE
memoize() cache iteration

### ISSUE THREAD

**Issue by bazineta** [lodash/lodash#897]
In the change notes for memoize(), there's the following:

Made _.memoize cache implement the ES Map interface

It appears that as a result of this, the cache is no longer iterable; that is, the Map interface appears to be all that it implements.  If this is indeed the case, then given that this is a reduction in functionality, i.e. previously one could iterate the cache, but that seems now to no longer be possible, then a bit more in the release notes for this section would be helpful.

**Comment by bazineta** [comment]
Actually, to clarify, it appears that it implements WeakMap, not Map.  That is, there's get(), set() and has(), but not forEach(), etc.

**Comment by jdalton** [comment]
I didn't say it implements the full API of either `Map` or `WeakMap` as that's not the intent. I'll clarify the note. The intent is to implement enough that the cache can be swapped out with `Map` or `WeakMap`. In previous versions iterating the cache was clunky because of key prefixes. In v3 if you want to iterate the cache there is a pseudo private property available.

**Comment by jdalton** [comment]
Updated the changelog mention.

**Comment by bazineta** [comment]
Thanks, that's definitely more clear.

I think that a common usage of _.memoize() is to create a cache, for example, of connection pools, etc., and it's not uncommon to have to at some point clean it up (e.g., closing a connection) before it goes away, thus the iteration question.  Easy enough to swap in an actual Map implementation for that requirement now that I understand the intent, but it was a bit confusing at first; hopefully that'll help others.
