### ISSUE TITLE
Chaining question

### ISSUE THREAD

**Issue by ashclarke** [lodash/lodash#907]
Hi John-David,

I have a simple utility function for testing that iterates through a number of values and calls a callback on these.

```
function iterateTypes(callback) {
    if (_.isFunction(callback)) {
        _([[], {}, true, 1, undefined, null, function () { }, NaN, ""]).each(callback);
    }
    else {
        throw new Error("`callback` is not a function");
    }
};
```

It seems that something has changed in lodash 3 that has caused this to no longer be chainable, and is therefore preventing the `each` function  from being called.

I've stepped through but I'm not sure whether there is a bug or not :S

Any ideas?

Thanks

**Comment by megawac** [comment]
Duplicate of #785, #878

**Comment by ashclarke** [comment]
Ah damnit. Thanks for opening my eyes! :eyes:

**Comment by jdalton** [comment]
Chaining is now deferred until an implicit or explicit `value` is requested. The _.each method returns the provided collection so does not warrant an implicit value() call.

Honestly no one should be doing `_(...).each(...)` as it's a waste creating a wrapped object just to throw it away. I like that there is a very clear distinction between normal and chained syntax to help avoid the conflating the two.

**Comment by megawac** [comment]
I disagree, I'd say its pretty common to do a series of operations and end
with an each. For instance a flat map into a filter into something
iterating the result

**Comment by jdalton** [comment]
> I disagree, I'd say its pretty common to do a series of operations and end
with an each.

To end the sequence simply use `.value()`. Because `each` is chainable it allows intermediate iteration that doesn't require the chain to be ended. The `each` method isn't reducing a collection to a single value or getting a single element out of a collection to ending the chain doesn't make sense and could be counter to the established behavior. By enabling `each` to be chainable we give devs control of it's behavior, choosing to end it with `value` if they want.

**Comment by brianmhunt** [comment]
@jdalton - thanks for all your work on this. Really amazing stuff. Just a quick comment on your note above:

> The each method isn't reducing a collection to a single value or getting a single element out of a collection so ending the chain implicitly doesn't make sense and would be counter to the established behavior. By making each chainable we give devs control of its behavior, allowing them to end the sequence with value if they want.

Just as a matter of opinion & style, I really feel like one should end a chain with `each`. I never even knew (or expected) that `each` returned the collection, and am still unclear as to the use case for this; I expect `each` to receive the values immediately and operate on them in order, the idea of changing or returning the collection strikes me as something more like a `tap` than an `each`.

It also seems counterintuitive to need to add `value` to start the iteration. I never expect nor would I use `each` to return, filter, modify, or add to a chained collection. As such I feel that `each` is a consumer at the end of the chain, not a participant of a continuing chain. With such a perspective, adding `.value()` (to something you never expect to return a value) smells funny and may confuse uninitiated developers into thinking that the `each` call returns something of value (when in fact the typical but now slightly obfuscated intention may be to perform an action on the items being iterated over).

The `each` call, for me at least, contrasts with the functions that clearly modify the collection or `tap`, which naturally fits into the chain and achieves the same as `each`.

Which is all to say: I feel `each` should consume the collection when called, without needing a superfluous `.value()`, because that is what my expectations are. The repetition of reports about this indicate that it is probably a reasonably popular expectation.

Of course, I'm probably all wrong and the better way is to add `.value`, I am likely stubbornly set in my ways, but I just wanted to give a heads up with a vote to reconsider this. :smile: 

:beers:

**Comment by jdalton** [comment]
I think you went in circles a bit in your explanation but I get the gist and I disagree.

This is the deferred chaining syntax. Sorry if you don't like deferred chaining. We've got our chaining behavior established and consistent and `each` isn't a strong enough case to break that now. `each` has returned a value since before lodash 1.0 and has been documented to do so. Usually you're chaining more than just `_(...).each()` so another `.value()` isn't a pain and if you are simply doing `_(..).each()` switch to `_.each()`.

**Comment by brianmhunt** [comment]
Thanks @jdalton ; sorry I didn't have time to make my post more concise.

Please, don't get me wrong, I think deferred chaining is awesome. I just believe `each` should be on par with `value` in terms when the deferral resolves. And I've no doubt your reasons are well justified on this.

It is not unusual to have something like this: `_(items).map(map_fn).filter(filter_fn).each(each_fn)`, and I think that's where users seem to be (perhaps rightly) confused — it's only been 2 weeks and you already have at least five issues on this.

Given the popularity of the confusion, it may help to make a special point in the docs highlighting the need for `.value` at the end of the `each` chain. I think lots of folks stop reading the docs after "Iterates over elements of collection invoking iteratee for each element. ", but at least if there's a note about needing `value()` you'll reduce your overhead answering the folks who read beyond. :)

**Comment by jdalton** [comment]
> it's only been 2 weeks and you already have at least five issues on this.

Deferred chaining is new and different from 2.4.1. I'm getting lots of issues filed on devs coming to grips with various changes. That's no reason to undo them.

> Given the popularity of the confusion, it may help to make a special point in the docs highlighting the need for .value at the end of the each chain.

The chaining behavior of methods [is documented](https://lodash.com/docs/#_).

>  I think lots of folks stop reading the docs after "Iterates over elements of collection invoking iteratee for each element. ",

I can't control devs reading skills and comprehension.

**Comment by brianmhunt** [comment]
> The chaining behavior of methods is documented.

You seem to have misread my comment. The existence of the documentation is not the suggestion I had made, rather its proximity to the inquiry of concern to developers about to use or having trouble with chains that end in `each`.

> I can't control devs reading skills or comprehension.

Again, you seem to have misread my comment. While you cannot control devs' comprehension, you can alleviate your own workload by reducing the cognitive effort necessary for devs to effectively use the platform i.e. without having to search for workarounds for processes that behave outside expecations and filing issues that you must respond to.

**Comment by jdalton** [comment]
Ugg locking the thread dude.
