### ISSUE TITLE
Function to replace the contents of an array?

### ISSUE THREAD

**Issue by mallowigi** [lodash/lodash#919]
Hi, 

In my project I had to find a way to replace the contents of an array without creating a new array, so I thought of setting the array length to 0 then appending the elements one by one.

I wondered if it was possible to add an utility to lodash, say, _.fill(array, newArray) ?

**Comment by jdalton** [comment]
Internally we have [lodash/internal/arrayCopy](https://github.com/lodash/lodash/blob/3.1.0-npm/internal/arrayCopy.js) which you can access. Though if you do you should lock your dependency version down to a fixed version (no `~` or `^` or `>=` pr `<=`) and use something like `"lodash": "3.0.1"`.

```js
var arrayCopy = require('lodash/internal/arrayCopy');
array.length = 0;
arrayCopy(newArray, array);
```

Many times methods have gone from internal to external. We wouldn't use [fill](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-array.prototype.fill) as that's taken by ES for a slightly different function. Since it is a mutation method and doesn't align precisely with our internal use I'll keep an eye on this and see if demand picks up. Until then you can create a mixin:

```js
var _ = require('lodash').runInContext();
_.mixin({ 'fill': func });
```

**Comment by StreetStrider** [comment]
@mallowigi, do you know about `Array.prototype.splice`? It has powers to modify array (remove and add elements) in place, without creating reference to new array.

**Comment by mallowigi** [comment]
Of course i know, but splice only accepts multiple arguments, not an array itself, so in the end i had to do Array.splice.prototype.apply(arr, [0, arr.length].concat(newArr))

Not the most verbose way to do "pushArray"
