### ISSUE TITLE
TypeErrors when working with Mongoose

### ISSUE THREAD

**Issue by riyadhalnur** [lodash/lodash#922]
Seeing this error a lot when running tests for mongoose models in a MEAN app

` TypeError: Function.prototype.apply: Arguments list has wrong type`

**Comment by jdalton** [comment]
Is this with lodash v3? If so could be related to iterating over own properties instead of inherited. If that sounds close you can use [_.toPlainObject](https://lodash.com/docs#toPlainObject) to convert those objects to plain ones. You may also checkout [lodash-migrate](https://www.npmjs.com/package/lodash-migrate) to help give you a heads up to the issue.

**Comment by riyadhalnur** [comment]
Yes, trying to upgrade to 3.1.0 from 2.4.1
