### ISSUE TITLE
_.first(array, n) and _.last(array, n)

### ISSUE THREAD

**Issue by sarahquigley** [lodash/lodash#946]
Underscore.js supports the usage of _.first and _.last in the following manner:
```
_.first(array, n)
 _.last(array, n)
```
These give the first and last n items in an array respectively. Lodash does not appear to support this syntax. 

I am aware that Lodash offers take and takeRight, which give the same functionality. However for easy switch over from Underscore to Lodash, and to maintain Lodash as a superset of underscore, it would be best if these uses of _.first and _.last were supported.

Thanks!

**Comment by StreetStrider** [comment]
@sarahquigley `first` and `last` works the way you want in previous major version of LoDash. This is the one of features that differs in v2 and v3. You can look for others in [Changelog](https://github.com/lodash/lodash/wiki/Changelog).

**Comment by jdalton** [comment]
Hi @sarahquigley! Underscore uses `_.take` as an alias for `_.first` so you can use `_.take(array, n)` for cross-lib compat. For `_.last` although there isn't an Underscore alias you can use `_.takeRight(array, n)`. 

If you're wanting to ease the switch from Underscore to lodash you can always use the 2.4.1 version of the [lodash.first](https://www.npmjs.com/package/lodash.first)  or [lodash.last](https://www.npmjs.com/package/lodash.last) package.

**Comment by jdalton** [comment]
> However for easy switch over from Underscore to Lodash, and to maintain Lodash as a superset of underscore, it would be best if these uses of `_.first` and `_.last` were supported.

lodash has transitioned from following to leading. lodash now has more npm direct+indirect dependents than Underscore and in a little more than a month it'll be the most directly depended on package in npm. It is currently the most downloaded brand on npm (lodash + all its build flavors), accounting for around 3% of npm's daily download traffic, & it's gaining dependents at more than 2:1 of Underscore. In addition Underscore is now aligning more with lodash with additions such as `_.keysIn`, matching `NaN` values in `_.indexOf`, & customizable partial placeholders.

In this case the `_.first` and `_.last` methods were 3x overloaded by supporting no arguments, an `n` argument, and a `predicate` argument. This makes modularizing and optimizing the method more difficult because it has more API baggage to deal with. Splitting it out should clarify the functionality too. For example Underscore has `_.take` as an alias of `_.first` though `_.take` is [traditionally](http://hackage.haskell.org/package/base-4.7.0.2/docs/Prelude.html#v:take) takes an `n` param.

**Comment by KyleAMathews** [comment]
It'd be great to add this to the migrating wiki page as the _.last breakage made it to production for me just now :-( https://github.com/lodash/lodash/wiki/Migrating

**Comment by jdalton** [comment]
It's there as
> Lodash split its overloaded `_.head`, `_.last`, `_.rest`, & `_.initial` out into
`_.take`, `_.takeRight`, `_.drop`, & `_.dropRight`

You can also use[eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash) to help catch these gotchas.

**Comment by KyleAMathews** [comment]
Oh gotcha... missed that. My bad.

**Comment by KyleAMathews** [comment]
Thanks

**Comment by batcer** [comment]
`first()` as it works in lodash now is very strange. If I had a sparse array and it returned the first element from the beginning, then it would be useful. But now it just return `array[0]`! I wonder, why someone should ever choose to use such a function instead of `array[0]` for purpose other than making someone not familiar with this method to go and check it in docs?!

**Comment by jdalton** [comment]
Hi @batcher!

I dig it because it's a companion to `last` which guards against nullish `array` values.

**Comment by StreetStrider** [comment]
@batcer 
> I wonder, why someone should ever choose to use such a function

Me:
```js
// I prefer
.then(first)
// over
.then(x => x[0])
// or
.then(function (x) { return x[0] })
```
In the mean time I don't recall myself working with sparse arrays at all.

**Comment by igordeoliveirasa** [comment]
how to get last of array?

**Comment by jdalton** [comment]
[_.last](https://lodash.com/docs/#last)
