### ISSUE TITLE
Merge is broken

### ISSUE THREAD

**Issue by ivan-kleshnin** [lodash/lodash#973]
Documentation:

> Recursively merges own enumerable properties of the source object(s), that don't resolve to undefined into the destination object. Subsequent sources overwrite property assignments of previous sources.

Example:

```javascript
var merge = require("lodash.merge");

var oldErrors = {
  model: {
    id: ["errors"],
    manufacturer: ["errors"],
  }
};

var newErrors = {
  model: {
    manufacturer: [],
  }
};

console.log(merge({}, oldErrors, newErrors));
```

Results in: `{model: {id: ['errors'], manufacturer: ['errors']}}`
Should be: `{model: {id: ['errors'], manufacturer: []}}`

---
The are no word about merging arrays in documentation.
If this behavior is expected, let's discuss possibility of a function that would behave as described in "should be". 

`Object.assign` does not satisfy, produces `{model: {manufacturer: []}}`

**Comment by jdalton** [comment]
This is by design. Since the method is merging values I see no reason why having an empty `manufacturer` array is expected. Even jQuery's [deep $.extend](http://api.jquery.com/jquery.extend/#jQuery-extend-deep-target-object1-objectN) produces results like lodash. 

Merging arrays is tricky, everyone has a preference. Because of this we allow passing a [customizer callback](https://lodash.com/docs#merge) to `_.merge` so you can customize how arrays are handled. The docs have an example of this.

**Comment by ivan-kleshnin** [comment]
Ok, thanks. You're right, I somehow overlooked those examples. 
Perhaps too many issues today.

**Comment by ivan-kleshnin** [comment]
Just as a note, ImmutableJS version of merge is exactly the same as I proposed.

**Comment by jdalton** [comment]
Then their `merge` is acting more like `assign` which is weird for something called *"merge"*.
