### ISSUE TITLE
improper flatten implementation

### ISSUE THREAD

**Issue by rnavarette** [lodash/lodash#975]
Looks like the 'flatten' definition is backward from underscore.
http://underscorejs.org/#flatten

The change that introduced the 'deep' feature also changed the behavior of _.flatten(vals) to be _NOT_ deep.  This breaks upgrade compatibility as previous versions of lodash (we're on 2.4.1) have were deep by default.

**Comment by jdalton** [comment]
Yap, it's covered in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings) too. Shallow by default is the correct way to do it. It mimics `Array#concat` and does less work by default.

**Comment by jdalton** [comment]
You can use [lodash-migrate](https://www.npmjs.com/package/lodash-migrate) to give you heads up to compat issues.

**Comment by rnavarette** [comment]
Sorry I missed the changelog.  Is Lodash no longer meant to be a 'drop in' replacement for underscore?  Mostly just wondering on this...

Thanks for the quick response.

**Comment by jdalton** [comment]
The changelog also shows ways to support both lodash and Underscore if you're writting libs that may use either.

lodash hasn't been a drop-in replacement since before v1. Before [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) we offered an Underscore compatibility build. But with v3 we’re no longer supporting an Underscore/Backbone build. Over the last year we’ve seen Underscore align more & more with lodash’s API so the need for a separate Underscore build has diminished. 

If you still need compatibility around some of the edges we recommend leveraging modules in lodash v3 to supplement your Underscore use.

**Comment by ldong** [comment]
@rnavarette https://github.com/lodash/lodash/wiki/Changelog#jan-26-2015--diff--docs
Its no longer support being a drop-in.  So, [v2.4.2](https://github.com/lodash/lodash/releases/tag/2.4.2) would be the last version can be used as an drop-in.
